// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { FromExcelData, FromExcelResponses, GetFilesData, GetFilesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getFiles = <ThrowOnError extends boolean = false>(options?: Options<GetFilesData, ThrowOnError>) => (options?.client ?? client).get<GetFilesResponses, unknown, ThrowOnError>({ url: '/import/files', ...options });

export const fromExcel = <ThrowOnError extends boolean = false>(options: Options<FromExcelData, ThrowOnError>) => (options.client ?? client).post<FromExcelResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/import/from-excel',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
