// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type IFormFile = Blob | File;

export type IFormFileCollection = Array<IFormFile>;

export type ImportFile = {
    id: string;
    originalFileName: string;
    uniqueFileName: string;
    status: ImportStatus;
};

export type ImportStatus = 'pending' | 'processing' | 'completed' | 'failed';

export type GetFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/import/files';
};

export type GetFilesResponses = {
    /**
     * OK
     */
    200: Array<ImportFile>;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type FromExcelData = {
    body: {
        files: IFormFileCollection;
    };
    path?: never;
    query?: never;
    url: '/import/from-excel';
};

export type FromExcelResponses = {
    /**
     * OK
     */
    200: unknown;
};
