// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zIFormFile = z.string();

export const zIFormFileCollection = z.array(zIFormFile);

export const zImportStatus = z.enum([
    'pending',
    'processing',
    'completed',
    'failed'
]);

export const zImportFile = z.object({
    id: z.uuid(),
    originalFileName: z.string(),
    uniqueFileName: z.string(),
    status: zImportStatus
});

export const zGetFilesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetFilesResponse = z.array(zImportFile);

export const zFromExcelData = z.object({
    body: z.object({
        files: zIFormFileCollection
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
