// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AjaxAphiaRecordsByNamePartData,
  AjaxAphiaRecordsByNamePartErrors,
  AjaxAphiaRecordsByNamePartResponses,
  AphiaAttributeKeysByIdData,
  AphiaAttributeKeysByIdErrors,
  AphiaAttributeKeysByIdResponses,
  AphiaAttributesByAphiaIdData,
  AphiaAttributesByAphiaIdErrors,
  AphiaAttributesByAphiaIdResponses,
  AphiaAttributeValuesByCategoryIdData,
  AphiaAttributeValuesByCategoryIdErrors,
  AphiaAttributeValuesByCategoryIdResponses,
  AphiaChildrenByAphiaIdData,
  AphiaChildrenByAphiaIdErrors,
  AphiaChildrenByAphiaIdResponses,
  AphiaClassificationByAphiaIdData,
  AphiaClassificationByAphiaIdErrors,
  AphiaClassificationByAphiaIdResponses,
  AphiaDistributionsByAphiaIdData,
  AphiaDistributionsByAphiaIdErrors,
  AphiaDistributionsByAphiaIdResponses,
  AphiaExternalIdByAphiaIdData,
  AphiaExternalIdByAphiaIdErrors,
  AphiaExternalIdByAphiaIdResponses,
  AphiaFullRecordByAphiaIdData,
  AphiaFullRecordByAphiaIdErrors,
  AphiaFullRecordByAphiaIdResponses,
  AphiaIdByNameData,
  AphiaIdByNameErrors,
  AphiaIdByNameResponses,
  AphiaIdsByAttributeKeyIdData,
  AphiaIdsByAttributeKeyIdErrors,
  AphiaIdsByAttributeKeyIdResponses,
  AphiaNameByAphiaIdData,
  AphiaNameByAphiaIdErrors,
  AphiaNameByAphiaIdResponses,
  AphiaRecordByAphiaIdData,
  AphiaRecordByAphiaIdErrors,
  AphiaRecordByAphiaIdResponses,
  AphiaRecordByExternalIdData,
  AphiaRecordByExternalIdErrors,
  AphiaRecordByExternalIdResponses,
  AphiaRecordsByAphiaIdsData,
  AphiaRecordsByAphiaIdsErrors,
  AphiaRecordsByAphiaIdsResponses,
  AphiaRecordsByDateData,
  AphiaRecordsByDateErrors,
  AphiaRecordsByDateResponses,
  AphiaRecordsByMatchNamesData,
  AphiaRecordsByMatchNamesErrors,
  AphiaRecordsByMatchNamesResponses,
  AphiaRecordsByNameData,
  AphiaRecordsByNameErrors,
  AphiaRecordsByNameResponses,
  AphiaRecordsByNamesData,
  AphiaRecordsByNamesErrors,
  AphiaRecordsByNamesResponses,
  AphiaRecordsByTaxonRankIdData,
  AphiaRecordsByTaxonRankIdErrors,
  AphiaRecordsByTaxonRankIdResponses,
  AphiaRecordsByVernacularData,
  AphiaRecordsByVernacularErrors,
  AphiaRecordsByVernacularResponses,
  AphiaSourcesByAphiaIdData,
  AphiaSourcesByAphiaIdErrors,
  AphiaSourcesByAphiaIdResponses,
  AphiaSynonymsByAphiaIdData,
  AphiaSynonymsByAphiaIdErrors,
  AphiaSynonymsByAphiaIdResponses,
  AphiaTaxonRanksByIdData,
  AphiaTaxonRanksByIdErrors,
  AphiaTaxonRanksByIdResponses,
  AphiaTaxonRanksByNameData,
  AphiaTaxonRanksByNameErrors,
  AphiaTaxonRanksByNameResponses,
  AphiaVernacularsByAphiaIdData,
  AphiaVernacularsByAphiaIdErrors,
  AphiaVernacularsByAphiaIdResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get the direct children (max. 50) for a given AphiaID
 *
 * Get the direct children (max. 50) for a given AphiaID
 */
export const aphiaChildrenByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaChildrenByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaChildrenByAphiaIdResponses, AphiaChildrenByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaChildrenByAphiaID/{ID}',
    ...options,
  });

/**
 * Get the complete classification for one taxon. This also includes any sub or super ranks.
 *
 * Get the complete classification for one taxon. This also includes any sub or super ranks.
 */
export const aphiaClassificationByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaClassificationByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AphiaClassificationByAphiaIdResponses,
    AphiaClassificationByAphiaIdErrors,
    ThrowOnError
  >({ url: '/AphiaClassificationByAphiaID/{ID}', ...options });

/**
 * Get all distributions for a given AphiaID
 *
 * Get all distributions for a given AphiaID
 */
export const aphiaDistributionsByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaDistributionsByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaDistributionsByAphiaIdResponses, AphiaDistributionsByAphiaIdErrors, ThrowOnError>(
    { url: '/AphiaDistributionsByAphiaID/{ID}', ...options },
  );

/**
 * Get any external identifier(s) for a given AphiaID
 *
 * Get any external identifier(s) for a given AphiaID
 */
export const aphiaExternalIdByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaExternalIdByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaExternalIdByAphiaIdResponses, AphiaExternalIdByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaExternalIDByAphiaID/{ID}',
    ...options,
  });

/**
 * Get the AphiaID for a given name.
 *
 * Get the AphiaID for a given name. Output: NULL when no match is found; -999 when multiple matches are found; an integer (AphiaID) when one exact match was found
 */
export const aphiaIdByName = <ThrowOnError extends boolean = false>(
  options: Options<AphiaIdByNameData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaIdByNameResponses, AphiaIdByNameErrors, ThrowOnError>({
    url: '/AphiaIDByName/{ScientificName}',
    ...options,
  });

/**
 * Get the name for a given AphiaID
 *
 * Get the name for a given AphiaID
 */
export const aphiaNameByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaNameByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaNameByAphiaIdResponses, AphiaNameByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaNameByAphiaID/{ID}',
    ...options,
  });

/**
 * Get the complete AphiaRecord for a given AphiaID
 *
 * Get the complete AphiaRecord for a given AphiaID
 */
export const aphiaRecordByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordByAphiaIdResponses, AphiaRecordByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaRecordByAphiaID/{ID}',
    ...options,
  });

/**
 * Get an AphiaRecord for multiple AphiaIDs in one go (max: 50)
 *
 * Get an AphiaRecord for multiple AphiaIDs in one go (max: 50)
 */
export const aphiaRecordsByAphiaIds = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByAphiaIdsData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByAphiaIdsResponses, AphiaRecordsByAphiaIdsErrors, ThrowOnError>({
    url: '/AphiaRecordsByAphiaIDs',
    ...options,
  });

/**
 * Get the Aphia Record for a given external identifier
 *
 * Get the Aphia Record for a given external identifier
 */
export const aphiaRecordByExternalId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordByExternalIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordByExternalIdResponses, AphiaRecordByExternalIdErrors, ThrowOnError>({
    url: '/AphiaRecordByExternalID/{ID}',
    ...options,
  });

/**
 * Lists all AphiaRecords (taxa) that have their last edit action (modified or added) during the specified period
 *
 * Lists all AphiaRecords (taxa) that have their last edit action (modified or added) during the specified period
 */
export const aphiaRecordsByDate = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByDateData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByDateResponses, AphiaRecordsByDateErrors, ThrowOnError>({
    url: '/AphiaRecordsByDate',
    ...options,
  });

/**
 * Try to find AphiaRecords using the TAXAMATCH fuzzy matching algorithm by Tony Rees
 *
 * For each given scientific name (may include authority), try to find one or more AphiaRecords, using the TAXAMATCH fuzzy matching algorithm by Tony Rees.<br/>This allows you to (fuzzy) match multiple names in one call. Limited to 50 names at once for performance reasons
 */
export const aphiaRecordsByMatchNames = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByMatchNamesData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByMatchNamesResponses, AphiaRecordsByMatchNamesErrors, ThrowOnError>({
    url: '/AphiaRecordsByMatchNames',
    ...options,
  });

/**
 * Get one or more matching (max. 50) AphiaRecords for a given name
 *
 * Get one or more matching (max. 50) AphiaRecords for a given name
 */
export const aphiaRecordsByName = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByNameData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByNameResponses, AphiaRecordsByNameErrors, ThrowOnError>({
    url: '/AphiaRecordsByName/{ScientificName}',
    ...options,
  });

/**
 * For each given scientific name, try to find one or more AphiaRecords
 *
 * For each given scientific name, try to find one or more AphiaRecords. This allows you to match multiple names in one call. Limited to 500 names at once for performance reasons.
 */
export const aphiaRecordsByNames = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByNamesData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByNamesResponses, AphiaRecordsByNamesErrors, ThrowOnError>({
    url: '/AphiaRecordsByNames',
    ...options,
  });

/**
 * Get one or more Aphia Records (max. 50) for a given vernacular
 *
 * Get one or more Aphia Records (max. 50) for a given vernacular
 */
export const aphiaRecordsByVernacular = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByVernacularData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByVernacularResponses, AphiaRecordsByVernacularErrors, ThrowOnError>({
    url: '/AphiaRecordsByVernacular/{Vernacular}',
    ...options,
  });

/**
 * Get all synonyms for a given AphiaID
 *
 * Get all synonyms for a given AphiaID
 */
export const aphiaSynonymsByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaSynonymsByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaSynonymsByAphiaIdResponses, AphiaSynonymsByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaSynonymsByAphiaID/{ID}',
    ...options,
  });

/**
 * Get all vernaculars for a given AphiaID
 *
 * Get all vernaculars for a given AphiaID
 */
export const aphiaVernacularsByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaVernacularsByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaVernacularsByAphiaIdResponses, AphiaVernacularsByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaVernacularsByAphiaID/{ID}',
    ...options,
  });

/**
 * Get one or more sources/references including links, for one AphiaID
 *
 * Get one or more sources/references including links, for one AphiaID
 */
export const aphiaSourcesByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaSourcesByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaSourcesByAphiaIdResponses, AphiaSourcesByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaSourcesByAphiaID/{ID}',
    ...options,
  });

/**
 * Get taxonomic ranks by their identifier
 *
 * Get taxonomic ranks by their identifier
 */
export const aphiaTaxonRanksById = <ThrowOnError extends boolean = false>(
  options: Options<AphiaTaxonRanksByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaTaxonRanksByIdResponses, AphiaTaxonRanksByIdErrors, ThrowOnError>({
    url: '/AphiaTaxonRanksByID/{ID}',
    ...options,
  });

/**
 * Get taxonomic ranks by their name
 *
 * Get taxonomic ranks by their name
 */
export const aphiaTaxonRanksByName = <ThrowOnError extends boolean = false>(
  options: Options<AphiaTaxonRanksByNameData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaTaxonRanksByNameResponses, AphiaTaxonRanksByNameErrors, ThrowOnError>({
    url: '/AphiaTaxonRanksByName/{taxonRank}',
    ...options,
  });

/**
 * Get the AphiaRecords for a given taxonRankID (max 50)
 *
 * Get the AphiaRecords for a given taxonRankID (max 50)
 */
export const aphiaRecordsByTaxonRankId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaRecordsByTaxonRankIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaRecordsByTaxonRankIdResponses, AphiaRecordsByTaxonRankIdErrors, ThrowOnError>({
    url: '/AphiaRecordsByTaxonRankID/{ID}',
    ...options,
  });

/**
 * Get the complete AphiaFullRecord for a given AphiaID
 *
 * Returns the linked open data implementation of an AphiaRecord for a given AphiaID. There are multiple formats available that can be chosen with the Accept header. The default format is JSON-LD but RDF, Turtle and N-triples are also supported.
 */
export const aphiaFullRecordByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaFullRecordByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaFullRecordByAphiaIdResponses, AphiaFullRecordByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaRecordFullByAphiaID/{ID}',
    ...options,
  });

/**
 * Get attribute definitions
 *
 * Get attribute definitions. To refer to root items specify ID = &#039;0&#039;
 */
export const aphiaAttributeKeysById = <ThrowOnError extends boolean = false>(
  options: Options<AphiaAttributeKeysByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaAttributeKeysByIdResponses, AphiaAttributeKeysByIdErrors, ThrowOnError>({
    url: '/AphiaAttributeKeysByID/{ID}',
    ...options,
  });

/**
 * Get list values that are grouped by an CateogryID
 *
 * Get list values that are grouped by an CateogryID
 */
export const aphiaAttributeValuesByCategoryId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaAttributeValuesByCategoryIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    AphiaAttributeValuesByCategoryIdResponses,
    AphiaAttributeValuesByCategoryIdErrors,
    ThrowOnError
  >({ url: '/AphiaAttributeValuesByCategoryID/{ID}', ...options });

/**
 * Get a list of AphiaID's (max 50) with attribute tree for a given attribute definition ID
 *
 * Get a list of AphiaID&#039;s (max 50) with attribute tree for a given attribute definition ID
 */
export const aphiaIdsByAttributeKeyId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaIdsByAttributeKeyIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaIdsByAttributeKeyIdResponses, AphiaIdsByAttributeKeyIdErrors, ThrowOnError>({
    url: '/AphiaIDsByAttributeKeyID/{ID}',
    ...options,
  });

/**
 * Get a list of attributes for a given AphiaID
 *
 * Get a list of attributes for a given AphiaID
 */
export const aphiaAttributesByAphiaId = <ThrowOnError extends boolean = false>(
  options: Options<AphiaAttributesByAphiaIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<AphiaAttributesByAphiaIdResponses, AphiaAttributesByAphiaIdErrors, ThrowOnError>({
    url: '/AphiaAttributesByAphiaID/{ID}',
    ...options,
  });

/**
 * Get taxa suggestion for a given prefix of a taxon name.
 *
 * Get taxa suggestion for a given prefix of a taxon name.
 */
export const ajaxAphiaRecordsByNamePart = <ThrowOnError extends boolean = false>(
  options: Options<AjaxAphiaRecordsByNamePartData, ThrowOnError>,
) =>
  (options.client ?? client).get<AjaxAphiaRecordsByNamePartResponses, AjaxAphiaRecordsByNamePartErrors, ThrowOnError>({
    url: '/AjaxAphiaRecordsByNamePart/{NamePart}',
    ...options,
  });
