// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { FetchElectricityParametersData, FetchElectricityParametersResponses, FetchElectricityTariffsData, FetchElectricityTariffsResponses, FetchGasParametersData, FetchGasParametersResponses, FetchGasTariffsData, FetchGasTariffsResponses, FetchNetworkChargeElectricityData, FetchNetworkChargeElectricityResponses, FetchNetworkChargeGasData, FetchNetworkChargeGasResponses, FetchSupplierCardElectricityData, FetchSupplierCardElectricityResponses, FetchSupplierCardGasData, FetchSupplierCardGasResponses, FetchSuppliersElectricityData, FetchSuppliersElectricityResponses, FetchSuppliersGasData, FetchSuppliersGasResponses, FetchSupplierVariantsElectricityData, FetchSupplierVariantsElectricityResponses, FetchSupplierVariantsGasData, FetchSupplierVariantsGasResponses, FetchTariffResultsData, FetchTariffResultsResponses, FetchUniversalInformationElectricityData, FetchUniversalInformationElectricityResponses, FetchUniversalInformationGasData, FetchUniversalInformationGasResponses, GetNetworkChargeResultsData, GetNetworkChargeResultsResponses, GetParametersElectricityData, GetParametersElectricityResponses, GetParametersGasData, GetParametersGasResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const fetchNetworkChargeElectricity = <ThrowOnError extends boolean = false>(options: Options<FetchNetworkChargeElectricityData, ThrowOnError>) => (options.client ?? client).post<FetchNetworkChargeElectricityResponses, unknown, ThrowOnError>({
    url: '/api/getag/network-charges/electricity/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getParametersElectricity = <ThrowOnError extends boolean = false>(options?: Options<GetParametersElectricityData, ThrowOnError>) => (options?.client ?? client).get<GetParametersElectricityResponses, unknown, ThrowOnError>({ url: '/api/getag/network-charges/electricity/parameters', ...options });

export const fetchNetworkChargeGas = <ThrowOnError extends boolean = false>(options: Options<FetchNetworkChargeGasData, ThrowOnError>) => (options.client ?? client).post<FetchNetworkChargeGasResponses, unknown, ThrowOnError>({
    url: '/api/getag/network-charges/gas/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getParametersGas = <ThrowOnError extends boolean = false>(options?: Options<GetParametersGasData, ThrowOnError>) => (options?.client ?? client).get<GetParametersGasResponses, unknown, ThrowOnError>({ url: '/api/getag/network-charges/gas/parameters', ...options });

export const getNetworkChargeResults = <ThrowOnError extends boolean = false>(options: Options<GetNetworkChargeResultsData, ThrowOnError>) => (options.client ?? client).get<GetNetworkChargeResultsResponses, unknown, ThrowOnError>({ url: '/api/getag/network-charges/results/{workflowId}', ...options });

export const fetchElectricityTariffs = <ThrowOnError extends boolean = false>(options: Options<FetchElectricityTariffsData, ThrowOnError>) => (options.client ?? client).post<FetchElectricityTariffsResponses, unknown, ThrowOnError>({
    url: '/api/getag/tariffs/electricity/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const fetchElectricityParameters = <ThrowOnError extends boolean = false>(options?: Options<FetchElectricityParametersData, ThrowOnError>) => (options?.client ?? client).get<FetchElectricityParametersResponses, unknown, ThrowOnError>({ url: '/api/getag/tariffs/electricity/parameters', ...options });

export const fetchGasTariffs = <ThrowOnError extends boolean = false>(options: Options<FetchGasTariffsData, ThrowOnError>) => (options.client ?? client).post<FetchGasTariffsResponses, unknown, ThrowOnError>({
    url: '/api/getag/tariffs/gas/fetch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const fetchGasParameters = <ThrowOnError extends boolean = false>(options?: Options<FetchGasParametersData, ThrowOnError>) => (options?.client ?? client).get<FetchGasParametersResponses, unknown, ThrowOnError>({ url: '/api/getag/tariffs/gas/parameters', ...options });

export const fetchTariffResults = <ThrowOnError extends boolean = false>(options: Options<FetchTariffResultsData, ThrowOnError>) => (options.client ?? client).get<FetchTariffResultsResponses, unknown, ThrowOnError>({ url: '/api/getag/tariffs/results/{workflowId}', ...options });

export const fetchSuppliersElectricity = <ThrowOnError extends boolean = false>(options?: Options<FetchSuppliersElectricityData, ThrowOnError>) => (options?.client ?? client).get<FetchSuppliersElectricityResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/electricity/fetch', ...options });

export const fetchSupplierCardElectricity = <ThrowOnError extends boolean = false>(options: Options<FetchSupplierCardElectricityData, ThrowOnError>) => (options.client ?? client).get<FetchSupplierCardElectricityResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/electricity/{supplierId}/card', ...options });

export const fetchSupplierVariantsElectricity = <ThrowOnError extends boolean = false>(options: Options<FetchSupplierVariantsElectricityData, ThrowOnError>) => (options.client ?? client).get<FetchSupplierVariantsElectricityResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/electricity/{supplierId}/variants', ...options });

export const fetchUniversalInformationElectricity = <ThrowOnError extends boolean = false>(options: Options<FetchUniversalInformationElectricityData, ThrowOnError>) => (options.client ?? client).post<FetchUniversalInformationElectricityResponses, unknown, ThrowOnError>({
    url: '/api/getag/supplier/electricity/universal-info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const fetchSuppliersGas = <ThrowOnError extends boolean = false>(options?: Options<FetchSuppliersGasData, ThrowOnError>) => (options?.client ?? client).get<FetchSuppliersGasResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/gas/fetch', ...options });

export const fetchSupplierCardGas = <ThrowOnError extends boolean = false>(options: Options<FetchSupplierCardGasData, ThrowOnError>) => (options.client ?? client).get<FetchSupplierCardGasResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/gas/{supplierId}/card', ...options });

export const fetchSupplierVariantsGas = <ThrowOnError extends boolean = false>(options: Options<FetchSupplierVariantsGasData, ThrowOnError>) => (options.client ?? client).get<FetchSupplierVariantsGasResponses, unknown, ThrowOnError>({ url: '/api/getag/supplier/gas/{supplierId}/variants', ...options });

export const fetchUniversalInformationGas = <ThrowOnError extends boolean = false>(options: Options<FetchUniversalInformationGasData, ThrowOnError>) => (options.client ?? client).post<FetchUniversalInformationGasResponses, unknown, ThrowOnError>({
    url: '/api/getag/supplier/gas/universal-info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
