// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AdditionalCostGroupElectricityDto = {
    transformer?: null | number;
    communicationDevice?: null | number;
    technicalControlDevice?: null | number;
    remoteReading?: null | number;
    meterDevice?: null | number;
    additionalReadings?: null | number;
    additionalBillings?: null | number;
    extendedAdditionalCosts?: null | Array<number>;
};

export type AdditionalCostGroupGasDto = {
    volumeConverter?: null | number;
    communicationDevice?: null | number;
    technicalControlDevice?: null | number;
    remoteReading?: null | number;
    meterDevice?: null | number;
    additionalReadings?: null | number;
    additionalBillings?: null | number;
    extendedAdditionalCosts?: null | Array<number>;
};

export type CalculationConfigurationDto = {
    id: number;
    value: number;
};

export type ChargeDetailsDto = {
    quantityModel?: null | number;
    timeFactor?: null | number;
    blindEnergyDetails?: null | Array<PriceDetailDto>;
    basePriceDetails?: null | Array<PriceDetailDto>;
    powerDetails?: null | Array<PriceDetailDto>;
    moreAndLessQuantityDetails?: null | Array<PriceDetailDto>;
    activeEnergyHighTariffDetails?: null | Array<PriceDetailDto>;
    activeEnergyLowTariffDetails?: null | Array<PriceDetailDto>;
    measurementDetails?: null | Array<PriceDetailDto>;
    msbDetails?: null | Array<PriceDetailDto>;
    billingDetails?: null | Array<PriceDetailDto>;
};

export type DiscountDto = {
    discountType?: null | string;
    discountKind?: null | string;
    discountRate?: null | number;
    discountValue?: null | number;
};

export type FlatCostDto = {
    id?: null | number;
    includedInTotalPrice?: number;
    bdewArticles?: null | Array<number>;
    details?: null | PriceDetailDto;
};

export type FlatCostTimeSliceDto = {
    id?: number;
    includedInTotalPrice?: number;
    bdewArticles?: null | Array<string>;
    details?: null | PriceDetailsDto;
};

export type InquiryFailureDto = {
    errorCode: string;
    errorMessage: string;
    details?: null | string;
    occurredAtUtc?: string;
};

export type InquiryStatus = 'pending' | 'success' | 'failed';

export type InquirySuccessDto = {
    workflowId: string;
};

export type MarketAreaLevyDto = {
    value?: null | number;
    marketAreaId?: null | number;
    marketAreaName?: null | string;
    marketAreaEic?: null | string;
};

export type NetworkChargeElectricityGridInfoDto = {
    uniqueId?: null | string;
    chargeTypeId?: null | number;
    loadType?: null | number;
    medium?: null | number;
    chargeCategory?: null | number;
    flatCosts?: null | Array<FlatCostDto>;
    chargeDetails?: null | ChargeDetailsDto;
    chargeId?: null | number;
    chargeRootId?: null | number;
    chargeName?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
    isPreliminary?: null | number;
    regionId?: null | number;
    networkOperators?: null | Array<NetworkChargeSupplierInfoDto>;
    basicSuppliers?: null | Array<NetworkChargeSupplierInfoDto>;
};

export type NetworkChargeElectricityParametersDto = {
    networkCodes: Array<string>;
    voltageOrPressureLevels: Array<string>;
    meterTypes: Array<string>;
    customerGroups: Array<string>;
};

export type NetworkChargeElectricityRequestDto = {
    items: Array<NetworkChargeElectricityRequestItemDto>;
};

export type NetworkChargeElectricityRequestItemDto = {
    consumptionHighTariffKWh: number;
    consumptionLowTariffKWh?: null | number;
    voltageLevelExtraction?: null | number;
    voltageLevelMeasurement?: null | number;
    feeType?: null | number;
    customerType?: null | number;
    lastConsumerGroup?: null | number;
    quantitySurcharge?: null | number;
    blindEnergyHighTariffKvarh?: null | number;
    blindEnergyLowTariffKvarh?: null | number;
    blindEnergyType?: null | number;
    additionalCostGroup?: null | AdditionalCostGroupElectricityDto;
    postalCode: string;
    uid?: null | string;
    municipalityKey?: null | string;
    street?: null | string;
    houseNumber?: null | string;
    referenceDate: string;
    powerKw?: null | number;
    meterType?: null | number;
    concessionType?: null | number;
    networkOperatorCode?: null | string;
    meteringPointOperatorCode?: null | string;
    meteringServiceProviderCode?: null | string;
    regionId?: null | number;
    outputConfiguration?: null | number;
    calculationConfigurations?: null | Array<CalculationConfigurationDto>;
};

export type NetworkChargeElectricitySuccessItemDto = {
    consumptionHighTariffKWh?: null | number;
    consumptionLowTariffKWh?: null | number;
    workPriceHighTariff?: null | number;
    workPriceLowTariff?: null | number;
    blindEnergyCost?: null | number;
    meterPriceReadingTotal?: null | number;
    remoteReadingCost?: null | number;
    concessionFeeHighTariff?: null | number;
    concessionFeeLowTariff?: null | number;
    concessionFeeTariffCustomerCtPerKWh?: null | number;
    concessionFeeSpecialContractCustomerCtPerKWh?: null | number;
    concessionFeeWeakLoadCtPerKWh?: null | number;
    chpLevy?: null | number;
    offshoreLevy?: null | number;
    shutdownLevy?: null | number;
    specialCustomerSurcharge?: null | number;
    eegLevy?: null | number;
    feeType?: null | number;
    gridInfos?: null | Array<NetworkChargeElectricityGridInfoDto>;
    uid?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
    totalPrice?: null | number;
    powerPrice?: null | number;
    basePrice?: null | number;
    meterOperationCost?: null | number;
    measurementAndReadingCost?: null | number;
    billingCost?: null | number;
    concessionFeeTotal?: null | number;
    meterType?: null | number;
};

export type NetworkChargeGasGridInfoDto = {
    flatCostsTimeSlice?: null | Array<FlatCostTimeSliceDto>;
    chargeId?: null | number;
    chargeRootId?: null | number;
    chargeName?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
    isPreliminary?: null | number;
    regionId?: null | number;
    networkOperators?: null | Array<NetworkChargeSupplierInfoDto>;
    basicSuppliers?: null | Array<NetworkChargeSupplierInfoDto>;
};

export type NetworkChargeGasParametersDto = {
    voltageOrPressureLevels: Array<string>;
    meterTypes: Array<string>;
    customerGroups: Array<string>;
};

export type NetworkChargeGasRequestDto = {
    items: Array<NetworkChargeGasRequestItemDto>;
};

export type NetworkChargeGasRequestItemDto = {
    consumptionKWh: number;
    pressureLevel: number;
    loadType: number;
    meterSize?: null | number;
    billingInterval?: null | number;
    biogasShare?: null | number;
    additionalCostGroup?: null | AdditionalCostGroupGasDto;
    postalCode: string;
    uid?: null | string;
    municipalityKey?: null | string;
    street?: null | string;
    houseNumber?: null | string;
    referenceDate: string;
    powerKw?: null | number;
    meterType?: null | number;
    concessionType?: null | number;
    networkOperatorCode?: null | string;
    meteringPointOperatorCode?: null | string;
    meteringServiceProviderCode?: null | string;
    regionId?: null | number;
    outputConfiguration?: null | number;
    calculationConfigurations?: null | Array<CalculationConfigurationDto>;
};

export type NetworkChargeGasSuccessItemDto = {
    consumption?: null | number;
    workPrice?: null | number;
    pressureLevel?: null | number;
    meterSizeFrom?: null | number;
    meterSizeTo?: null | number;
    billingInterval?: null | number;
    powerPriceType?: null | number;
    workPriceType?: null | number;
    basePriceConsumption?: null | number;
    basePricePower?: null | number;
    consumptionFix?: null | number;
    workPriceFix?: null | number;
    co2PriceNaturalGas?: null | number;
    referenceCo2PriceNaturalGas?: null | number;
    powerFix?: null | number;
    powerTransferred?: null | number;
    controlEnergyLevy?: null | Array<MarketAreaLevyDto>;
    balancingLevy?: null | Array<MarketAreaLevyDto>;
    gridInfo?: null | NetworkChargeGasGridInfoDto;
    uid?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
    totalPrice?: null | number;
    powerPrice?: null | number;
    basePrice?: null | number;
    meterOperationCost?: null | number;
    measurementAndReadingCost?: null | number;
    billingCost?: null | number;
    concessionFeeTotal?: null | number;
    meterType?: null | number;
};

export type NetworkChargeResponseItemBaseDto = ({
    $type?: 'electricity';
} & NetworkChargeResponseItemBaseDtoNetworkChargeElectricityResponseItemDto) | ({
    $type?: 'gas';
} & NetworkChargeResponseItemBaseDtoNetworkChargeGasResponseItemDto);

export type NetworkChargeResponseItemBaseDtoNetworkChargeElectricityResponseItemDto = {
    $type?: 'electricity';
    request: NetworkChargeElectricityRequestItemDto;
    successResult?: null | NetworkChargeElectricitySuccessItemDto;
    workflowId: string;
    status: InquiryStatus;
    failureResult?: null | InquiryFailureDto;
};

export type NetworkChargeResponseItemBaseDtoNetworkChargeGasResponseItemDto = {
    $type?: 'gas';
    request: NetworkChargeGasRequestItemDto;
    successResult?: null | NetworkChargeGasSuccessItemDto;
    workflowId: string;
    status: InquiryStatus;
    failureResult?: null | InquiryFailureDto;
};

export type NetworkChargeSupplierInfoDto = {
    supplierId?: null | number;
    supplierName?: null | string;
    marketRoleId?: null | number;
    associationNumber?: null | string;
    associationNumberShort?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
};

export type PriceDetailDto = {
    id?: null | number;
    value?: null | number;
    referenceValue?: null | number;
    quantity?: null | number;
    quantityUnit?: null | string;
    time?: null | number;
    timeUnit?: null | string;
    discountValue?: null | number;
    quantityModel?: null | number;
    timeFactor?: null | number;
    meterType?: null | number;
    billingInterval?: null | number;
    dataProvision?: null | number;
    validFrom?: null | string;
    validTo?: null | string;
    discounts?: DiscountDto;
};

export type PriceDetailsDto = {
    id?: null | number;
    value?: number;
    referenceValue?: number;
    time?: null | number;
    timeUnit?: null | string;
    quantity?: number;
    quantityUnit?: null | string;
    discountValue?: null | number;
    validFrom?: string;
    validTo?: string;
    discounts?: null | Array<DiscountDto>;
};

export type SupplierCardItemDto = {
    companyName?: null | string;
    shortName?: null | string;
    street?: null | string;
    houseNumber?: null | string;
    zipCode?: null | string;
    city?: null | string;
    country?: null | string;
    phone?: null | string;
    fax?: null | string;
    website?: null | string;
    email?: null | string;
    poBoxZipCode?: null | string;
    poBoxCity?: null | string;
    poBox?: null | string;
    associationNumber?: null | string;
    statusId?: null | number;
    remark?: null | string;
};

export type SupplierItemDto = {
    supplierId: number;
    supplierName: string;
    brandId?: null | number;
    brandName?: null | string;
};

export type SupplierVariantItemDto = {
    supplierId: number;
    supplierName: string;
    brandId?: null | number;
    brandName?: null | string;
    tariffId: number;
    variantId: string;
    tariffName: string;
    isBasicSupplyTariff: boolean;
};

export type TariffBonusDto = {
    bonusId?: null | number;
    bonusName?: null | string;
    bonusType?: null | string;
    amountNet?: null | number;
    amountGross?: null | number;
    condition?: null | string;
    paymentMonth?: null | number;
};

export type TariffElectricityRequestDto = {
    items: Array<TariffElectricityRequestItemDto>;
};

export type TariffElectricityRequestItemDto = {
    consumptionHighTariffKWh: number;
    consumptionLowTariffKWh?: null | number;
    meterType?: null | number;
    loadProfiles?: null | string;
    smartMeterFlag?: null | number;
    uid?: null | string;
    postalCode: string;
    city?: null | string;
    networkOperatorCode?: null | string;
    basicSupplierCode?: null | string;
    gridAreaCode?: null | string;
    customerType: number;
    tariffType?: null | number;
    referenceDate?: null | string;
    pageSize?: null | number;
    pageNumber?: null | number;
    sorting?: null | number;
    indicator?: null | number;
    limitPerSupplier?: null | number;
    tariffsFromBasicSuppliers?: null | number;
    basicSupplyTariffs?: null | number;
    tariffHandling?: null | number;
    supplierIds?: null | string;
    brandIds?: null | string;
    tariffCodes?: null | string;
    tariffRootIds?: null | string;
    tariffRootIdsMinFilter?: null | string;
    certificateIds?: null | string;
    salesChannelIds?: null | string;
    regionalSupplierRadius?: null | number;
    ecoFlag?: null | number;
    packageFlag?: null | number;
    fixPriceFlag?: null | number;
    prepaymentFlag?: null | number;
    portalGuideline?: null | number;
    bonusFlag?: null | number;
    materialBonusFlag?: null | number;
    priceGuaranteeFlag?: null | number;
    depositFlag?: null | number;
    specialDeductionFlag?: null | number;
    existingCustomerTariffFlag?: null | number;
    maxContractDurationMonths?: null | number;
    maxRenewalMonths?: null | number;
    maxCancellationPeriodCode?: null | number;
    minPriceGuaranteeMonths?: null | number;
    comparisonTariffId?: null | number;
    comparisonVariantId?: null | string;
    comparisonGuideline?: null | number;
    comparisonSupplierId?: null | number;
    ignoreLimitsUpToKWh?: null | number;
    details?: null | number;
    baiExtendedWhiteList?: null | string;
    baiExtendedBlackList?: null | string;
};

export type TariffElectricityResponseItemDto = {
    request: TariffElectricityRequestItemDto;
    successResult?: null | TariffElectricitySuccessResultDto;
    workflowId: string;
    status: InquiryStatus;
    failureResult?: null | InquiryFailureDto;
};

export type TariffElectricityStrommixDto = {
    year?: null | number;
    co2EmissionsGramPerKWh?: null | number;
    radioactiveWasteGramPerKWh?: null | number;
    nuclearPercent?: null | number;
    renewableTotalPercent?: null | number;
    fossilTotalPercent?: null | number;
};

export type TariffElectricitySuccessItemDto = {
    workPriceHighTariffNetCtPerKWh?: null | number;
    workPriceHighTariffGrossCtPerKWh?: null | number;
    workPriceLowTariffNetCtPerKWh?: null | number;
    workPriceLowTariffGrossCtPerKWh?: null | number;
    workPriceEnergyHighTariffNet?: null | number;
    workPriceEnergyHighTariffGross?: null | number;
    workPriceEnergyLowTariffNet?: null | number;
    workPriceEnergyLowTariffGross?: null | number;
    workPriceEnergyHighTariffNetCtPerKWh?: null | number;
    workPriceEnergyHighTariffGrossCtPerKWh?: null | number;
    workPriceEnergyLowTariffNetCtPerKWh?: null | number;
    workPriceEnergyLowTariffGrossCtPerKWh?: null | number;
    isEcoTariff?: null | boolean;
    strommix?: null | TariffElectricityStrommixDto;
    uid?: null | string;
    tariffId?: null | number;
    tariffVariantId?: null | string;
    tariffRootId?: null | number;
    tariffCode?: null | string;
    tariffName?: null | string;
    tariffInfo?: null | string;
    supplierId?: null | number;
    supplierName?: null | string;
    brandId?: null | number;
    validFrom?: null | string;
    validTo?: null | string;
    displayFrom?: null | string;
    displayTo?: null | string;
    totalPriceNet?: null | number;
    totalPriceGross?: null | number;
    totalPriceWithoutBonusesNet?: null | number;
    totalPriceWithoutBonusesGross?: null | number;
    basePriceNet?: null | number;
    basePriceGross?: null | number;
    workPriceNet?: null | number;
    workPriceGross?: null | number;
    basePriceEnergyNet?: null | number;
    basePriceEnergyGross?: null | number;
    savingsNet?: null | number;
    savingsGross?: null | number;
    isPrepaymentTariff?: null | boolean;
    isPackageTariff?: null | boolean;
    isBasicSupplyTariff?: null | boolean;
    isComparisonTariff?: null | boolean;
    contractDuration?: null | string;
    contractDurationId?: null | number;
    contractExtension?: null | string;
    contractExtensionId?: null | number;
    cancellationPeriod?: null | string;
    cancellationPeriodId?: null | number;
    packageAmountKWh?: null | number;
    packagePriceNet?: null | number;
    packagePriceGross?: null | number;
    packageOverConsumptionPriceNetCtPerKWh?: null | number;
    packageOverConsumptionPriceGrossCtPerKWh?: null | number;
    gridInfo?: null | TariffGridInfoBaseDto;
    bonuses?: null | Array<TariffBonusDto>;
    surcharges?: null | Array<TariffSurchargeDto>;
    additionalInfo?: null | Array<TariffInfoDto>;
};

export type TariffElectricitySuccessResultDto = {
    tariffs?: null | Array<TariffElectricitySuccessItemDto>;
    totalResultCount?: null | number;
    pageResultCount?: null | number;
    postalCode?: null | string;
    city?: null | string;
    uid?: null | string;
};

export type TariffGasRequestDto = {
    items: Array<TariffGasRequestItemDto>;
};

export type TariffGasRequestItemDto = {
    consumptionKWh: number;
    powerKw?: null | number;
    uid?: null | string;
    postalCode: string;
    city?: null | string;
    networkOperatorCode?: null | string;
    basicSupplierCode?: null | string;
    gridAreaCode?: null | string;
    customerType: number;
    tariffType?: null | number;
    referenceDate?: null | string;
    pageSize?: null | number;
    pageNumber?: null | number;
    sorting?: null | number;
    indicator?: null | number;
    limitPerSupplier?: null | number;
    tariffsFromBasicSuppliers?: null | number;
    basicSupplyTariffs?: null | number;
    tariffHandling?: null | number;
    supplierIds?: null | string;
    brandIds?: null | string;
    tariffCodes?: null | string;
    tariffRootIds?: null | string;
    tariffRootIdsMinFilter?: null | string;
    certificateIds?: null | string;
    salesChannelIds?: null | string;
    regionalSupplierRadius?: null | number;
    ecoFlag?: null | number;
    packageFlag?: null | number;
    fixPriceFlag?: null | number;
    prepaymentFlag?: null | number;
    portalGuideline?: null | number;
    bonusFlag?: null | number;
    materialBonusFlag?: null | number;
    priceGuaranteeFlag?: null | number;
    depositFlag?: null | number;
    specialDeductionFlag?: null | number;
    existingCustomerTariffFlag?: null | number;
    maxContractDurationMonths?: null | number;
    maxRenewalMonths?: null | number;
    maxCancellationPeriodCode?: null | number;
    minPriceGuaranteeMonths?: null | number;
    comparisonTariffId?: null | number;
    comparisonVariantId?: null | string;
    comparisonGuideline?: null | number;
    comparisonSupplierId?: null | number;
    ignoreLimitsUpToKWh?: null | number;
    details?: null | number;
    baiExtendedWhiteList?: null | string;
    baiExtendedBlackList?: null | string;
};

export type TariffGridDateValueDto = {
    id?: number;
    name?: null | string;
    value: string;
};

export type TariffGridDoubleValueDto = {
    id?: number;
    name?: null | string;
    value: number;
};

export type TariffGridInfoBaseDto = ({
    $type?: 'electricity';
} & TariffGridInfoBaseDtoTariffElectricityGridInfoDto) | ({
    $type?: 'gas';
} & TariffGridInfoBaseDtoTariffGasGridInfoDto);

export type TariffGridInfoBaseDtoTariffElectricityGridInfoDto = {
    $type?: 'electricity';
    workPriceHighTariffNetCtPerKWh?: null | number;
    workPriceLowTariffNetCtPerKWh?: null | number;
    concessionFeeHighTariffCtPerKWh?: null | number;
    concessionFeeLowTariffCtPerKWh?: null | number;
    feeType?: null | number;
    meterType?: null | number;
    voltageLevelExtraction?: null | number;
    voltageLevelMeasurement?: null | number;
    totalChargeNet?: null | number;
    basePriceNet?: null | number;
    powerPriceNet?: null | number;
    billingFee?: null | number;
    meteringAndReadingFee?: null | number;
    meteringEquipmentFee?: null | number;
    meterPriceAndReadingFee?: null | number;
    levies?: null | Array<TariffGridLevyDto>;
    taxes?: null | Array<TariffGridTaxDto>;
    miscellaneousInfo?: null | Array<TariffGridMiscInfoDto>;
};

export type TariffGridInfoBaseDtoTariffGasGridInfoDto = {
    $type?: 'gas';
    workPriceNetCtPerKWh?: null | number;
    concessionFeeCtPerKWh?: null | number;
    pressureLevel?: null | number;
    meterType?: null | number;
    meterSizeFrom?: null | number;
    meterSizeTo?: null | number;
    totalChargeNet?: null | number;
    basePriceNet?: null | number;
    powerPriceNet?: null | number;
    billingFee?: null | number;
    meteringAndReadingFee?: null | number;
    meteringEquipmentFee?: null | number;
    meterPriceAndReadingFee?: null | number;
    levies?: null | Array<TariffGridLevyDto>;
    taxes?: null | Array<TariffGridTaxDto>;
    miscellaneousInfo?: null | Array<TariffGridMiscInfoDto>;
};

export type TariffGridIntValueDto = {
    id?: number;
    name?: null | string;
    value: number;
};

export type TariffGridLevyDto = {
    key?: null | string;
    name?: null | string;
    amount?: null | number;
    miscellaneousInfo?: null | Array<TariffGridMiscInfoDto>;
};

export type TariffGridMiscInfoDto = {
    intValues?: null | Array<TariffGridIntValueDto>;
    doubleValues?: null | Array<TariffGridDoubleValueDto>;
    stringValues?: null | Array<TariffGridStringValueDto>;
    dateValues?: null | Array<TariffGridDateValueDto>;
};

export type TariffGridStringValueDto = {
    id?: number;
    name?: null | string;
    value: string;
};

export type TariffGridTaxDto = {
    key?: null | string;
    name?: null | string;
    amount?: null | number;
};

export type TariffInfoDto = {
    infoId?: null | number;
    infoType?: null | string;
    content?: null | string;
};

export type TariffParametersDto = {
    customerTypes: Array<string>;
    tariffTypes: Array<string>;
    meterTypes?: null | Array<string>;
    cancellationPeriods: Array<string>;
};

export type TariffSurchargeDto = {
    surchargeId?: null | number;
    surchargeName?: null | string;
    surchargeType?: null | string;
    amountNet?: null | number;
    amountGross?: null | number;
};

export type UniversalInfoDetailDto = {
    rechercheTypeId?: number;
    salesChannelId?: null | number;
    tariffCode?: null | string;
    info?: null | string;
    validFrom?: null | string;
    validTo?: null | string;
    consumptionFrom?: null | number;
    consumptionTo?: null | number;
};

export type UniversalInfoGasRequestDto = {
    consumption?: null | number;
    referenceDate?: null | string;
    tariffCode?: null | string;
    tariffRootIds?: null | string;
    supplierIds?: null | string;
    salesChannelIds?: null | string;
    additionalInfoIds?: null | string;
};

export type UniversalInfoItemDto = {
    tariffId: number;
    tariffRootId: number;
    supplierId: number;
    brandId?: null | number;
    additionalInformation: Array<UniversalInfoDetailDto>;
};

export type UniversalInfoRequestDto = {
    consumptionHt?: null | number;
    consumptionLt?: null | number;
    referenceDate?: null | string;
    tariffCode?: null | string;
    tariffRootIds?: null | string;
    supplierIds?: null | string;
    salesChannelIds?: null | string;
    rechercheTypeIds?: null | string;
};

export type FetchNetworkChargeElectricityData = {
    body: NetworkChargeElectricityRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/network-charges/electricity/fetch';
};

export type FetchNetworkChargeElectricityResponses = {
    /**
     * OK
     */
    200: InquirySuccessDto;
};

export type FetchNetworkChargeElectricityResponse = FetchNetworkChargeElectricityResponses[keyof FetchNetworkChargeElectricityResponses];

export type GetParametersElectricityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/getag/network-charges/electricity/parameters';
};

export type GetParametersElectricityResponses = {
    /**
     * OK
     */
    200: NetworkChargeElectricityParametersDto;
};

export type GetParametersElectricityResponse = GetParametersElectricityResponses[keyof GetParametersElectricityResponses];

export type FetchNetworkChargeGasData = {
    body: NetworkChargeGasRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/network-charges/gas/fetch';
};

export type FetchNetworkChargeGasResponses = {
    /**
     * OK
     */
    200: InquirySuccessDto;
};

export type FetchNetworkChargeGasResponse = FetchNetworkChargeGasResponses[keyof FetchNetworkChargeGasResponses];

export type GetParametersGasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/getag/network-charges/gas/parameters';
};

export type GetParametersGasResponses = {
    /**
     * OK
     */
    200: NetworkChargeGasParametersDto;
};

export type GetParametersGasResponse = GetParametersGasResponses[keyof GetParametersGasResponses];

export type GetNetworkChargeResultsData = {
    body?: never;
    path: {
        workflowId: string;
    };
    query?: never;
    url: '/api/getag/network-charges/results/{workflowId}';
};

export type GetNetworkChargeResultsResponses = {
    /**
     * OK
     */
    200: Array<NetworkChargeResponseItemBaseDto>;
};

export type GetNetworkChargeResultsResponse = GetNetworkChargeResultsResponses[keyof GetNetworkChargeResultsResponses];

export type FetchElectricityTariffsData = {
    body: TariffElectricityRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/tariffs/electricity/fetch';
};

export type FetchElectricityTariffsResponses = {
    /**
     * OK
     */
    200: InquirySuccessDto;
};

export type FetchElectricityTariffsResponse = FetchElectricityTariffsResponses[keyof FetchElectricityTariffsResponses];

export type FetchElectricityParametersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/getag/tariffs/electricity/parameters';
};

export type FetchElectricityParametersResponses = {
    /**
     * OK
     */
    200: TariffParametersDto;
};

export type FetchElectricityParametersResponse = FetchElectricityParametersResponses[keyof FetchElectricityParametersResponses];

export type FetchGasTariffsData = {
    body: TariffGasRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/tariffs/gas/fetch';
};

export type FetchGasTariffsResponses = {
    /**
     * OK
     */
    200: InquirySuccessDto;
};

export type FetchGasTariffsResponse = FetchGasTariffsResponses[keyof FetchGasTariffsResponses];

export type FetchGasParametersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/getag/tariffs/gas/parameters';
};

export type FetchGasParametersResponses = {
    /**
     * OK
     */
    200: TariffParametersDto;
};

export type FetchGasParametersResponse = FetchGasParametersResponses[keyof FetchGasParametersResponses];

export type FetchTariffResultsData = {
    body?: never;
    path: {
        workflowId: string;
    };
    query?: never;
    url: '/api/getag/tariffs/results/{workflowId}';
};

export type FetchTariffResultsResponses = {
    /**
     * OK
     */
    200: Array<TariffElectricityResponseItemDto>;
};

export type FetchTariffResultsResponse = FetchTariffResultsResponses[keyof FetchTariffResultsResponses];

export type FetchSuppliersElectricityData = {
    body?: never;
    path?: never;
    query?: {
        ReferenceDate?: string;
        SupplierIds?: string;
        AssociationNumber?: string;
        SupplierName?: string;
        SupplierLocation?: string;
    };
    url: '/api/getag/supplier/electricity/fetch';
};

export type FetchSuppliersElectricityResponses = {
    /**
     * OK
     */
    200: Array<SupplierItemDto>;
};

export type FetchSuppliersElectricityResponse = FetchSuppliersElectricityResponses[keyof FetchSuppliersElectricityResponses];

export type FetchSupplierCardElectricityData = {
    body?: never;
    path: {
        supplierId: number;
    };
    query?: never;
    url: '/api/getag/supplier/electricity/{supplierId}/card';
};

export type FetchSupplierCardElectricityResponses = {
    /**
     * OK
     */
    200: SupplierCardItemDto;
};

export type FetchSupplierCardElectricityResponse = FetchSupplierCardElectricityResponses[keyof FetchSupplierCardElectricityResponses];

export type FetchSupplierVariantsElectricityData = {
    body?: never;
    path: {
        supplierId: number;
    };
    query?: {
        PostalCode?: string;
        City?: string;
        CustomerType?: number;
        ReferenceDate?: string;
        TariffType?: string;
        Consumption?: number;
        NetworkOperatorCode?: string;
        BasicSupplierCode?: string;
    };
    url: '/api/getag/supplier/electricity/{supplierId}/variants';
};

export type FetchSupplierVariantsElectricityResponses = {
    /**
     * OK
     */
    200: Array<SupplierVariantItemDto>;
};

export type FetchSupplierVariantsElectricityResponse = FetchSupplierVariantsElectricityResponses[keyof FetchSupplierVariantsElectricityResponses];

export type FetchUniversalInformationElectricityData = {
    body: UniversalInfoRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/supplier/electricity/universal-info';
};

export type FetchUniversalInformationElectricityResponses = {
    /**
     * OK
     */
    200: Array<UniversalInfoItemDto>;
};

export type FetchUniversalInformationElectricityResponse = FetchUniversalInformationElectricityResponses[keyof FetchUniversalInformationElectricityResponses];

export type FetchSuppliersGasData = {
    body?: never;
    path?: never;
    query?: {
        ReferenceDate?: string;
        SupplierIds?: string;
        AssociationNumber?: string;
        SupplierName?: string;
        SupplierLocation?: string;
    };
    url: '/api/getag/supplier/gas/fetch';
};

export type FetchSuppliersGasResponses = {
    /**
     * OK
     */
    200: Array<SupplierItemDto>;
};

export type FetchSuppliersGasResponse = FetchSuppliersGasResponses[keyof FetchSuppliersGasResponses];

export type FetchSupplierCardGasData = {
    body?: never;
    path: {
        supplierId: number;
    };
    query?: never;
    url: '/api/getag/supplier/gas/{supplierId}/card';
};

export type FetchSupplierCardGasResponses = {
    /**
     * OK
     */
    200: SupplierCardItemDto;
};

export type FetchSupplierCardGasResponse = FetchSupplierCardGasResponses[keyof FetchSupplierCardGasResponses];

export type FetchSupplierVariantsGasData = {
    body?: never;
    path: {
        supplierId: number;
    };
    query?: {
        PostalCode?: string;
        City?: string;
        CustomerType?: number;
        ReferenceDate?: string;
        TariffType?: string;
        Consumption?: number;
        NetworkOperatorCode?: string;
        BasicSupplierCode?: string;
    };
    url: '/api/getag/supplier/gas/{supplierId}/variants';
};

export type FetchSupplierVariantsGasResponses = {
    /**
     * OK
     */
    200: Array<SupplierVariantItemDto>;
};

export type FetchSupplierVariantsGasResponse = FetchSupplierVariantsGasResponses[keyof FetchSupplierVariantsGasResponses];

export type FetchUniversalInformationGasData = {
    body: UniversalInfoGasRequestDto;
    path?: never;
    query?: never;
    url: '/api/getag/supplier/gas/universal-info';
};

export type FetchUniversalInformationGasResponses = {
    /**
     * OK
     */
    200: Array<UniversalInfoItemDto>;
};

export type FetchUniversalInformationGasResponse = FetchUniversalInformationGasResponses[keyof FetchUniversalInformationGasResponses];
