// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAdditionalCostGroupElectricityDto = z.object({
    transformer: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    communicationDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    technicalControlDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    remoteReading: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalReadings: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalBillings: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    extendedAdditionalCosts: z.optional(z.union([
        z.null(),
        z.array(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    ]))
});

export const zAdditionalCostGroupGasDto = z.object({
    volumeConverter: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    communicationDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    technicalControlDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    remoteReading: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterDevice: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalReadings: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalBillings: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    extendedAdditionalCosts: z.optional(z.union([
        z.null(),
        z.array(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    ]))
});

export const zCalculationConfigurationDto = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    value: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zDiscountDto = z.object({
    discountType: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    discountKind: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    discountRate: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    discountValue: z.optional(z.union([
        z.null(),
        z.number()
    ]))
});

export const zInquiryFailureDto = z.object({
    errorCode: z.string(),
    errorMessage: z.string(),
    details: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    occurredAtUtc: z.optional(z.iso.datetime())
});

export const zInquiryStatus = z.enum([
    'pending',
    'success',
    'failed'
]);

export const zInquirySuccessDto = z.object({
    workflowId: z.string()
});

export const zMarketAreaLevyDto = z.object({
    value: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    marketAreaId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    marketAreaName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    marketAreaEic: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zNetworkChargeElectricityParametersDto = z.object({
    networkCodes: z.array(z.string()),
    voltageOrPressureLevels: z.array(z.string()),
    meterTypes: z.array(z.string()),
    customerGroups: z.array(z.string())
});

export const zNetworkChargeElectricityRequestItemDto = z.object({
    consumptionHighTariffKWh: z.number(),
    consumptionLowTariffKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    voltageLevelExtraction: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    voltageLevelMeasurement: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    feeType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    customerType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    lastConsumerGroup: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    quantitySurcharge: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    blindEnergyHighTariffKvarh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    blindEnergyLowTariffKvarh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    blindEnergyType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalCostGroup: z.optional(z.union([
        z.null(),
        zAdditionalCostGroupElectricityDto
    ])),
    postalCode: z.string(),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    municipalityKey: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    street: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    houseNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    referenceDate: z.iso.date(),
    powerKw: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    concessionType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    networkOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meteringPointOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meteringServiceProviderCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    regionId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    outputConfiguration: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    calculationConfigurations: z.optional(z.union([
        z.null(),
        z.array(zCalculationConfigurationDto)
    ]))
});

export const zNetworkChargeElectricityRequestDto = z.object({
    items: z.array(zNetworkChargeElectricityRequestItemDto)
});

export const zNetworkChargeGasParametersDto = z.object({
    voltageOrPressureLevels: z.array(z.string()),
    meterTypes: z.array(z.string()),
    customerGroups: z.array(z.string())
});

export const zNetworkChargeGasRequestItemDto = z.object({
    consumptionKWh: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    pressureLevel: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    loadType: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    meterSize: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingInterval: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    biogasShare: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    additionalCostGroup: z.optional(z.union([
        z.null(),
        zAdditionalCostGroupGasDto
    ])),
    postalCode: z.string(),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    municipalityKey: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    street: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    houseNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    referenceDate: z.iso.date(),
    powerKw: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    concessionType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    networkOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meteringPointOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meteringServiceProviderCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    regionId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    outputConfiguration: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    calculationConfigurations: z.optional(z.union([
        z.null(),
        z.array(zCalculationConfigurationDto)
    ]))
});

export const zNetworkChargeGasRequestDto = z.object({
    items: z.array(zNetworkChargeGasRequestItemDto)
});

export const zNetworkChargeSupplierInfoDto = z.object({
    supplierId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    supplierName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    marketRoleId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    associationNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    associationNumberShort: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ]))
});

export const zPriceDetailDto = z.object({
    id: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    value: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    referenceValue: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    quantity: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    quantityUnit: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    time: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    timeUnit: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    discountValue: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    quantityModel: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    timeFactor: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    billingInterval: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    dataProvision: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    discounts: z.optional(zDiscountDto)
});

export const zChargeDetailsDto = z.object({
    quantityModel: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    timeFactor: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    blindEnergyDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    basePriceDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    powerDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    moreAndLessQuantityDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    activeEnergyHighTariffDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    activeEnergyLowTariffDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    measurementDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    msbDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ])),
    billingDetails: z.optional(z.union([
        z.null(),
        z.array(zPriceDetailDto)
    ]))
});

export const zFlatCostDto = z.object({
    id: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    includedInTotalPrice: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    bdewArticles: z.optional(z.union([
        z.null(),
        z.array(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }))
    ])),
    details: z.optional(z.union([
        z.null(),
        zPriceDetailDto
    ]))
});

export const zNetworkChargeElectricityGridInfoDto = z.object({
    uniqueId: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    chargeTypeId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    loadType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    medium: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    chargeCategory: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    flatCosts: z.optional(z.union([
        z.null(),
        z.array(zFlatCostDto)
    ])),
    chargeDetails: z.optional(z.union([
        z.null(),
        zChargeDetailsDto
    ])),
    chargeId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    chargeRootId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    chargeName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    isPreliminary: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    regionId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    networkOperators: z.optional(z.union([
        z.null(),
        z.array(zNetworkChargeSupplierInfoDto)
    ])),
    basicSuppliers: z.optional(z.union([
        z.null(),
        z.array(zNetworkChargeSupplierInfoDto)
    ]))
});

export const zNetworkChargeElectricitySuccessItemDto = z.object({
    consumptionHighTariffKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    consumptionLowTariffKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceHighTariff: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceLowTariff: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    blindEnergyCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterPriceReadingTotal: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    remoteReadingCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeHighTariff: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeLowTariff: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeTariffCustomerCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeSpecialContractCustomerCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeWeakLoadCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    chpLevy: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    offshoreLevy: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    shutdownLevy: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    specialCustomerSurcharge: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    eegLevy: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    feeType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    gridInfos: z.optional(z.union([
        z.null(),
        z.array(zNetworkChargeElectricityGridInfoDto)
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    totalPrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerPrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterOperationCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    measurementAndReadingCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeTotal: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ]))
});

export const zNetworkChargeResponseItemBaseDtoNetworkChargeElectricityResponseItemDto = z.object({
    $type: z.optional(z.enum(['electricity'])),
    request: zNetworkChargeElectricityRequestItemDto,
    successResult: z.optional(z.union([
        z.null(),
        zNetworkChargeElectricitySuccessItemDto
    ])),
    workflowId: z.uuid(),
    status: zInquiryStatus,
    failureResult: z.optional(z.union([
        z.null(),
        zInquiryFailureDto
    ]))
});

export const zPriceDetailsDto = z.object({
    id: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    value: z.optional(z.number()),
    referenceValue: z.optional(z.number()),
    time: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    timeUnit: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    quantity: z.optional(z.number()),
    quantityUnit: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    discountValue: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    validFrom: z.optional(z.iso.datetime()),
    validTo: z.optional(z.iso.datetime()),
    discounts: z.optional(z.union([
        z.null(),
        z.array(zDiscountDto)
    ]))
});

export const zFlatCostTimeSliceDto = z.object({
    id: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    includedInTotalPrice: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    bdewArticles: z.optional(z.union([
        z.null(),
        z.array(z.string())
    ])),
    details: z.optional(z.union([
        z.null(),
        zPriceDetailsDto
    ]))
});

export const zNetworkChargeGasGridInfoDto = z.object({
    flatCostsTimeSlice: z.optional(z.union([
        z.null(),
        z.array(zFlatCostTimeSliceDto)
    ])),
    chargeId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    chargeRootId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    chargeName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    isPreliminary: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    regionId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    networkOperators: z.optional(z.union([
        z.null(),
        z.array(zNetworkChargeSupplierInfoDto)
    ])),
    basicSuppliers: z.optional(z.union([
        z.null(),
        z.array(zNetworkChargeSupplierInfoDto)
    ]))
});

export const zNetworkChargeGasSuccessItemDto = z.object({
    consumption: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    pressureLevel: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterSizeFrom: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterSizeTo: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingInterval: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    powerPriceType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    workPriceType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    basePriceConsumption: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePricePower: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    consumptionFix: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceFix: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    co2PriceNaturalGas: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    referenceCo2PriceNaturalGas: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerFix: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerTransferred: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    controlEnergyLevy: z.optional(z.union([
        z.null(),
        z.array(zMarketAreaLevyDto)
    ])),
    balancingLevy: z.optional(z.union([
        z.null(),
        z.array(zMarketAreaLevyDto)
    ])),
    gridInfo: z.optional(z.union([
        z.null(),
        zNetworkChargeGasGridInfoDto
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    totalPrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerPrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePrice: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterOperationCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    measurementAndReadingCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingCost: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeTotal: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ]))
});

export const zNetworkChargeResponseItemBaseDtoNetworkChargeGasResponseItemDto = z.object({
    $type: z.optional(z.enum(['gas'])),
    request: zNetworkChargeGasRequestItemDto,
    successResult: z.optional(z.union([
        z.null(),
        zNetworkChargeGasSuccessItemDto
    ])),
    workflowId: z.uuid(),
    status: zInquiryStatus,
    failureResult: z.optional(z.union([
        z.null(),
        zInquiryFailureDto
    ]))
});

export const zNetworkChargeResponseItemBaseDto = z.union([
    z.object({
        $type: z.optional(z.literal('electricity'))
    }).and(zNetworkChargeResponseItemBaseDtoNetworkChargeElectricityResponseItemDto),
    z.object({
        $type: z.optional(z.literal('gas'))
    }).and(zNetworkChargeResponseItemBaseDtoNetworkChargeGasResponseItemDto)
]);

export const zSupplierCardItemDto = z.object({
    companyName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    shortName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    street: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    houseNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    zipCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    city: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    country: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    phone: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    fax: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    website: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    email: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    poBoxZipCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    poBoxCity: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    poBox: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    associationNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    statusId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    remark: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zSupplierItemDto = z.object({
    supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    supplierName: z.string(),
    brandId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    brandName: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zSupplierVariantItemDto = z.object({
    supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    supplierName: z.string(),
    brandId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    brandName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    variantId: z.string(),
    tariffName: z.string(),
    isBasicSupplyTariff: z.boolean()
});

export const zTariffBonusDto = z.object({
    bonusId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    bonusName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    bonusType: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    amountNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    amountGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    condition: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    paymentMonth: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ]))
});

export const zTariffElectricityRequestItemDto = z.object({
    consumptionHighTariffKWh: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    consumptionLowTariffKWh: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    loadProfiles: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    smartMeterFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    postalCode: z.string(),
    city: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    networkOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    basicSupplierCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    gridAreaCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    customerType: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    tariffType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    referenceDate: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    pageSize: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    pageNumber: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    sorting: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    indicator: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    limitPerSupplier: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffsFromBasicSuppliers: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    basicSupplyTariffs: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffHandling: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    supplierIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    brandIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffCodes: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIdsMinFilter: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    certificateIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    salesChannelIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    regionalSupplierRadius: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    ecoFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    packageFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    fixPriceFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    prepaymentFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    portalGuideline: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    bonusFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    materialBonusFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    priceGuaranteeFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    depositFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    specialDeductionFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    existingCustomerTariffFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxContractDurationMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxRenewalMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxCancellationPeriodCode: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    minPriceGuaranteeMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonTariffId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonVariantId: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    comparisonGuideline: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonSupplierId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    ignoreLimitsUpToKWh: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    details: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    baiExtendedWhiteList: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    baiExtendedBlackList: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zTariffElectricityRequestDto = z.object({
    items: z.array(zTariffElectricityRequestItemDto)
});

export const zTariffElectricityStrommixDto = z.object({
    year: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    co2EmissionsGramPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    radioactiveWasteGramPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    nuclearPercent: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    renewableTotalPercent: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    fossilTotalPercent: z.optional(z.union([
        z.null(),
        z.number()
    ]))
});

export const zTariffGasRequestItemDto = z.object({
    consumptionKWh: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    powerKw: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    postalCode: z.string(),
    city: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    networkOperatorCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    basicSupplierCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    gridAreaCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    customerType: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    tariffType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    referenceDate: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    pageSize: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    pageNumber: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    sorting: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    indicator: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    limitPerSupplier: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffsFromBasicSuppliers: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    basicSupplyTariffs: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffHandling: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    supplierIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    brandIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffCodes: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIdsMinFilter: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    certificateIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    salesChannelIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    regionalSupplierRadius: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    ecoFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    packageFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    fixPriceFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    prepaymentFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    portalGuideline: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    bonusFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    materialBonusFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    priceGuaranteeFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    depositFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    specialDeductionFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    existingCustomerTariffFlag: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxContractDurationMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxRenewalMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    maxCancellationPeriodCode: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    minPriceGuaranteeMonths: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonTariffId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonVariantId: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    comparisonGuideline: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    comparisonSupplierId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    ignoreLimitsUpToKWh: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    details: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    baiExtendedWhiteList: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    baiExtendedBlackList: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zTariffGasRequestDto = z.object({
    items: z.array(zTariffGasRequestItemDto)
});

export const zTariffGridDateValueDto = z.object({
    id: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    value: z.iso.date()
});

export const zTariffGridDoubleValueDto = z.object({
    id: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    value: z.number()
});

export const zTariffGridIntValueDto = z.object({
    id: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    value: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zTariffGridStringValueDto = z.object({
    id: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    value: z.string()
});

export const zTariffGridMiscInfoDto = z.object({
    intValues: z.optional(z.union([
        z.null(),
        z.array(zTariffGridIntValueDto)
    ])),
    doubleValues: z.optional(z.union([
        z.null(),
        z.array(zTariffGridDoubleValueDto)
    ])),
    stringValues: z.optional(z.union([
        z.null(),
        z.array(zTariffGridStringValueDto)
    ])),
    dateValues: z.optional(z.union([
        z.null(),
        z.array(zTariffGridDateValueDto)
    ]))
});

export const zTariffGridLevyDto = z.object({
    key: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    amount: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    miscellaneousInfo: z.optional(z.union([
        z.null(),
        z.array(zTariffGridMiscInfoDto)
    ]))
});

export const zTariffGridTaxDto = z.object({
    key: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    amount: z.optional(z.union([
        z.null(),
        z.number()
    ]))
});

export const zTariffGridInfoBaseDtoTariffElectricityGridInfoDto = z.object({
    $type: z.optional(z.enum(['electricity'])),
    workPriceHighTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceLowTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeHighTariffCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeLowTariffCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    feeType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    voltageLevelExtraction: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    voltageLevelMeasurement: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    totalChargeNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerPriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meteringAndReadingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meteringEquipmentFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterPriceAndReadingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    levies: z.optional(z.union([
        z.null(),
        z.array(zTariffGridLevyDto)
    ])),
    taxes: z.optional(z.union([
        z.null(),
        z.array(zTariffGridTaxDto)
    ])),
    miscellaneousInfo: z.optional(z.union([
        z.null(),
        z.array(zTariffGridMiscInfoDto)
    ]))
});

export const zTariffGridInfoBaseDtoTariffGasGridInfoDto = z.object({
    $type: z.optional(z.enum(['gas'])),
    workPriceNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    concessionFeeCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    pressureLevel: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterType: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    meterSizeFrom: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterSizeTo: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    totalChargeNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    powerPriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    billingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meteringAndReadingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meteringEquipmentFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    meterPriceAndReadingFee: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    levies: z.optional(z.union([
        z.null(),
        z.array(zTariffGridLevyDto)
    ])),
    taxes: z.optional(z.union([
        z.null(),
        z.array(zTariffGridTaxDto)
    ])),
    miscellaneousInfo: z.optional(z.union([
        z.null(),
        z.array(zTariffGridMiscInfoDto)
    ]))
});

export const zTariffGridInfoBaseDto = z.union([
    z.object({
        $type: z.optional(z.literal('electricity'))
    }).and(zTariffGridInfoBaseDtoTariffElectricityGridInfoDto),
    z.object({
        $type: z.optional(z.literal('gas'))
    }).and(zTariffGridInfoBaseDtoTariffGasGridInfoDto)
]);

export const zTariffInfoDto = z.object({
    infoId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    infoType: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    content: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zTariffParametersDto = z.object({
    customerTypes: z.array(z.string()),
    tariffTypes: z.array(z.string()),
    meterTypes: z.optional(z.union([
        z.null(),
        z.array(z.string())
    ])),
    cancellationPeriods: z.array(z.string())
});

export const zTariffSurchargeDto = z.object({
    surchargeId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    surchargeName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    surchargeType: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    amountNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    amountGross: z.optional(z.union([
        z.null(),
        z.number()
    ]))
});

export const zTariffElectricitySuccessItemDto = z.object({
    workPriceHighTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceHighTariffGrossCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceLowTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceLowTariffGrossCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyHighTariffNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyHighTariffGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyLowTariffNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyLowTariffGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyHighTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyHighTariffGrossCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyLowTariffNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceEnergyLowTariffGrossCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    isEcoTariff: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    strommix: z.optional(z.union([
        z.null(),
        zTariffElectricityStrommixDto
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffVariantId: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffInfo: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    supplierId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    supplierName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    brandId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    displayFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    displayTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    totalPriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    totalPriceGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    totalPriceWithoutBonusesNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    totalPriceWithoutBonusesGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    workPriceGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceEnergyNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    basePriceEnergyGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    savingsNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    savingsGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    isPrepaymentTariff: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    isPackageTariff: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    isBasicSupplyTariff: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    isComparisonTariff: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    contractDuration: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    contractDurationId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    contractExtension: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    contractExtensionId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    cancellationPeriod: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    cancellationPeriodId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    packageAmountKWh: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    packagePriceNet: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    packagePriceGross: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    packageOverConsumptionPriceNetCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    packageOverConsumptionPriceGrossCtPerKWh: z.optional(z.union([
        z.null(),
        z.number()
    ])),
    gridInfo: z.optional(z.union([
        z.null(),
        zTariffGridInfoBaseDto
    ])),
    bonuses: z.optional(z.union([
        z.null(),
        z.array(zTariffBonusDto)
    ])),
    surcharges: z.optional(z.union([
        z.null(),
        z.array(zTariffSurchargeDto)
    ])),
    additionalInfo: z.optional(z.union([
        z.null(),
        z.array(zTariffInfoDto)
    ]))
});

export const zTariffElectricitySuccessResultDto = z.object({
    tariffs: z.optional(z.union([
        z.null(),
        z.array(zTariffElectricitySuccessItemDto)
    ])),
    totalResultCount: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    pageResultCount: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    postalCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    city: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    uid: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zTariffElectricityResponseItemDto = z.object({
    request: zTariffElectricityRequestItemDto,
    successResult: z.optional(z.union([
        z.null(),
        zTariffElectricitySuccessResultDto
    ])),
    workflowId: z.uuid(),
    status: zInquiryStatus,
    failureResult: z.optional(z.union([
        z.null(),
        zInquiryFailureDto
    ]))
});

export const zUniversalInfoDetailDto = z.object({
    rechercheTypeId: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    salesChannelId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    tariffCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    info: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    consumptionFrom: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    consumptionTo: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ]))
});

export const zUniversalInfoGasRequestDto = z.object({
    consumption: z.optional(z.union([
        z.null(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])),
    referenceDate: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    tariffCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    supplierIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    salesChannelIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    additionalInfoIds: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zUniversalInfoItemDto = z.object({
    tariffId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    tariffRootId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    brandId: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    additionalInformation: z.array(zUniversalInfoDetailDto)
});

export const zUniversalInfoRequestDto = z.object({
    consumptionHt: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    consumptionLt: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    referenceDate: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    tariffCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    tariffRootIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    supplierIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    salesChannelIds: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    rechercheTypeIds: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zFetchNetworkChargeElectricityData = z.object({
    body: zNetworkChargeElectricityRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchNetworkChargeElectricityResponse = zInquirySuccessDto;

export const zGetParametersElectricityData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetParametersElectricityResponse = zNetworkChargeElectricityParametersDto;

export const zFetchNetworkChargeGasData = z.object({
    body: zNetworkChargeGasRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchNetworkChargeGasResponse = zInquirySuccessDto;

export const zGetParametersGasData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetParametersGasResponse = zNetworkChargeGasParametersDto;

export const zGetNetworkChargeResultsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        workflowId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetNetworkChargeResultsResponse = z.array(zNetworkChargeResponseItemBaseDto);

export const zFetchElectricityTariffsData = z.object({
    body: zTariffElectricityRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchElectricityTariffsResponse = zInquirySuccessDto;

export const zFetchElectricityParametersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchElectricityParametersResponse = zTariffParametersDto;

export const zFetchGasTariffsData = z.object({
    body: zTariffGasRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchGasTariffsResponse = zInquirySuccessDto;

export const zFetchGasParametersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchGasParametersResponse = zTariffParametersDto;

export const zFetchTariffResultsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        workflowId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchTariffResultsResponse = z.array(zTariffElectricityResponseItemDto);

export const zFetchSuppliersElectricityData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ReferenceDate: z.optional(z.iso.datetime()),
        SupplierIds: z.optional(z.string()),
        AssociationNumber: z.optional(z.string()),
        SupplierName: z.optional(z.string()),
        SupplierLocation: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zFetchSuppliersElectricityResponse = z.array(zSupplierItemDto);

export const zFetchSupplierCardElectricityData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchSupplierCardElectricityResponse = zSupplierCardItemDto;

export const zFetchSupplierVariantsElectricityData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        PostalCode: z.optional(z.string()),
        City: z.optional(z.string()),
        CustomerType: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        ReferenceDate: z.optional(z.iso.datetime()),
        TariffType: z.optional(z.string()),
        Consumption: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        NetworkOperatorCode: z.optional(z.string()),
        BasicSupplierCode: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zFetchSupplierVariantsElectricityResponse = z.array(zSupplierVariantItemDto);

export const zFetchUniversalInformationElectricityData = z.object({
    body: zUniversalInfoRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchUniversalInformationElectricityResponse = z.array(zUniversalInfoItemDto);

export const zFetchSuppliersGasData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        ReferenceDate: z.optional(z.iso.datetime()),
        SupplierIds: z.optional(z.string()),
        AssociationNumber: z.optional(z.string()),
        SupplierName: z.optional(z.string()),
        SupplierLocation: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zFetchSuppliersGasResponse = z.array(zSupplierItemDto);

export const zFetchSupplierCardGasData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchSupplierCardGasResponse = zSupplierCardItemDto;

export const zFetchSupplierVariantsGasData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        supplierId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.object({
        PostalCode: z.optional(z.string()),
        City: z.optional(z.string()),
        CustomerType: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        ReferenceDate: z.optional(z.iso.datetime()),
        TariffType: z.optional(z.string()),
        Consumption: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
        NetworkOperatorCode: z.optional(z.string()),
        BasicSupplierCode: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zFetchSupplierVariantsGasResponse = z.array(zSupplierVariantItemDto);

export const zFetchUniversalInformationGasData = z.object({
    body: zUniversalInfoGasRequestDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zFetchUniversalInformationGasResponse = z.array(zUniversalInfoItemDto);
