// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ApiCatsData,
  ApiCatsResponses,
  ApiCountData,
  ApiCountResponses,
  ApiTagsData,
  ApiTagsResponses,
  CatGetData,
  CatGetErrors,
  CatGetResponses,
  CatGetTextData,
  CatGetTextErrors,
  CatGetTextResponses,
  CatRandomData,
  CatRandomResponses,
  CatRandomTagData,
  CatRandomTagResponses,
  CatRandomTagTextData,
  CatRandomTagTextResponses,
  CatRandomTextData,
  CatRandomTextResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Will return all cats
 */
export const apiCats = <ThrowOnError extends boolean = false>(options?: Options<ApiCatsData, ThrowOnError>) =>
  (options?.client ?? client).get<ApiCatsResponses, unknown, ThrowOnError>({ url: '/api/cats', ...options });

/**
 * Count how many cat
 */
export const apiCount = <ThrowOnError extends boolean = false>(options?: Options<ApiCountData, ThrowOnError>) =>
  (options?.client ?? client).get<ApiCountResponses, unknown, ThrowOnError>({ url: '/api/count', ...options });

/**
 * Will return all tags
 */
export const apiTags = <ThrowOnError extends boolean = false>(options?: Options<ApiTagsData, ThrowOnError>) =>
  (options?.client ?? client).get<ApiTagsResponses, unknown, ThrowOnError>({ url: '/api/tags', ...options });

/**
 * Get a random cat
 */
export const catRandom = <ThrowOnError extends boolean = false>(options?: Options<CatRandomData, ThrowOnError>) =>
  (options?.client ?? client).get<CatRandomResponses, unknown, ThrowOnError>({ url: '/cat', ...options });

/**
 * Get random cat saying text
 */
export const catRandomText = <ThrowOnError extends boolean = false>(
  options: Options<CatRandomTextData, ThrowOnError>,
) =>
  (options.client ?? client).get<CatRandomTextResponses, unknown, ThrowOnError>({
    url: '/cat/says/{text}',
    ...options,
  });

/**
 * Get cat by id
 */
export const catGet = <ThrowOnError extends boolean = false>(options: Options<CatGetData, ThrowOnError>) =>
  (options.client ?? client).get<CatGetResponses, CatGetErrors, ThrowOnError>({ url: '/cat/{id}', ...options });

/**
 * Get cat by id saying text
 */
export const catGetText = <ThrowOnError extends boolean = false>(options: Options<CatGetTextData, ThrowOnError>) =>
  (options.client ?? client).get<CatGetTextResponses, CatGetTextErrors, ThrowOnError>({
    url: '/cat/{id}/says/{text}',
    ...options,
  });

/**
 * Get random cat by tag
 */
export const catRandomTag = <ThrowOnError extends boolean = false>(options: Options<CatRandomTagData, ThrowOnError>) =>
  (options.client ?? client).get<CatRandomTagResponses, unknown, ThrowOnError>({ url: '/cat/{tag}', ...options });

/**
 * Get random cat by tag saying text
 */
export const catRandomTagText = <ThrowOnError extends boolean = false>(
  options: Options<CatRandomTagTextData, ThrowOnError>,
) =>
  (options.client ?? client).get<CatRandomTagTextResponses, unknown, ThrowOnError>({
    url: '/cat/{tag}/says/{text}',
    ...options,
  });
