// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://cataas.com' | (string & {});
};

export type Cat = {
  id: string;
  tags: Array<string>;
  mimetype: string;
  createdAt: string;
};

export type ApiCatsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    skip?: number;
    tags?: string;
  };
  url: '/api/cats';
};

export type ApiCatsResponses = {
  /**
   * List of cats
   */
  200: Array<Cat>;
};

export type ApiCatsResponse = ApiCatsResponses[keyof ApiCatsResponses];

export type ApiCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/count';
};

export type ApiCountResponses = {
  /**
   * List of tags
   */
  200: {
    count?: number;
  };
};

export type ApiCountResponse = ApiCountResponses[keyof ApiCountResponses];

export type ApiTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/tags';
};

export type ApiTagsResponses = {
  /**
   * List of tags
   */
  200: Array<string>;
};

export type ApiTagsResponse = ApiTagsResponses[keyof ApiTagsResponses];

export type CatRandomData = {
  body?: never;
  path?: never;
  query?: {
    type?: 'square' | 'medium' | 'small' | 'xsmall';
    filter?: 'mono' | 'negate' | 'custom';
    fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside';
    position?:
      | 'top'
      | 'right top'
      | 'right'
      | 'right bottom'
      | 'bottom'
      | 'left bottom'
      | 'left'
      | 'left top'
      | 'center';
    width?: number;
    height?: number;
    blur?: number;
    /**
     * With custom filter, define red value between 0 and 255
     */
    r?: number;
    /**
     * With custom filter, define green value between 0 and 255
     */
    g?: number;
    /**
     * With custom filter, define blue value between 0 and 255
     */
    b?: number;
    /**
     * With custom filter, define brightness
     */
    brightness?: number;
    /**
     * With custom filter, define saturation
     */
    saturation?: number;
    /**
     * With custom filter, define hue
     */
    hue?: number;
    /**
     * With custom filter, define lightness
     */
    lightness?: number;
    html?: boolean;
    json?: boolean;
  };
  url: '/cat';
};

export type CatRandomResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatRandomResponse = CatRandomResponses[keyof CatRandomResponses];

export type CatRandomTextData = {
  body?: never;
  path: {
    text: string;
  };
  query?: {
    type?: 'square' | 'medium' | 'small' | 'xsmall';
    filter?: 'mono' | 'negate' | 'custom';
    fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside';
    position?:
      | 'top'
      | 'right top'
      | 'right'
      | 'right bottom'
      | 'bottom'
      | 'left bottom'
      | 'left'
      | 'left top'
      | 'center';
    width?: number;
    height?: number;
    blur?: number;
    /**
     * With custom filter, define red value between 0 and 255
     */
    r?: number;
    /**
     * With custom filter, define green value between 0 and 255
     */
    g?: number;
    /**
     * With custom filter, define blue value between 0 and 255
     */
    b?: number;
    /**
     * With custom filter, define brightness
     */
    brightness?: number;
    /**
     * With custom filter, define saturation
     */
    saturation?: number;
    /**
     * With custom filter, define hue
     */
    hue?: number;
    /**
     * With custom filter, define lightness
     */
    lightness?: number;
    html?: boolean;
    json?: boolean;
    font?:
      | 'Andale Mono'
      | 'Impact'
      | 'Arial'
      | 'Arial Black'
      | 'Comic Sans MS'
      | 'Courier New'
      | 'Georgia'
      | 'Times New Roman'
      | 'Verdana'
      | 'Webdings';
    fontSize?: number;
    fontColor?: string;
    fontBackground?: string;
  };
  url: '/cat/says/{text}';
};

export type CatRandomTextResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatRandomTextResponse = CatRandomTextResponses[keyof CatRandomTextResponses];

export type CatGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/cat/{id}';
};

export type CatGetErrors = {
  /**
   * Cat not found
   */
  404: unknown;
};

export type CatGetResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatGetResponse = CatGetResponses[keyof CatGetResponses];

export type CatGetTextData = {
  body?: never;
  path: {
    id: string;
    text: string;
  };
  query?: {
    type?: 'square' | 'medium' | 'small' | 'xsmall';
    filter?: 'mono' | 'negate' | 'custom';
    fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside';
    position?:
      | 'top'
      | 'right top'
      | 'right'
      | 'right bottom'
      | 'bottom'
      | 'left bottom'
      | 'left'
      | 'left top'
      | 'center';
    width?: number;
    height?: number;
    blur?: number;
    /**
     * With custom filter, define red value between 0 and 255
     */
    r?: number;
    /**
     * With custom filter, define green value between 0 and 255
     */
    g?: number;
    /**
     * With custom filter, define blue value between 0 and 255
     */
    b?: number;
    /**
     * With custom filter, define brightness
     */
    brightness?: number;
    /**
     * With custom filter, define saturation
     */
    saturation?: number;
    /**
     * With custom filter, define hue
     */
    hue?: number;
    /**
     * With custom filter, define lightness
     */
    lightness?: number;
    html?: boolean;
    json?: boolean;
    font?:
      | 'Andale Mono'
      | 'Impact'
      | 'Arial'
      | 'Arial Black'
      | 'Comic Sans MS'
      | 'Courier New'
      | 'Georgia'
      | 'Times New Roman'
      | 'Verdana'
      | 'Webdings';
    fontSize?: number;
    fontColor?: string;
    fontBackground?: string;
  };
  url: '/cat/{id}/says/{text}';
};

export type CatGetTextErrors = {
  /**
   * Cat not found
   */
  404: unknown;
};

export type CatGetTextResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatGetTextResponse = CatGetTextResponses[keyof CatGetTextResponses];

export type CatRandomTagData = {
  body?: never;
  path: {
    tag: string;
  };
  query?: {
    type?: 'square' | 'medium' | 'small' | 'xsmall';
    filter?: 'mono' | 'negate' | 'custom';
    fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside';
    position?:
      | 'top'
      | 'right top'
      | 'right'
      | 'right bottom'
      | 'bottom'
      | 'left bottom'
      | 'left'
      | 'left top'
      | 'center';
    width?: number;
    height?: number;
    blur?: number;
    /**
     * With custom filter, define red value between 0 and 255
     */
    r?: number;
    /**
     * With custom filter, define green value between 0 and 255
     */
    g?: number;
    /**
     * With custom filter, define blue value between 0 and 255
     */
    b?: number;
    /**
     * With custom filter, define brightness
     */
    brightness?: number;
    /**
     * With custom filter, define saturation
     */
    saturation?: number;
    /**
     * With custom filter, define hue
     */
    hue?: number;
    /**
     * With custom filter, define lightness
     */
    lightness?: number;
    html?: boolean;
    json?: boolean;
  };
  url: '/cat/{tag}';
};

export type CatRandomTagResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatRandomTagResponse = CatRandomTagResponses[keyof CatRandomTagResponses];

export type CatRandomTagTextData = {
  body?: never;
  path: {
    tag: string;
    text: string;
  };
  query?: {
    type?: 'square' | 'medium' | 'small' | 'xsmall';
    filter?: 'mono' | 'negate' | 'custom';
    fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside';
    position?:
      | 'top'
      | 'right top'
      | 'right'
      | 'right bottom'
      | 'bottom'
      | 'left bottom'
      | 'left'
      | 'left top'
      | 'center';
    width?: number;
    height?: number;
    blur?: number;
    /**
     * With custom filter, define red value between 0 and 255
     */
    r?: number;
    /**
     * With custom filter, define green value between 0 and 255
     */
    g?: number;
    /**
     * With custom filter, define blue value between 0 and 255
     */
    b?: number;
    /**
     * With custom filter, define brightness
     */
    brightness?: number;
    /**
     * With custom filter, define saturation
     */
    saturation?: number;
    /**
     * With custom filter, define hue
     */
    hue?: number;
    /**
     * With custom filter, define lightness
     */
    lightness?: number;
    html?: boolean;
    json?: boolean;
    font?:
      | 'Andale Mono'
      | 'Impact'
      | 'Arial'
      | 'Arial Black'
      | 'Comic Sans MS'
      | 'Courier New'
      | 'Georgia'
      | 'Times New Roman'
      | 'Verdana'
      | 'Webdings';
    fontSize?: number;
    fontColor?: string;
    fontBackground?: string;
  };
  url: '/cat/{tag}/says/{text}';
};

export type CatRandomTagTextResponses = {
  /**
   * Cat returned
   */
  200: Cat;
};

export type CatRandomTagTextResponse = CatRandomTagTextResponses[keyof CatRandomTagTextResponses];
