// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCat = z.object({
  id: z.string(),
  tags: z.array(z.string()),
  mimetype: z.string(),
  createdAt: z.string(),
});

export const zApiCatsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.number()).default(10),
      skip: z.optional(z.number()).default(0),
      tags: z.optional(z.string()),
    }),
  ),
});

/**
 * List of cats
 */
export const zApiCatsResponse = z.array(zCat);

export const zApiCountData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * List of tags
 */
export const zApiCountResponse = z.object({
  count: z.optional(z.number()),
});

export const zApiTagsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * List of tags
 */
export const zApiTagsResponse = z.array(z.string());

export const zCatRandomData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['square', 'medium', 'small', 'xsmall'])),
      filter: z.optional(z.enum(['mono', 'negate', 'custom'])),
      fit: z.optional(z.enum(['cover', 'contain', 'fill', 'inside', 'outside'])),
      position: z.optional(
        z.enum(['top', 'right top', 'right', 'right bottom', 'bottom', 'left bottom', 'left', 'left top', 'center']),
      ),
      width: z.optional(z.number()),
      height: z.optional(z.number()),
      blur: z.optional(z.number()),
      r: z.optional(z.number()),
      g: z.optional(z.number()),
      b: z.optional(z.number()),
      brightness: z.optional(z.number()),
      saturation: z.optional(z.number()),
      hue: z.optional(z.number()),
      lightness: z.optional(z.number()),
      html: z.optional(z.boolean()),
      json: z.optional(z.boolean()),
    }),
  ),
});

/**
 * Cat returned
 */
export const zCatRandomResponse = zCat;

export const zCatRandomTextData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    text: z.string(),
  }),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['square', 'medium', 'small', 'xsmall'])),
      filter: z.optional(z.enum(['mono', 'negate', 'custom'])),
      fit: z.optional(z.enum(['cover', 'contain', 'fill', 'inside', 'outside'])),
      position: z.optional(
        z.enum(['top', 'right top', 'right', 'right bottom', 'bottom', 'left bottom', 'left', 'left top', 'center']),
      ),
      width: z.optional(z.number()),
      height: z.optional(z.number()),
      blur: z.optional(z.number()),
      r: z.optional(z.number()),
      g: z.optional(z.number()),
      b: z.optional(z.number()),
      brightness: z.optional(z.number()),
      saturation: z.optional(z.number()),
      hue: z.optional(z.number()),
      lightness: z.optional(z.number()),
      html: z.optional(z.boolean()),
      json: z.optional(z.boolean()),
      font: z.optional(
        z.enum([
          'Andale Mono',
          'Impact',
          'Arial',
          'Arial Black',
          'Comic Sans MS',
          'Courier New',
          'Georgia',
          'Times New Roman',
          'Verdana',
          'Webdings',
        ]),
      ),
      fontSize: z.optional(z.number()).default(50),
      fontColor: z.optional(z.string()).default('#fff'),
      fontBackground: z.optional(z.string()).default('none'),
    }),
  ),
});

/**
 * Cat returned
 */
export const zCatRandomTextResponse = zCat;

export const zCatGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Cat returned
 */
export const zCatGetResponse = zCat;

export const zCatGetTextData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.string(),
    text: z.string(),
  }),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['square', 'medium', 'small', 'xsmall'])),
      filter: z.optional(z.enum(['mono', 'negate', 'custom'])),
      fit: z.optional(z.enum(['cover', 'contain', 'fill', 'inside', 'outside'])),
      position: z.optional(
        z.enum(['top', 'right top', 'right', 'right bottom', 'bottom', 'left bottom', 'left', 'left top', 'center']),
      ),
      width: z.optional(z.number()),
      height: z.optional(z.number()),
      blur: z.optional(z.number()),
      r: z.optional(z.number()),
      g: z.optional(z.number()),
      b: z.optional(z.number()),
      brightness: z.optional(z.number()),
      saturation: z.optional(z.number()),
      hue: z.optional(z.number()),
      lightness: z.optional(z.number()),
      html: z.optional(z.boolean()),
      json: z.optional(z.boolean()),
      font: z.optional(
        z.enum([
          'Andale Mono',
          'Impact',
          'Arial',
          'Arial Black',
          'Comic Sans MS',
          'Courier New',
          'Georgia',
          'Times New Roman',
          'Verdana',
          'Webdings',
        ]),
      ),
      fontSize: z.optional(z.number()).default(50),
      fontColor: z.optional(z.string()).default('#fff'),
      fontBackground: z.optional(z.string()).default('none'),
    }),
  ),
});

/**
 * Cat returned
 */
export const zCatGetTextResponse = zCat;

export const zCatRandomTagData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tag: z.string(),
  }),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['square', 'medium', 'small', 'xsmall'])),
      filter: z.optional(z.enum(['mono', 'negate', 'custom'])),
      fit: z.optional(z.enum(['cover', 'contain', 'fill', 'inside', 'outside'])),
      position: z.optional(
        z.enum(['top', 'right top', 'right', 'right bottom', 'bottom', 'left bottom', 'left', 'left top', 'center']),
      ),
      width: z.optional(z.number()),
      height: z.optional(z.number()),
      blur: z.optional(z.number()),
      r: z.optional(z.number()),
      g: z.optional(z.number()),
      b: z.optional(z.number()),
      brightness: z.optional(z.number()),
      saturation: z.optional(z.number()),
      hue: z.optional(z.number()),
      lightness: z.optional(z.number()),
      html: z.optional(z.boolean()),
      json: z.optional(z.boolean()),
    }),
  ),
});

/**
 * Cat returned
 */
export const zCatRandomTagResponse = zCat;

export const zCatRandomTagTextData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    tag: z.string(),
    text: z.string(),
  }),
  query: z.optional(
    z.object({
      type: z.optional(z.enum(['square', 'medium', 'small', 'xsmall'])),
      filter: z.optional(z.enum(['mono', 'negate', 'custom'])),
      fit: z.optional(z.enum(['cover', 'contain', 'fill', 'inside', 'outside'])),
      position: z.optional(
        z.enum(['top', 'right top', 'right', 'right bottom', 'bottom', 'left bottom', 'left', 'left top', 'center']),
      ),
      width: z.optional(z.number()),
      height: z.optional(z.number()),
      blur: z.optional(z.number()),
      r: z.optional(z.number()),
      g: z.optional(z.number()),
      b: z.optional(z.number()),
      brightness: z.optional(z.number()),
      saturation: z.optional(z.number()),
      hue: z.optional(z.number()),
      lightness: z.optional(z.number()),
      html: z.optional(z.boolean()),
      json: z.optional(z.boolean()),
      font: z.optional(
        z.enum([
          'Andale Mono',
          'Impact',
          'Arial',
          'Arial Black',
          'Comic Sans MS',
          'Courier New',
          'Georgia',
          'Times New Roman',
          'Verdana',
          'Webdings',
        ]),
      ),
      fontSize: z.optional(z.number()).default(50),
      fontColor: z.optional(z.string()).default('#fff'),
      fontBackground: z.optional(z.string()).default('none'),
    }),
  ),
});

/**
 * Cat returned
 */
export const zCatRandomTagTextResponse = zCat;
