// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { fromExcel, getFiles, type Options } from '../sdk.gen';
import type { FromExcelData, GetFilesData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getFilesQueryKey = (options?: Options<GetFilesData>) => createQueryKey('getFiles', options, ['Import']);

export const getFilesQuery = defineQueryOptions((options?: Options<GetFilesData>) => ({
    key: getFilesQueryKey(options),
    query: async (context) => {
        const { data } = await getFiles({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fromExcelMutation = (options?: Partial<Options<FromExcelData>>): UseMutationOptions<unknown, Options<FromExcelData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fromExcel({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
