// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import {
  apiCats,
  apiCount,
  apiTags,
  catGet,
  catGetText,
  catRandom,
  catRandomTag,
  catRandomTagText,
  catRandomText,
  type Options,
} from '../sdk.gen';
import type {
  ApiCatsData,
  ApiCountData,
  ApiTagsData,
  CatGetData,
  CatGetTextData,
  CatRandomData,
  CatRandomTagData,
  CatRandomTagTextData,
  CatRandomTextData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const apiCatsQueryKey = (options?: Options<ApiCatsData>) => createQueryKey('apiCats', options, ['API']);

/**
 * Will return all cats
 */
export const apiCatsQuery = defineQueryOptions((options?: Options<ApiCatsData>) => ({
  key: apiCatsQueryKey(options),
  query: async (context) => {
    const { data } = await apiCats({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const apiCountQueryKey = (options?: Options<ApiCountData>) => createQueryKey('apiCount', options, ['API']);

/**
 * Count how many cat
 */
export const apiCountQuery = defineQueryOptions((options?: Options<ApiCountData>) => ({
  key: apiCountQueryKey(options),
  query: async (context) => {
    const { data } = await apiCount({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const apiTagsQueryKey = (options?: Options<ApiTagsData>) => createQueryKey('apiTags', options, ['API']);

/**
 * Will return all tags
 */
export const apiTagsQuery = defineQueryOptions((options?: Options<ApiTagsData>) => ({
  key: apiTagsQueryKey(options),
  query: async (context) => {
    const { data } = await apiTags({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catRandomQueryKey = (options?: Options<CatRandomData>) => createQueryKey('catRandom', options, ['Cats']);

/**
 * Get a random cat
 */
export const catRandomQuery = defineQueryOptions((options?: Options<CatRandomData>) => ({
  key: catRandomQueryKey(options),
  query: async (context) => {
    const { data } = await catRandom({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catRandomTextQueryKey = (options: Options<CatRandomTextData>) =>
  createQueryKey('catRandomText', options, ['Cats']);

/**
 * Get random cat saying text
 */
export const catRandomTextQuery = defineQueryOptions((options: Options<CatRandomTextData>) => ({
  key: catRandomTextQueryKey(options),
  query: async (context) => {
    const { data } = await catRandomText({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catGetQueryKey = (options: Options<CatGetData>) => createQueryKey('catGet', options, ['Cats']);

/**
 * Get cat by id
 */
export const catGetQuery = defineQueryOptions((options: Options<CatGetData>) => ({
  key: catGetQueryKey(options),
  query: async (context) => {
    const { data } = await catGet({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catGetTextQueryKey = (options: Options<CatGetTextData>) => createQueryKey('catGetText', options, ['Cats']);

/**
 * Get cat by id saying text
 */
export const catGetTextQuery = defineQueryOptions((options: Options<CatGetTextData>) => ({
  key: catGetTextQueryKey(options),
  query: async (context) => {
    const { data } = await catGetText({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catRandomTagQueryKey = (options: Options<CatRandomTagData>) =>
  createQueryKey('catRandomTag', options, ['Cats']);

/**
 * Get random cat by tag
 */
export const catRandomTagQuery = defineQueryOptions((options: Options<CatRandomTagData>) => ({
  key: catRandomTagQueryKey(options),
  query: async (context) => {
    const { data } = await catRandomTag({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const catRandomTagTextQueryKey = (options: Options<CatRandomTagTextData>) =>
  createQueryKey('catRandomTagText', options, ['Cats']);

/**
 * Get random cat by tag saying text
 */
export const catRandomTagTextQuery = defineQueryOptions((options: Options<CatRandomTagTextData>) => ({
  key: catRandomTagTextQueryKey(options),
  query: async (context) => {
    const { data } = await catRandomTagText({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));
