// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Address = {
    id: string;
    street?: null | string;
    houseNumber?: null | string;
    addendum?: null | string;
    postalCode?: null | string;
    city?: null | string;
    country?: null | string;
    coordinates?: null | GeoCoordinates;
};

export type AggregatedConsumption = {
    quantity: number;
    unit: ConsumptionUnit;
    start: string;
    end: string;
};

export type BenefitRecipient = {
    id: string;
    name: string;
    legalForm?: null | LegalForm;
    address: Address;
    contacts?: Array<Contact>;
};

export type Building = {
    id: string;
    name: string;
    assetNumber: string;
    address: Address;
};

export type Changelog = {
    source: string;
    sourceIdentifier: string;
    type: ChangelogType;
    timestamp: string;
    user: null | string;
};

export type ChangelogType = 'created' | 'updated';

export type Consumption = {
    quantity?: number;
    unit?: ConsumptionUnit;
    source?: ConsumptionSource;
    category?: ConsumptionCategory;
    start?: string;
    end?: string;
    meterId: string;
    meterNumber?: null | string;
    meterType?: MeterType;
    meterProduct?: MeterProduct;
    supplier?: null | Supplier;
    deliveryPointId: string;
    address: Address;
};

export type ConsumptionCategory = 'consumption' | 'forecast';

export type ConsumptionPerYear = {
    year?: number;
    consumption?: number;
    unit?: ConsumptionUnit;
};

export type ConsumptionSource = 'invoice' | 'measurement' | 'wave' | 'customerDocument' | 'supplier' | 'api' | 'estimation' | 'gridOperator';

export type ConsumptionUnit = 'kilowattHour' | 'megaWattHour' | 'cubicMeter';

export type Contact = {
    id: string;
    type?: ContactType;
    target?: null | string;
};

export type ContactType = 'internet' | 'phone' | 'email';

export type ContractType = 'defaultSupply' | 'emergencySupply' | 'standard' | 'indefinite';

export type DeliveryPoint = {
    id: string;
    name: string;
    meterSupplierStatus?: MeterSupplierStatus;
    address: Address;
    meter: Meter;
    building?: null | Building;
    supplierContracts?: Array<SupplierContract>;
    consumptionsPerYear?: Array<ConsumptionPerYear>;
};

export type EntityLinkedToFile = {
    entityType: string;
    entityId: string;
    displayName: string;
};

export type Error = {
    code?: null | string;
    description?: null | string;
    type?: ErrorType;
    numericType?: number;
    metadata?: null | {
        [key: string]: unknown;
    };
};

export type ErrorOrOfAddress = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: Address;
    firstError?: Error;
};

export type ErrorOrOfDeliveryPoint = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: DeliveryPoint;
    firstError?: Error;
};

export type ErrorOrOfIReadOnlyCollectionOfChangelog = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | Array<Changelog>;
    firstError?: Error;
};

export type ErrorOrOfIReadOnlyCollectionOfConsumption = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | Array<Consumption>;
    firstError?: Error;
};

export type ErrorOrOfIReadOnlyCollectionOfDeliveryPoint = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | Array<DeliveryPoint>;
    firstError?: Error;
};

export type ErrorOrOfIReadOnlyCollectionOfSupplier = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | Array<Supplier>;
    firstError?: Error;
};

export type ErrorOrOfIReadOnlyCollectionOfSupplierContract = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | Array<SupplierContract>;
    firstError?: Error;
};

export type ErrorOrOfSupplier = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: Supplier;
    firstError?: Error;
};

export type ErrorOrOfSupplierContract = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: SupplierContract;
    firstError?: Error;
};

export type ErrorOrOfUnit = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: Unit;
    firstError?: Error;
};

export type ErrorType = 'failure' | 'unexpected' | 'validation' | 'conflict' | 'notFound' | 'unauthorized' | 'forbidden';

export type GeoCoordinates = {
    latitude?: number;
    longitude?: number;
};

export type InvoiceRecipient = {
    id: string;
    name: string;
    legalForm?: null | LegalForm;
    address: Address;
    contacts?: Array<Contact>;
};

export type LegalForm = 'gmbh' | 'ohg' | 'ag' | 'gbr' | 'kg' | 'ug' | 'limited' | 'soleProprietorship' | 'ggmbh' | 'eg' | 'gmbhCoKg';

export type MeasurementLevel = 'low' | 'medium' | 'high';

export type MetaData = {
    additionalData?: null | {
        [key: string]: unknown;
    };
    created?: null | string;
    createdBy?: null | string;
    id?: null | string;
    name?: null | string;
    previewAvailable?: null | boolean;
    previewName?: null | string;
    previewSizeInBytes?: null | number;
    revision?: null | number;
    sizeInBytes?: null | number;
};

export type Meter = {
    id: string;
    meterNumber?: null | string;
    malo?: null | string;
    melo?: null | string;
    meterType?: MeterType;
    meterProduct?: MeterProduct;
    validFrom?: null | string;
    validTo?: null | string;
    ownership?: MeterOwnershipType;
    measurementType?: null | MeterMeasurementType;
    readingRequired?: boolean;
    consumptionUnit?: ConsumptionUnit;
    measurementLevel?: null | MeasurementLevel;
    lastReading?: number;
    lastReadingDate?: null | string;
    notes?: null | string;
};

export type MeterMeasurementType = 'slp' | 'rlm';

export type MeterOwnershipType = 'owner' | 'tenant';

export type MeterProduct = 'gas' | 'electricity' | 'water';

export type MeterSupplierStatus = 'unregistered' | 'registering' | 'registered' | 'unregistering';

export type MeterType = 'analog' | 'digital';

export type Supplier = {
    id: string;
    name: string;
    legalForm?: null | LegalForm;
    address: Address;
    contacts?: Array<Contact>;
};

export type SupplierContract = {
    id: string;
    tariffName?: null | string;
    contractNumber?: null | string;
    customerNumber?: null | string;
    contractType?: ContractType;
    validFrom?: null | string;
    validTo?: null | string;
    contractStartDate?: null | string;
    contractEndDate?: null | string;
    terminationPeriod?: null | number;
    terminationPeriodUnit?: null | TimeUnit;
    renewalPeriod?: null | number;
    renewalPeriodUnit?: null | TimeUnit;
    annualPeakPerformance?: null | string;
    supplier: Supplier;
    invoiceRecipient: InvoiceRecipient;
    benefitRecipient: BenefitRecipient;
};

export type TimeUnit = 'day' | 'week' | 'month' | 'year';

export type Unit = {
    [key: string]: unknown;
};

export type WaveError = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type GetChangelogRecentData = {
    body?: never;
    path?: never;
    query?: {
        top?: number;
    };
    url: '/changelog/recent';
};

export type GetChangelogRecentErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetChangelogRecentError = GetChangelogRecentErrors[keyof GetChangelogRecentErrors];

export type GetChangelogRecentResponses = {
    /**
     * OK
     */
    200: Array<Changelog>;
};

export type GetChangelogRecentResponse = GetChangelogRecentResponses[keyof GetChangelogRecentResponses];

export type GetDeliveryPointsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/delivery-points';
};

export type GetDeliveryPointsErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDeliveryPointsError = GetDeliveryPointsErrors[keyof GetDeliveryPointsErrors];

export type GetDeliveryPointsResponses = {
    /**
     * OK
     */
    200: Array<DeliveryPoint>;
};

export type GetDeliveryPointsResponse = GetDeliveryPointsResponses[keyof GetDeliveryPointsResponses];

export type GetDeliveryPointsRecentData = {
    body?: never;
    path?: never;
    query?: {
        top?: number;
    };
    url: '/delivery-points/recent';
};

export type GetDeliveryPointsRecentErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDeliveryPointsRecentError = GetDeliveryPointsRecentErrors[keyof GetDeliveryPointsRecentErrors];

export type GetDeliveryPointsRecentResponses = {
    /**
     * OK
     */
    200: Array<DeliveryPoint>;
};

export type GetDeliveryPointsRecentResponse = GetDeliveryPointsRecentResponses[keyof GetDeliveryPointsRecentResponses];

export type GetDeliveryPointsRegisteredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/delivery-points/registered';
};

export type GetDeliveryPointsRegisteredErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDeliveryPointsRegisteredError = GetDeliveryPointsRegisteredErrors[keyof GetDeliveryPointsRegisteredErrors];

export type GetDeliveryPointsRegisteredResponses = {
    /**
     * OK
     */
    200: Array<DeliveryPoint>;
};

export type GetDeliveryPointsRegisteredResponse = GetDeliveryPointsRegisteredResponses[keyof GetDeliveryPointsRegisteredResponses];

export type GetAllRegisteredCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/delivery-points/registered/count';
};

export type GetAllRegisteredCountErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetAllRegisteredCountError = GetAllRegisteredCountErrors[keyof GetAllRegisteredCountErrors];

export type GetAllRegisteredCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetAllRegisteredCountResponse = GetAllRegisteredCountResponses[keyof GetAllRegisteredCountResponses];

export type GetDeliveryPointsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/delivery-points/{id}';
};

export type GetDeliveryPointsByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetDeliveryPointsByIdError = GetDeliveryPointsByIdErrors[keyof GetDeliveryPointsByIdErrors];

export type GetDeliveryPointsByIdResponses = {
    /**
     * OK
     */
    200: DeliveryPoint;
};

export type GetDeliveryPointsByIdResponse = GetDeliveryPointsByIdResponses[keyof GetDeliveryPointsByIdResponses];

export type GetDeliveryPointsByIdChangelogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/delivery-points/{id}/changelog';
};

export type GetDeliveryPointsByIdChangelogErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetDeliveryPointsByIdChangelogError = GetDeliveryPointsByIdChangelogErrors[keyof GetDeliveryPointsByIdChangelogErrors];

export type GetDeliveryPointsByIdChangelogResponses = {
    /**
     * OK
     */
    200: Array<Changelog>;
};

export type GetDeliveryPointsByIdChangelogResponse = GetDeliveryPointsByIdChangelogResponses[keyof GetDeliveryPointsByIdChangelogResponses];

export type PostDeliveryPointsByIdRegisterData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/delivery-points/{id}/register';
};

export type PostDeliveryPointsByIdRegisterErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type PostDeliveryPointsByIdRegisterError = PostDeliveryPointsByIdRegisterErrors[keyof PostDeliveryPointsByIdRegisterErrors];

export type PostDeliveryPointsByIdRegisterResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type PostDeliveryPointsByIdRegisterResponse = PostDeliveryPointsByIdRegisterResponses[keyof PostDeliveryPointsByIdRegisterResponses];

export type PostDeliveryPointsByIdUnregisterData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/delivery-points/{id}/unregister';
};

export type PostDeliveryPointsByIdUnregisterErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type PostDeliveryPointsByIdUnregisterError = PostDeliveryPointsByIdUnregisterErrors[keyof PostDeliveryPointsByIdUnregisterErrors];

export type PostDeliveryPointsByIdUnregisterResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type PostDeliveryPointsByIdUnregisterResponse = PostDeliveryPointsByIdUnregisterResponses[keyof PostDeliveryPointsByIdUnregisterResponses];

export type GetFilesLinkedToDeliveryPointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/delivery-points/{id}/files';
};

export type GetFilesLinkedToDeliveryPointResponses = {
    /**
     * OK
     */
    200: Array<MetaData>;
};

export type GetFilesLinkedToDeliveryPointResponse = GetFilesLinkedToDeliveryPointResponses[keyof GetFilesLinkedToDeliveryPointResponses];

export type RemoveFileLinkToDeliveryPointData = {
    body?: never;
    path: {
        entityId: string;
        fileId: string;
    };
    query?: never;
    url: '/delivery-points/{entityId}/files/{fileId}';
};

export type RemoveFileLinkToDeliveryPointErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type RemoveFileLinkToDeliveryPointError = RemoveFileLinkToDeliveryPointErrors[keyof RemoveFileLinkToDeliveryPointErrors];

export type RemoveFileLinkToDeliveryPointResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type RemoveFileLinkToDeliveryPointResponse = RemoveFileLinkToDeliveryPointResponses[keyof RemoveFileLinkToDeliveryPointResponses];

export type AddFileLinkToDeliveryPointData = {
    body?: never;
    path: {
        entityId: string;
        fileId: string;
    };
    query?: never;
    url: '/delivery-points/{entityId}/files/{fileId}';
};

export type AddFileLinkToDeliveryPointErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type AddFileLinkToDeliveryPointError = AddFileLinkToDeliveryPointErrors[keyof AddFileLinkToDeliveryPointErrors];

export type AddFileLinkToDeliveryPointResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type AddFileLinkToDeliveryPointResponse = AddFileLinkToDeliveryPointResponses[keyof AddFileLinkToDeliveryPointResponses];

export type GetConsumptionsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        m?: Array<string>;
        dp?: Array<string>;
    };
    url: '/consumptions';
};

export type GetConsumptionsErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetConsumptionsError = GetConsumptionsErrors[keyof GetConsumptionsErrors];

export type GetConsumptionsResponses = {
    /**
     * OK
     */
    200: Array<Consumption>;
};

export type GetConsumptionsResponse = GetConsumptionsResponses[keyof GetConsumptionsResponses];

export type GetConsumptionsAggregatedCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/consumptions/aggregated/current';
};

export type GetConsumptionsAggregatedCurrentErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetConsumptionsAggregatedCurrentError = GetConsumptionsAggregatedCurrentErrors[keyof GetConsumptionsAggregatedCurrentErrors];

export type GetConsumptionsAggregatedCurrentResponses = {
    /**
     * OK
     */
    200: Array<AggregatedConsumption>;
};

export type GetConsumptionsAggregatedCurrentResponse = GetConsumptionsAggregatedCurrentResponses[keyof GetConsumptionsAggregatedCurrentResponses];

export type GetConsumptionsAggregatedPreviousData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/consumptions/aggregated/previous';
};

export type GetConsumptionsAggregatedPreviousErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetConsumptionsAggregatedPreviousError = GetConsumptionsAggregatedPreviousErrors[keyof GetConsumptionsAggregatedPreviousErrors];

export type GetConsumptionsAggregatedPreviousResponses = {
    /**
     * OK
     */
    200: Array<AggregatedConsumption>;
};

export type GetConsumptionsAggregatedPreviousResponse = GetConsumptionsAggregatedPreviousResponses[keyof GetConsumptionsAggregatedPreviousResponses];

export type GetSupplierContractsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/supplier-contracts';
};

export type GetSupplierContractsErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetSupplierContractsError = GetSupplierContractsErrors[keyof GetSupplierContractsErrors];

export type GetSupplierContractsResponses = {
    /**
     * OK
     */
    200: Array<SupplierContract>;
};

export type GetSupplierContractsResponse = GetSupplierContractsResponses[keyof GetSupplierContractsResponses];

export type GetSupplierContractsRecentData = {
    body?: never;
    path?: never;
    query?: {
        top?: number;
    };
    url: '/supplier-contracts/recent';
};

export type GetSupplierContractsRecentErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetSupplierContractsRecentError = GetSupplierContractsRecentErrors[keyof GetSupplierContractsRecentErrors];

export type GetSupplierContractsRecentResponses = {
    /**
     * OK
     */
    200: Array<SupplierContract>;
};

export type GetSupplierContractsRecentResponse = GetSupplierContractsRecentResponses[keyof GetSupplierContractsRecentResponses];

export type GetSupplierContractsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/supplier-contracts/active';
};

export type GetSupplierContractsActiveErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetSupplierContractsActiveError = GetSupplierContractsActiveErrors[keyof GetSupplierContractsActiveErrors];

export type GetSupplierContractsActiveResponses = {
    /**
     * OK
     */
    200: Array<SupplierContract>;
};

export type GetSupplierContractsActiveResponse = GetSupplierContractsActiveResponses[keyof GetSupplierContractsActiveResponses];

export type GetSupplierContractsActiveCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/supplier-contracts/active/count';
};

export type GetSupplierContractsActiveCountErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetSupplierContractsActiveCountError = GetSupplierContractsActiveCountErrors[keyof GetSupplierContractsActiveCountErrors];

export type GetSupplierContractsActiveCountResponses = {
    /**
     * OK
     */
    200: number;
};

export type GetSupplierContractsActiveCountResponse = GetSupplierContractsActiveCountResponses[keyof GetSupplierContractsActiveCountResponses];

export type GetSupplierContractsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/supplier-contracts/{id}';
};

export type GetSupplierContractsByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSupplierContractsByIdError = GetSupplierContractsByIdErrors[keyof GetSupplierContractsByIdErrors];

export type GetSupplierContractsByIdResponses = {
    /**
     * OK
     */
    200: SupplierContract;
};

export type GetSupplierContractsByIdResponse = GetSupplierContractsByIdResponses[keyof GetSupplierContractsByIdResponses];

export type GetSupplierContractsByIdChangelogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/supplier-contracts/{id}/changelog';
};

export type GetSupplierContractsByIdChangelogErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSupplierContractsByIdChangelogError = GetSupplierContractsByIdChangelogErrors[keyof GetSupplierContractsByIdChangelogErrors];

export type GetSupplierContractsByIdChangelogResponses = {
    /**
     * OK
     */
    200: Array<Changelog>;
};

export type GetSupplierContractsByIdChangelogResponse = GetSupplierContractsByIdChangelogResponses[keyof GetSupplierContractsByIdChangelogResponses];

export type GetSupplierContractsByIdDeliveryPointsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/supplier-contracts/{id}/delivery-points';
};

export type GetSupplierContractsByIdDeliveryPointsErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSupplierContractsByIdDeliveryPointsError = GetSupplierContractsByIdDeliveryPointsErrors[keyof GetSupplierContractsByIdDeliveryPointsErrors];

export type GetSupplierContractsByIdDeliveryPointsResponses = {
    /**
     * OK
     */
    200: Array<DeliveryPoint>;
};

export type GetSupplierContractsByIdDeliveryPointsResponse = GetSupplierContractsByIdDeliveryPointsResponses[keyof GetSupplierContractsByIdDeliveryPointsResponses];

export type GetFilesLinkedToSupplierContractData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/supplier-contracts/{id}/files';
};

export type GetFilesLinkedToSupplierContractResponses = {
    /**
     * OK
     */
    200: Array<MetaData>;
};

export type GetFilesLinkedToSupplierContractResponse = GetFilesLinkedToSupplierContractResponses[keyof GetFilesLinkedToSupplierContractResponses];

export type RemoveFileLinkToSupplierContractData = {
    body?: never;
    path: {
        entityId: string;
        fileId: string;
    };
    query?: never;
    url: '/supplier-contracts/{entityId}/files/{fileId}';
};

export type RemoveFileLinkToSupplierContractErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type RemoveFileLinkToSupplierContractError = RemoveFileLinkToSupplierContractErrors[keyof RemoveFileLinkToSupplierContractErrors];

export type RemoveFileLinkToSupplierContractResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type RemoveFileLinkToSupplierContractResponse = RemoveFileLinkToSupplierContractResponses[keyof RemoveFileLinkToSupplierContractResponses];

export type AddFileLinkToSupplierContractData = {
    body?: never;
    path: {
        entityId: string;
        fileId: string;
    };
    query?: never;
    url: '/supplier-contracts/{entityId}/files/{fileId}';
};

export type AddFileLinkToSupplierContractErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type AddFileLinkToSupplierContractError = AddFileLinkToSupplierContractErrors[keyof AddFileLinkToSupplierContractErrors];

export type AddFileLinkToSupplierContractResponses = {
    /**
     * OK
     */
    200: Unit;
};

export type AddFileLinkToSupplierContractResponse = AddFileLinkToSupplierContractResponses[keyof AddFileLinkToSupplierContractResponses];

export type GetMetersByIdDeliveryPointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/meters/{id}/delivery-point';
};

export type GetMetersByIdDeliveryPointErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetMetersByIdDeliveryPointError = GetMetersByIdDeliveryPointErrors[keyof GetMetersByIdDeliveryPointErrors];

export type GetMetersByIdDeliveryPointResponses = {
    /**
     * OK
     */
    200: DeliveryPoint;
};

export type GetMetersByIdDeliveryPointResponse = GetMetersByIdDeliveryPointResponses[keyof GetMetersByIdDeliveryPointResponses];

export type GetAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/addresses';
};

export type GetAddressesErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetAddressesError = GetAddressesErrors[keyof GetAddressesErrors];

export type GetAddressesResponses = {
    /**
     * OK
     */
    200: Array<Address>;
};

export type GetAddressesResponse = GetAddressesResponses[keyof GetAddressesResponses];

export type GetAddressesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type GetAddressesByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetAddressesByIdError = GetAddressesByIdErrors[keyof GetAddressesByIdErrors];

export type GetAddressesByIdResponses = {
    /**
     * OK
     */
    200: Address;
};

export type GetAddressesByIdResponse = GetAddressesByIdResponses[keyof GetAddressesByIdResponses];

export type GetAddressesByIdChangelogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/addresses/{id}/changelog';
};

export type GetAddressesByIdChangelogErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetAddressesByIdChangelogError = GetAddressesByIdChangelogErrors[keyof GetAddressesByIdChangelogErrors];

export type GetAddressesByIdChangelogResponses = {
    /**
     * OK
     */
    200: Array<Changelog>;
};

export type GetAddressesByIdChangelogResponse = GetAddressesByIdChangelogResponses[keyof GetAddressesByIdChangelogResponses];

export type GetAddressesByIdDeliveryPointsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/addresses/{id}/delivery-points';
};

export type GetAddressesByIdDeliveryPointsErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetAddressesByIdDeliveryPointsError = GetAddressesByIdDeliveryPointsErrors[keyof GetAddressesByIdDeliveryPointsErrors];

export type GetAddressesByIdDeliveryPointsResponses = {
    /**
     * OK
     */
    200: Array<DeliveryPoint>;
};

export type GetAddressesByIdDeliveryPointsResponse = GetAddressesByIdDeliveryPointsResponses[keyof GetAddressesByIdDeliveryPointsResponses];

export type GetAddressesByIdSuppliersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/addresses/{id}/suppliers';
};

export type GetAddressesByIdSuppliersErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetAddressesByIdSuppliersError = GetAddressesByIdSuppliersErrors[keyof GetAddressesByIdSuppliersErrors];

export type GetAddressesByIdSuppliersResponses = {
    /**
     * OK
     */
    200: Array<Supplier>;
};

export type GetAddressesByIdSuppliersResponse = GetAddressesByIdSuppliersResponses[keyof GetAddressesByIdSuppliersResponses];

export type GetSuppliersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/suppliers';
};

export type GetSuppliersErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetSuppliersError = GetSuppliersErrors[keyof GetSuppliersErrors];

export type GetSuppliersResponses = {
    /**
     * OK
     */
    200: Array<Supplier>;
};

export type GetSuppliersResponse = GetSuppliersResponses[keyof GetSuppliersResponses];

export type GetSuppliersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/suppliers/{id}';
};

export type GetSuppliersByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSuppliersByIdError = GetSuppliersByIdErrors[keyof GetSuppliersByIdErrors];

export type GetSuppliersByIdResponses = {
    /**
     * OK
     */
    200: Supplier;
};

export type GetSuppliersByIdResponse = GetSuppliersByIdResponses[keyof GetSuppliersByIdResponses];

export type GetSuppliersByIdChangelogData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/suppliers/{id}/changelog';
};

export type GetSuppliersByIdChangelogErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSuppliersByIdChangelogError = GetSuppliersByIdChangelogErrors[keyof GetSuppliersByIdChangelogErrors];

export type GetSuppliersByIdChangelogResponses = {
    /**
     * OK
     */
    200: Array<Changelog>;
};

export type GetSuppliersByIdChangelogResponse = GetSuppliersByIdChangelogResponses[keyof GetSuppliersByIdChangelogResponses];

export type GetSuppliersByIdSupplierContractsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/suppliers/{id}/supplier-contracts';
};

export type GetSuppliersByIdSupplierContractsErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
};

export type GetSuppliersByIdSupplierContractsError = GetSuppliersByIdSupplierContractsErrors[keyof GetSuppliersByIdSupplierContractsErrors];

export type GetSuppliersByIdSupplierContractsResponses = {
    /**
     * OK
     */
    200: Array<SupplierContract>;
};

export type GetSuppliersByIdSupplierContractsResponse = GetSuppliersByIdSupplierContractsResponses[keyof GetSuppliersByIdSupplierContractsResponses];

export type GetEntitiesLinkedToFileData = {
    body?: never;
    path: {
        fileId: string;
    };
    query?: never;
    url: '/files/{fileId}/entities';
};

export type GetEntitiesLinkedToFileResponses = {
    /**
     * OK
     */
    200: Array<EntityLinkedToFile>;
};

export type GetEntitiesLinkedToFileResponse = GetEntitiesLinkedToFileResponses[keyof GetEntitiesLinkedToFileResponses];
