// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zChangelogType = z.enum(['created', 'updated']);

export const zChangelog = z.object({
    source: z.string(),
    sourceIdentifier: z.uuid(),
    type: zChangelogType,
    timestamp: z.iso.datetime(),
    user: z.union([
        z.null(),
        z.string()
    ])
});

export const zConsumptionCategory = z.enum(['consumption', 'forecast']);

export const zConsumptionSource = z.enum([
    'invoice',
    'measurement',
    'wave',
    'customerDocument',
    'supplier',
    'api',
    'estimation',
    'gridOperator'
]);

export const zConsumptionUnit = z.enum([
    'kilowattHour',
    'megaWattHour',
    'cubicMeter'
]);

export const zAggregatedConsumption = z.object({
    quantity: z.number(),
    unit: zConsumptionUnit,
    start: z.iso.date(),
    end: z.iso.date()
});

export const zConsumptionPerYear = z.object({
    year: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    consumption: z.optional(z.number()),
    unit: z.optional(zConsumptionUnit)
});

export const zContactType = z.enum([
    'internet',
    'phone',
    'email'
]);

export const zContact = z.object({
    id: z.uuid(),
    type: z.optional(zContactType),
    target: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zContractType = z.enum([
    'defaultSupply',
    'emergencySupply',
    'standard',
    'indefinite'
]);

export const zEntityLinkedToFile = z.object({
    entityType: z.string(),
    entityId: z.uuid(),
    displayName: z.string()
});

export const zErrorType = z.enum([
    'failure',
    'unexpected',
    'validation',
    'conflict',
    'notFound',
    'unauthorized',
    'forbidden'
]);

export const zError = z.object({
    code: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    type: z.optional(zErrorType),
    numericType: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    metadata: z.optional(z.union([
        z.null(),
        z.record(z.string(), z.unknown())
    ]))
});

export const zErrorOrOfIReadOnlyCollectionOfChangelog = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.array(zChangelog)
    ])),
    firstError: z.optional(zError)
});

export const zGeoCoordinates = z.object({
    latitude: z.optional(z.number()),
    longitude: z.optional(z.number())
});

export const zAddress = z.object({
    id: z.uuid(),
    street: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    houseNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    addendum: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    postalCode: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    city: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    country: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    coordinates: z.optional(z.union([
        z.null(),
        zGeoCoordinates
    ]))
});

export const zBuilding = z.object({
    id: z.uuid(),
    name: z.string(),
    assetNumber: z.string(),
    address: zAddress
});

export const zErrorOrOfAddress = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zAddress),
    firstError: z.optional(zError)
});

export const zLegalForm = z.enum([
    'gmbh',
    'ohg',
    'ag',
    'gbr',
    'kg',
    'ug',
    'limited',
    'soleProprietorship',
    'ggmbh',
    'eg',
    'gmbhCoKg'
]);

export const zBenefitRecipient = z.object({
    id: z.uuid(),
    name: z.string(),
    legalForm: z.optional(z.union([
        z.null(),
        zLegalForm
    ])),
    address: zAddress,
    contacts: z.optional(z.array(zContact))
});

export const zInvoiceRecipient = z.object({
    id: z.uuid(),
    name: z.string(),
    legalForm: z.optional(z.union([
        z.null(),
        zLegalForm
    ])),
    address: zAddress,
    contacts: z.optional(z.array(zContact))
});

export const zMeasurementLevel = z.enum([
    'low',
    'medium',
    'high'
]);

export const zMetaData = z.object({
    additionalData: z.optional(z.union([
        z.null(),
        z.record(z.string(), z.unknown())
    ])),
    created: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    createdBy: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    id: z.optional(z.union([
        z.null(),
        z.uuid()
    ])),
    name: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    previewAvailable: z.optional(z.union([
        z.null(),
        z.boolean()
    ])),
    previewName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    previewSizeInBytes: z.optional(z.union([
        z.null(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])),
    revision: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    sizeInBytes: z.optional(z.union([
        z.null(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ]))
});

export const zMeterMeasurementType = z.enum(['slp', 'rlm']);

export const zMeterOwnershipType = z.enum(['owner', 'tenant']);

export const zMeterProduct = z.enum([
    'gas',
    'electricity',
    'water'
]);

export const zMeterSupplierStatus = z.enum([
    'unregistered',
    'registering',
    'registered',
    'unregistering'
]);

export const zMeterType = z.enum(['analog', 'digital']);

export const zMeter = z.object({
    id: z.uuid(),
    meterNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    malo: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    melo: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meterType: z.optional(zMeterType),
    meterProduct: z.optional(zMeterProduct),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    ownership: z.optional(zMeterOwnershipType),
    measurementType: z.optional(z.union([
        z.null(),
        zMeterMeasurementType
    ])),
    readingRequired: z.optional(z.boolean()),
    consumptionUnit: z.optional(zConsumptionUnit),
    measurementLevel: z.optional(z.union([
        z.null(),
        zMeasurementLevel
    ])),
    lastReading: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    lastReadingDate: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    notes: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zSupplier = z.object({
    id: z.uuid(),
    name: z.string(),
    legalForm: z.optional(z.union([
        z.null(),
        zLegalForm
    ])),
    address: zAddress,
    contacts: z.optional(z.array(zContact))
});

export const zConsumption = z.object({
    quantity: z.optional(z.number()),
    unit: z.optional(zConsumptionUnit),
    source: z.optional(zConsumptionSource),
    category: z.optional(zConsumptionCategory),
    start: z.optional(z.iso.date()),
    end: z.optional(z.iso.date()),
    meterId: z.uuid(),
    meterNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    meterType: z.optional(zMeterType),
    meterProduct: z.optional(zMeterProduct),
    supplier: z.optional(z.union([
        z.null(),
        zSupplier
    ])),
    deliveryPointId: z.uuid(),
    address: zAddress
});

export const zErrorOrOfIReadOnlyCollectionOfConsumption = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.array(zConsumption)
    ])),
    firstError: z.optional(zError)
});

export const zErrorOrOfIReadOnlyCollectionOfSupplier = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.array(zSupplier)
    ])),
    firstError: z.optional(zError)
});

export const zErrorOrOfSupplier = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zSupplier),
    firstError: z.optional(zError)
});

export const zTimeUnit = z.enum([
    'day',
    'week',
    'month',
    'year'
]);

export const zSupplierContract = z.object({
    id: z.uuid(),
    tariffName: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    contractNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    customerNumber: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    contractType: z.optional(zContractType),
    validFrom: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    validTo: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    contractStartDate: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    contractEndDate: z.optional(z.union([
        z.null(),
        z.iso.date()
    ])),
    terminationPeriod: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    terminationPeriodUnit: z.optional(z.union([
        z.null(),
        zTimeUnit
    ])),
    renewalPeriod: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    renewalPeriodUnit: z.optional(z.union([
        z.null(),
        zTimeUnit
    ])),
    annualPeakPerformance: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    supplier: zSupplier,
    invoiceRecipient: zInvoiceRecipient,
    benefitRecipient: zBenefitRecipient
});

export const zDeliveryPoint = z.object({
    id: z.uuid(),
    name: z.string(),
    meterSupplierStatus: z.optional(zMeterSupplierStatus),
    address: zAddress,
    meter: zMeter,
    building: z.optional(z.union([
        z.null(),
        zBuilding
    ])),
    supplierContracts: z.optional(z.array(zSupplierContract)),
    consumptionsPerYear: z.optional(z.array(zConsumptionPerYear))
});

export const zErrorOrOfDeliveryPoint = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zDeliveryPoint),
    firstError: z.optional(zError)
});

export const zErrorOrOfIReadOnlyCollectionOfDeliveryPoint = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.array(zDeliveryPoint)
    ])),
    firstError: z.optional(zError)
});

export const zErrorOrOfIReadOnlyCollectionOfSupplierContract = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.array(zSupplierContract)
    ])),
    firstError: z.optional(zError)
});

export const zErrorOrOfSupplierContract = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zSupplierContract),
    firstError: z.optional(zError)
});

export const zUnit = z.record(z.string(), z.unknown());

export const zErrorOrOfUnit = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zUnit),
    firstError: z.optional(zError)
});

export const zWaveError = z.object({
    type: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    title: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    status: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    detail: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    instance: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zGetChangelogRecentData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        top: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(4)
    }))
});

/**
 * OK
 */
export const zGetChangelogRecentResponse = z.array(zChangelog);

export const zGetDeliveryPointsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDeliveryPointsResponse = z.array(zDeliveryPoint);

export const zGetDeliveryPointsRecentData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        top: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(4)
    }))
});

/**
 * OK
 */
export const zGetDeliveryPointsRecentResponse = z.array(zDeliveryPoint);

export const zGetDeliveryPointsRegisteredData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDeliveryPointsRegisteredResponse = z.array(zDeliveryPoint);

export const zGetAllRegisteredCountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAllRegisteredCountResponse = z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' });

export const zGetDeliveryPointsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDeliveryPointsByIdResponse = zDeliveryPoint;

export const zGetDeliveryPointsByIdChangelogData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDeliveryPointsByIdChangelogResponse = z.array(zChangelog);

export const zPostDeliveryPointsByIdRegisterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostDeliveryPointsByIdRegisterResponse = zUnit;

export const zPostDeliveryPointsByIdUnregisterData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostDeliveryPointsByIdUnregisterResponse = zUnit;

export const zGetFilesLinkedToDeliveryPointData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetFilesLinkedToDeliveryPointResponse = z.array(zMetaData);

export const zRemoveFileLinkToDeliveryPointData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        entityId: z.uuid(),
        fileId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zRemoveFileLinkToDeliveryPointResponse = zUnit;

export const zAddFileLinkToDeliveryPointData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        entityId: z.uuid(),
        fileId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zAddFileLinkToDeliveryPointResponse = zUnit;

export const zGetConsumptionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        from: z.iso.date(),
        to: z.iso.date(),
        m: z.optional(z.array(z.uuid())),
        dp: z.optional(z.array(z.uuid()))
    })
});

/**
 * OK
 */
export const zGetConsumptionsResponse = z.array(zConsumption);

export const zGetConsumptionsAggregatedCurrentData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetConsumptionsAggregatedCurrentResponse = z.array(zAggregatedConsumption);

export const zGetConsumptionsAggregatedPreviousData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetConsumptionsAggregatedPreviousResponse = z.array(zAggregatedConsumption);

export const zGetSupplierContractsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsResponse = z.array(zSupplierContract);

export const zGetSupplierContractsRecentData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        top: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })).default(4)
    }))
});

/**
 * OK
 */
export const zGetSupplierContractsRecentResponse = z.array(zSupplierContract);

export const zGetSupplierContractsActiveData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsActiveResponse = z.array(zSupplierContract);

export const zGetSupplierContractsActiveCountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsActiveCountResponse = z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' });

export const zGetSupplierContractsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsByIdResponse = zSupplierContract;

export const zGetSupplierContractsByIdChangelogData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsByIdChangelogResponse = z.array(zChangelog);

export const zGetSupplierContractsByIdDeliveryPointsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSupplierContractsByIdDeliveryPointsResponse = z.array(zDeliveryPoint);

export const zGetFilesLinkedToSupplierContractData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetFilesLinkedToSupplierContractResponse = z.array(zMetaData);

export const zRemoveFileLinkToSupplierContractData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        entityId: z.uuid(),
        fileId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zRemoveFileLinkToSupplierContractResponse = zUnit;

export const zAddFileLinkToSupplierContractData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        entityId: z.uuid(),
        fileId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zAddFileLinkToSupplierContractResponse = zUnit;

export const zGetMetersByIdDeliveryPointData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetMetersByIdDeliveryPointResponse = zDeliveryPoint;

export const zGetAddressesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAddressesResponse = z.array(zAddress);

export const zGetAddressesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAddressesByIdResponse = zAddress;

export const zGetAddressesByIdChangelogData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAddressesByIdChangelogResponse = z.array(zChangelog);

export const zGetAddressesByIdDeliveryPointsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAddressesByIdDeliveryPointsResponse = z.array(zDeliveryPoint);

export const zGetAddressesByIdSuppliersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAddressesByIdSuppliersResponse = z.array(zSupplier);

export const zGetSuppliersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSuppliersResponse = z.array(zSupplier);

export const zGetSuppliersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSuppliersByIdResponse = zSupplier;

export const zGetSuppliersByIdChangelogData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSuppliersByIdChangelogResponse = z.array(zChangelog);

export const zGetSuppliersByIdSupplierContractsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetSuppliersByIdSupplierContractsResponse = z.array(zSupplierContract);

export const zGetEntitiesLinkedToFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        fileId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetEntitiesLinkedToFileResponse = z.array(zEntityLinkedToFile);
