// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { addFileLinkToDeliveryPoint, addFileLinkToSupplierContract, getAddresses, getAddressesById, getAddressesByIdChangelog, getAddressesByIdDeliveryPoints, getAddressesByIdSuppliers, getAllRegisteredCount, getChangelogRecent, getConsumptions, getConsumptionsAggregatedCurrent, getConsumptionsAggregatedPrevious, getDeliveryPoints, getDeliveryPointsById, getDeliveryPointsByIdChangelog, getDeliveryPointsRecent, getDeliveryPointsRegistered, getEntitiesLinkedToFile, getFilesLinkedToDeliveryPoint, getFilesLinkedToSupplierContract, getMetersByIdDeliveryPoint, getSupplierContracts, getSupplierContractsActive, getSupplierContractsActiveCount, getSupplierContractsById, getSupplierContractsByIdChangelog, getSupplierContractsByIdDeliveryPoints, getSupplierContractsRecent, getSuppliers, getSuppliersById, getSuppliersByIdChangelog, getSuppliersByIdSupplierContracts, type Options, postDeliveryPointsByIdRegister, postDeliveryPointsByIdUnregister, removeFileLinkToDeliveryPoint, removeFileLinkToSupplierContract } from '../sdk.gen';
import type { AddFileLinkToDeliveryPointData, AddFileLinkToDeliveryPointError, AddFileLinkToDeliveryPointResponse, AddFileLinkToSupplierContractData, AddFileLinkToSupplierContractError, AddFileLinkToSupplierContractResponse, GetAddressesByIdChangelogData, GetAddressesByIdData, GetAddressesByIdDeliveryPointsData, GetAddressesByIdSuppliersData, GetAddressesData, GetAllRegisteredCountData, GetChangelogRecentData, GetConsumptionsAggregatedCurrentData, GetConsumptionsAggregatedPreviousData, GetConsumptionsData, GetDeliveryPointsByIdChangelogData, GetDeliveryPointsByIdData, GetDeliveryPointsData, GetDeliveryPointsRecentData, GetDeliveryPointsRegisteredData, GetEntitiesLinkedToFileData, GetFilesLinkedToDeliveryPointData, GetFilesLinkedToSupplierContractData, GetMetersByIdDeliveryPointData, GetSupplierContractsActiveCountData, GetSupplierContractsActiveData, GetSupplierContractsByIdChangelogData, GetSupplierContractsByIdData, GetSupplierContractsByIdDeliveryPointsData, GetSupplierContractsData, GetSupplierContractsRecentData, GetSuppliersByIdChangelogData, GetSuppliersByIdData, GetSuppliersByIdSupplierContractsData, GetSuppliersData, PostDeliveryPointsByIdRegisterData, PostDeliveryPointsByIdRegisterError, PostDeliveryPointsByIdRegisterResponse, PostDeliveryPointsByIdUnregisterData, PostDeliveryPointsByIdUnregisterError, PostDeliveryPointsByIdUnregisterResponse, RemoveFileLinkToDeliveryPointData, RemoveFileLinkToDeliveryPointError, RemoveFileLinkToDeliveryPointResponse, RemoveFileLinkToSupplierContractData, RemoveFileLinkToSupplierContractError, RemoveFileLinkToSupplierContractResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getChangelogRecentQueryKey = (options?: Options<GetChangelogRecentData>) => createQueryKey('getChangelogRecent', options, ['Changelog']);

export const getChangelogRecentQuery = defineQueryOptions((options?: Options<GetChangelogRecentData>) => ({
    key: getChangelogRecentQueryKey(options),
    query: async (context) => {
        const { data } = await getChangelogRecent({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeliveryPointsQueryKey = (options?: Options<GetDeliveryPointsData>) => createQueryKey('getDeliveryPoints', options, ['DeliveryPoints']);

export const getDeliveryPointsQuery = defineQueryOptions((options?: Options<GetDeliveryPointsData>) => ({
    key: getDeliveryPointsQueryKey(options),
    query: async (context) => {
        const { data } = await getDeliveryPoints({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeliveryPointsRecentQueryKey = (options?: Options<GetDeliveryPointsRecentData>) => createQueryKey('getDeliveryPointsRecent', options, ['DeliveryPoints']);

export const getDeliveryPointsRecentQuery = defineQueryOptions((options?: Options<GetDeliveryPointsRecentData>) => ({
    key: getDeliveryPointsRecentQueryKey(options),
    query: async (context) => {
        const { data } = await getDeliveryPointsRecent({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeliveryPointsRegisteredQueryKey = (options?: Options<GetDeliveryPointsRegisteredData>) => createQueryKey('getDeliveryPointsRegistered', options, ['DeliveryPoints']);

export const getDeliveryPointsRegisteredQuery = defineQueryOptions((options?: Options<GetDeliveryPointsRegisteredData>) => ({
    key: getDeliveryPointsRegisteredQueryKey(options),
    query: async (context) => {
        const { data } = await getDeliveryPointsRegistered({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAllRegisteredCountQueryKey = (options?: Options<GetAllRegisteredCountData>) => createQueryKey('getAllRegisteredCount', options, ['DeliveryPoints']);

export const getAllRegisteredCountQuery = defineQueryOptions((options?: Options<GetAllRegisteredCountData>) => ({
    key: getAllRegisteredCountQueryKey(options),
    query: async (context) => {
        const { data } = await getAllRegisteredCount({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeliveryPointsByIdQueryKey = (options: Options<GetDeliveryPointsByIdData>) => createQueryKey('getDeliveryPointsById', options, ['DeliveryPoints']);

export const getDeliveryPointsByIdQuery = defineQueryOptions((options: Options<GetDeliveryPointsByIdData>) => ({
    key: getDeliveryPointsByIdQueryKey(options),
    query: async (context) => {
        const { data } = await getDeliveryPointsById({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDeliveryPointsByIdChangelogQueryKey = (options: Options<GetDeliveryPointsByIdChangelogData>) => createQueryKey('getDeliveryPointsByIdChangelog', options, ['DeliveryPoints']);

export const getDeliveryPointsByIdChangelogQuery = defineQueryOptions((options: Options<GetDeliveryPointsByIdChangelogData>) => ({
    key: getDeliveryPointsByIdChangelogQueryKey(options),
    query: async (context) => {
        const { data } = await getDeliveryPointsByIdChangelog({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postDeliveryPointsByIdRegisterMutation = (options?: Partial<Options<PostDeliveryPointsByIdRegisterData>>): UseMutationOptions<PostDeliveryPointsByIdRegisterResponse, Options<PostDeliveryPointsByIdRegisterData>, PostDeliveryPointsByIdRegisterError> => ({
    mutation: async (vars) => {
        const { data } = await postDeliveryPointsByIdRegister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postDeliveryPointsByIdUnregisterMutation = (options?: Partial<Options<PostDeliveryPointsByIdUnregisterData>>): UseMutationOptions<PostDeliveryPointsByIdUnregisterResponse, Options<PostDeliveryPointsByIdUnregisterData>, PostDeliveryPointsByIdUnregisterError> => ({
    mutation: async (vars) => {
        const { data } = await postDeliveryPointsByIdUnregister({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getFilesLinkedToDeliveryPointQueryKey = (options: Options<GetFilesLinkedToDeliveryPointData>) => createQueryKey('getFilesLinkedToDeliveryPoint', options, ['DeliveryPoints']);

export const getFilesLinkedToDeliveryPointQuery = defineQueryOptions((options: Options<GetFilesLinkedToDeliveryPointData>) => ({
    key: getFilesLinkedToDeliveryPointQueryKey(options),
    query: async (context) => {
        const { data } = await getFilesLinkedToDeliveryPoint({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const removeFileLinkToDeliveryPointMutation = (options?: Partial<Options<RemoveFileLinkToDeliveryPointData>>): UseMutationOptions<RemoveFileLinkToDeliveryPointResponse, Options<RemoveFileLinkToDeliveryPointData>, RemoveFileLinkToDeliveryPointError> => ({
    mutation: async (vars) => {
        const { data } = await removeFileLinkToDeliveryPoint({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const addFileLinkToDeliveryPointMutation = (options?: Partial<Options<AddFileLinkToDeliveryPointData>>): UseMutationOptions<AddFileLinkToDeliveryPointResponse, Options<AddFileLinkToDeliveryPointData>, AddFileLinkToDeliveryPointError> => ({
    mutation: async (vars) => {
        const { data } = await addFileLinkToDeliveryPoint({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getConsumptionsQueryKey = (options: Options<GetConsumptionsData>) => createQueryKey('getConsumptions', options, ['Consumptions']);

export const getConsumptionsQuery = defineQueryOptions((options: Options<GetConsumptionsData>) => ({
    key: getConsumptionsQueryKey(options),
    query: async (context) => {
        const { data } = await getConsumptions({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getConsumptionsAggregatedCurrentQueryKey = (options?: Options<GetConsumptionsAggregatedCurrentData>) => createQueryKey('getConsumptionsAggregatedCurrent', options, ['Consumptions']);

export const getConsumptionsAggregatedCurrentQuery = defineQueryOptions((options?: Options<GetConsumptionsAggregatedCurrentData>) => ({
    key: getConsumptionsAggregatedCurrentQueryKey(options),
    query: async (context) => {
        const { data } = await getConsumptionsAggregatedCurrent({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getConsumptionsAggregatedPreviousQueryKey = (options?: Options<GetConsumptionsAggregatedPreviousData>) => createQueryKey('getConsumptionsAggregatedPrevious', options, ['Consumptions']);

export const getConsumptionsAggregatedPreviousQuery = defineQueryOptions((options?: Options<GetConsumptionsAggregatedPreviousData>) => ({
    key: getConsumptionsAggregatedPreviousQueryKey(options),
    query: async (context) => {
        const { data } = await getConsumptionsAggregatedPrevious({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsQueryKey = (options?: Options<GetSupplierContractsData>) => createQueryKey('getSupplierContracts', options, ['SupplierContracts']);

export const getSupplierContractsQuery = defineQueryOptions((options?: Options<GetSupplierContractsData>) => ({
    key: getSupplierContractsQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContracts({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsRecentQueryKey = (options?: Options<GetSupplierContractsRecentData>) => createQueryKey('getSupplierContractsRecent', options, ['SupplierContracts']);

export const getSupplierContractsRecentQuery = defineQueryOptions((options?: Options<GetSupplierContractsRecentData>) => ({
    key: getSupplierContractsRecentQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsRecent({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsActiveQueryKey = (options?: Options<GetSupplierContractsActiveData>) => createQueryKey('getSupplierContractsActive', options, ['SupplierContracts']);

export const getSupplierContractsActiveQuery = defineQueryOptions((options?: Options<GetSupplierContractsActiveData>) => ({
    key: getSupplierContractsActiveQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsActive({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsActiveCountQueryKey = (options?: Options<GetSupplierContractsActiveCountData>) => createQueryKey('getSupplierContractsActiveCount', options, ['SupplierContracts']);

export const getSupplierContractsActiveCountQuery = defineQueryOptions((options?: Options<GetSupplierContractsActiveCountData>) => ({
    key: getSupplierContractsActiveCountQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsActiveCount({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsByIdQueryKey = (options: Options<GetSupplierContractsByIdData>) => createQueryKey('getSupplierContractsById', options, ['SupplierContracts']);

export const getSupplierContractsByIdQuery = defineQueryOptions((options: Options<GetSupplierContractsByIdData>) => ({
    key: getSupplierContractsByIdQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsById({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsByIdChangelogQueryKey = (options: Options<GetSupplierContractsByIdChangelogData>) => createQueryKey('getSupplierContractsByIdChangelog', options, ['SupplierContracts']);

export const getSupplierContractsByIdChangelogQuery = defineQueryOptions((options: Options<GetSupplierContractsByIdChangelogData>) => ({
    key: getSupplierContractsByIdChangelogQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsByIdChangelog({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSupplierContractsByIdDeliveryPointsQueryKey = (options: Options<GetSupplierContractsByIdDeliveryPointsData>) => createQueryKey('getSupplierContractsByIdDeliveryPoints', options, ['SupplierContracts']);

export const getSupplierContractsByIdDeliveryPointsQuery = defineQueryOptions((options: Options<GetSupplierContractsByIdDeliveryPointsData>) => ({
    key: getSupplierContractsByIdDeliveryPointsQueryKey(options),
    query: async (context) => {
        const { data } = await getSupplierContractsByIdDeliveryPoints({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getFilesLinkedToSupplierContractQueryKey = (options: Options<GetFilesLinkedToSupplierContractData>) => createQueryKey('getFilesLinkedToSupplierContract', options, ['SupplierContracts']);

export const getFilesLinkedToSupplierContractQuery = defineQueryOptions((options: Options<GetFilesLinkedToSupplierContractData>) => ({
    key: getFilesLinkedToSupplierContractQueryKey(options),
    query: async (context) => {
        const { data } = await getFilesLinkedToSupplierContract({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const removeFileLinkToSupplierContractMutation = (options?: Partial<Options<RemoveFileLinkToSupplierContractData>>): UseMutationOptions<RemoveFileLinkToSupplierContractResponse, Options<RemoveFileLinkToSupplierContractData>, RemoveFileLinkToSupplierContractError> => ({
    mutation: async (vars) => {
        const { data } = await removeFileLinkToSupplierContract({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const addFileLinkToSupplierContractMutation = (options?: Partial<Options<AddFileLinkToSupplierContractData>>): UseMutationOptions<AddFileLinkToSupplierContractResponse, Options<AddFileLinkToSupplierContractData>, AddFileLinkToSupplierContractError> => ({
    mutation: async (vars) => {
        const { data } = await addFileLinkToSupplierContract({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getMetersByIdDeliveryPointQueryKey = (options: Options<GetMetersByIdDeliveryPointData>) => createQueryKey('getMetersByIdDeliveryPoint', options, ['Meters']);

export const getMetersByIdDeliveryPointQuery = defineQueryOptions((options: Options<GetMetersByIdDeliveryPointData>) => ({
    key: getMetersByIdDeliveryPointQueryKey(options),
    query: async (context) => {
        const { data } = await getMetersByIdDeliveryPoint({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAddressesQueryKey = (options?: Options<GetAddressesData>) => createQueryKey('getAddresses', options, ['Addresses']);

export const getAddressesQuery = defineQueryOptions((options?: Options<GetAddressesData>) => ({
    key: getAddressesQueryKey(options),
    query: async (context) => {
        const { data } = await getAddresses({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAddressesByIdQueryKey = (options: Options<GetAddressesByIdData>) => createQueryKey('getAddressesById', options, ['Addresses']);

export const getAddressesByIdQuery = defineQueryOptions((options: Options<GetAddressesByIdData>) => ({
    key: getAddressesByIdQueryKey(options),
    query: async (context) => {
        const { data } = await getAddressesById({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAddressesByIdChangelogQueryKey = (options: Options<GetAddressesByIdChangelogData>) => createQueryKey('getAddressesByIdChangelog', options, ['Addresses']);

export const getAddressesByIdChangelogQuery = defineQueryOptions((options: Options<GetAddressesByIdChangelogData>) => ({
    key: getAddressesByIdChangelogQueryKey(options),
    query: async (context) => {
        const { data } = await getAddressesByIdChangelog({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAddressesByIdDeliveryPointsQueryKey = (options: Options<GetAddressesByIdDeliveryPointsData>) => createQueryKey('getAddressesByIdDeliveryPoints', options, ['Addresses']);

export const getAddressesByIdDeliveryPointsQuery = defineQueryOptions((options: Options<GetAddressesByIdDeliveryPointsData>) => ({
    key: getAddressesByIdDeliveryPointsQueryKey(options),
    query: async (context) => {
        const { data } = await getAddressesByIdDeliveryPoints({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getAddressesByIdSuppliersQueryKey = (options: Options<GetAddressesByIdSuppliersData>) => createQueryKey('getAddressesByIdSuppliers', options, ['Addresses']);

export const getAddressesByIdSuppliersQuery = defineQueryOptions((options: Options<GetAddressesByIdSuppliersData>) => ({
    key: getAddressesByIdSuppliersQueryKey(options),
    query: async (context) => {
        const { data } = await getAddressesByIdSuppliers({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSuppliersQueryKey = (options?: Options<GetSuppliersData>) => createQueryKey('getSuppliers', options, ['Suppliers']);

export const getSuppliersQuery = defineQueryOptions((options?: Options<GetSuppliersData>) => ({
    key: getSuppliersQueryKey(options),
    query: async (context) => {
        const { data } = await getSuppliers({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSuppliersByIdQueryKey = (options: Options<GetSuppliersByIdData>) => createQueryKey('getSuppliersById', options, ['Suppliers']);

export const getSuppliersByIdQuery = defineQueryOptions((options: Options<GetSuppliersByIdData>) => ({
    key: getSuppliersByIdQueryKey(options),
    query: async (context) => {
        const { data } = await getSuppliersById({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSuppliersByIdChangelogQueryKey = (options: Options<GetSuppliersByIdChangelogData>) => createQueryKey('getSuppliersByIdChangelog', options, ['Suppliers']);

export const getSuppliersByIdChangelogQuery = defineQueryOptions((options: Options<GetSuppliersByIdChangelogData>) => ({
    key: getSuppliersByIdChangelogQueryKey(options),
    query: async (context) => {
        const { data } = await getSuppliersByIdChangelog({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getSuppliersByIdSupplierContractsQueryKey = (options: Options<GetSuppliersByIdSupplierContractsData>) => createQueryKey('getSuppliersByIdSupplierContracts', options, ['Suppliers']);

export const getSuppliersByIdSupplierContractsQuery = defineQueryOptions((options: Options<GetSuppliersByIdSupplierContractsData>) => ({
    key: getSuppliersByIdSupplierContractsQueryKey(options),
    query: async (context) => {
        const { data } = await getSuppliersByIdSupplierContracts({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getEntitiesLinkedToFileQueryKey = (options: Options<GetEntitiesLinkedToFileData>) => createQueryKey('getEntitiesLinkedToFile', options, ['Files']);

export const getEntitiesLinkedToFileQuery = defineQueryOptions((options: Options<GetEntitiesLinkedToFileData>) => ({
    key: getEntitiesLinkedToFileQueryKey(options),
    query: async (context) => {
        const { data } = await getEntitiesLinkedToFile({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
