// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDirectoriesByIdData, DeleteDirectoriesByIdErrors, DeleteDirectoriesByIdResponses, DeleteFilesByIdData, DeleteFilesByIdErrors, DeleteFilesByIdResponses, GetDirectoriesByNameExistsInSystemBySystemData, GetDirectoriesByNameExistsInSystemBySystemErrors, GetDirectoriesByNameExistsInSystemBySystemResponses, GetDirectoriesForSystemBySystemData, GetDirectoriesForSystemBySystemErrors, GetDirectoriesForSystemBySystemResponses, GetDownloadUrlForFileData, GetDownloadUrlForFileErrors, GetDownloadUrlForFileResponses, GetDownloadUrlForFileVersionData, GetDownloadUrlForFileVersionErrors, GetDownloadUrlForFileVersionResponses, GetDownloadUrlForPreviewOfFileData, GetDownloadUrlForPreviewOfFileErrors, GetDownloadUrlForPreviewOfFileResponses, GetDownloadUrlForPreviewOfFileVersionData, GetDownloadUrlForPreviewOfFileVersionErrors, GetDownloadUrlForPreviewOfFileVersionResponses, GetFilesByNameExistsInDirectoryByDirectoryIdData, GetFilesByNameExistsInDirectoryByDirectoryIdErrors, GetFilesByNameExistsInDirectoryByDirectoryIdResponses, GetLatestFilesData, GetLatestFilesErrors, GetLatestFilesResponses, GetMetaDataForFileData, GetMetaDataForFileErrors, GetMetaDataForFileResponses, GetMetaDataForFileVersionData, GetMetaDataForFileVersionErrors, GetMetaDataForFileVersionResponses, PatchDirectoriesByIdMoveData, PatchDirectoriesByIdMoveErrors, PatchDirectoriesByIdMoveResponses, PatchFilesByIdMoveData, PatchFilesByIdMoveErrors, PatchFilesByIdMoveResponses, PostDirectoriesData, PostDirectoriesErrors, PostDirectoriesResponses, PostFilesSearchData, PostFilesSearchErrors, PostFilesSearchResponses, PostFilesUploadToDirectoryByDirectoryIdData, PostFilesUploadToDirectoryByDirectoryIdErrors, PostFilesUploadToDirectoryByDirectoryIdResponses, PutDirectoriesByIdData, PutDirectoriesByIdErrors, PutDirectoriesByIdResponses, PutFilesByIdData, PutFilesByIdErrors, PutFilesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getDirectoriesForSystemBySystem = <ThrowOnError extends boolean = false>(options: Options<GetDirectoriesForSystemBySystemData, ThrowOnError>) => (options.client ?? client).get<GetDirectoriesForSystemBySystemResponses, GetDirectoriesForSystemBySystemErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories/for/system/{system}',
    ...options
});

export const getDirectoriesByNameExistsInSystemBySystem = <ThrowOnError extends boolean = false>(options: Options<GetDirectoriesByNameExistsInSystemBySystemData, ThrowOnError>) => (options.client ?? client).get<GetDirectoriesByNameExistsInSystemBySystemResponses, GetDirectoriesByNameExistsInSystemBySystemErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories/{name}/exists/in/system/{system}',
    ...options
});

export const postDirectories = <ThrowOnError extends boolean = false>(options: Options<PostDirectoriesData, ThrowOnError>) => (options.client ?? client).post<PostDirectoriesResponses, PostDirectoriesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteDirectoriesById = <ThrowOnError extends boolean = false>(options: Options<DeleteDirectoriesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteDirectoriesByIdResponses, DeleteDirectoriesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories/{id}',
    ...options
});

export const putDirectoriesById = <ThrowOnError extends boolean = false>(options: Options<PutDirectoriesByIdData, ThrowOnError>) => (options.client ?? client).put<PutDirectoriesByIdResponses, PutDirectoriesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const patchDirectoriesByIdMove = <ThrowOnError extends boolean = false>(options: Options<PatchDirectoriesByIdMoveData, ThrowOnError>) => (options.client ?? client).patch<PatchDirectoriesByIdMoveResponses, PatchDirectoriesByIdMoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/directories/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getFilesByNameExistsInDirectoryByDirectoryId = <ThrowOnError extends boolean = false>(options: Options<GetFilesByNameExistsInDirectoryByDirectoryIdData, ThrowOnError>) => (options.client ?? client).get<GetFilesByNameExistsInDirectoryByDirectoryIdResponses, GetFilesByNameExistsInDirectoryByDirectoryIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{name}/exists/in/directory/{directoryId}',
    ...options
});

export const postFilesUploadToDirectoryByDirectoryId = <ThrowOnError extends boolean = false>(options: Options<PostFilesUploadToDirectoryByDirectoryIdData, ThrowOnError>) => (options.client ?? client).post<PostFilesUploadToDirectoryByDirectoryIdResponses, PostFilesUploadToDirectoryByDirectoryIdErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/upload/to/directory/{directoryId}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const deleteFilesById = <ThrowOnError extends boolean = false>(options: Options<DeleteFilesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteFilesByIdResponses, DeleteFilesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}',
    ...options
});

export const putFilesById = <ThrowOnError extends boolean = false>(options: Options<PutFilesByIdData, ThrowOnError>) => (options.client ?? client).put<PutFilesByIdResponses, PutFilesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const patchFilesByIdMove = <ThrowOnError extends boolean = false>(options: Options<PatchFilesByIdMoveData, ThrowOnError>) => (options.client ?? client).patch<PatchFilesByIdMoveResponses, PatchFilesByIdMoveErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postFilesSearch = <ThrowOnError extends boolean = false>(options: Options<PostFilesSearchData, ThrowOnError>) => (options.client ?? client).post<PostFilesSearchResponses, PostFilesSearchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getLatestFiles = <ThrowOnError extends boolean = false>(options: Options<GetLatestFilesData, ThrowOnError>) => (options.client ?? client).get<GetLatestFilesResponses, GetLatestFilesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{system}/latest',
    ...options
});

export const getMetaDataForFile = <ThrowOnError extends boolean = false>(options: Options<GetMetaDataForFileData, ThrowOnError>) => (options.client ?? client).get<GetMetaDataForFileResponses, GetMetaDataForFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/metadata',
    ...options
});

export const getMetaDataForFileVersion = <ThrowOnError extends boolean = false>(options: Options<GetMetaDataForFileVersionData, ThrowOnError>) => (options.client ?? client).get<GetMetaDataForFileVersionResponses, GetMetaDataForFileVersionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/versions/{versionId}/metadata',
    ...options
});

export const getDownloadUrlForFile = <ThrowOnError extends boolean = false>(options: Options<GetDownloadUrlForFileData, ThrowOnError>) => (options.client ?? client).get<GetDownloadUrlForFileResponses, GetDownloadUrlForFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/url',
    ...options
});

export const getDownloadUrlForPreviewOfFile = <ThrowOnError extends boolean = false>(options: Options<GetDownloadUrlForPreviewOfFileData, ThrowOnError>) => (options.client ?? client).get<GetDownloadUrlForPreviewOfFileResponses, GetDownloadUrlForPreviewOfFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/preview/url',
    ...options
});

export const getDownloadUrlForFileVersion = <ThrowOnError extends boolean = false>(options: Options<GetDownloadUrlForFileVersionData, ThrowOnError>) => (options.client ?? client).get<GetDownloadUrlForFileVersionResponses, GetDownloadUrlForFileVersionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/versions/{versionId}/url',
    ...options
});

export const getDownloadUrlForPreviewOfFileVersion = <ThrowOnError extends boolean = false>(options: Options<GetDownloadUrlForPreviewOfFileVersionData, ThrowOnError>) => (options.client ?? client).get<GetDownloadUrlForPreviewOfFileVersionResponses, GetDownloadUrlForPreviewOfFileVersionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'X-Authentication-Id', type: 'apiKey' }],
    url: '/files/{id}/versions/{versionId}/preview/url',
    ...options
});
