// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateADirectory = {
    name: string;
    parentId?: null | string;
    system?: SystemTypes;
};

export type Directory = {
    id: string;
    name: string;
    directories?: null | Array<DirectoryInfo>;
    files?: null | Array<File>;
};

export type DirectoryInfo = {
    id: string;
    name: string;
    hasDirectories: boolean;
};

export type Error = {
    code?: null | string;
    description?: null | string;
    type?: ErrorType;
    numericType?: number;
    metadata?: null | {
        [key: string]: unknown;
    };
};

export type ErrorOrOfboolean = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: boolean;
    firstError?: Error;
};

export type ErrorOrOfDirectory = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: Directory;
    firstError?: Error;
};

export type ErrorOrOfFileAndVersion = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: FileAndVersion;
    firstError?: Error;
};

export type ErrorOrOfGuid = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: string;
    firstError?: Error;
};

export type ErrorOrOfMetaData = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: MetaData;
    firstError?: Error;
};

export type ErrorOrOfSearchResultOfFile = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: SearchResultOfFile;
    firstError?: Error;
};

export type ErrorOrOfstring = {
    isError?: boolean;
    errors?: null | Array<Error>;
    errorsOrEmptyList?: null | Array<Error>;
    value?: null | string;
    firstError?: Error;
};

export type ErrorType = 'failure' | 'unexpected' | 'validation' | 'conflict' | 'notFound' | 'unauthorized' | 'forbidden';

export type File = {
    id: string;
    name: string;
    directoryId: string;
    previewAvailable: boolean;
    sizeInBytes?: number;
    created?: string;
};

export type FileAndVersion = {
    fileId: string;
    versionId: string;
};

export type IFormFile = Blob | File;

export type MetaData = {
    id: string;
    revision?: number;
    name: string;
    sizeInBytes: number;
    previewAvailable: boolean;
    previewName: null | string;
    previewSizeInBytes: null | number;
    created: string;
    createdBy: string;
};

export type MoveADirectory = {
    to?: null | string;
};

export type MoveAFile = {
    to: string;
};

export type RangeOfDateTime = {
    min?: null | string;
    max?: null | string;
};

export type RenameADirectory = {
    name: string;
};

export type RenameAFile = {
    name: string;
};

export type SearchFiles = {
    system: SystemTypes;
    created?: null | RangeOfDateTime;
    skip?: null | number;
    take?: null | number;
    search?: string;
    searchBy?: string;
    sortBy?: string;
    sortingDirection?: null | SortingDirections;
};

export type SearchResultOfFile = {
    count?: number;
    items: Array<File>;
};

export type SortingDirections = 'none' | 'ascending' | 'descending';

export type SystemTypes = 'none' | 'wave' | 'customerPortal';

export type WaveError = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type GetDirectoriesForSystemBySystemData = {
    body?: never;
    path: {
        system: SystemTypes;
    };
    query?: {
        id?: string;
    };
    url: '/directories/for/system/{system}';
};

export type GetDirectoriesForSystemBySystemErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDirectoriesForSystemBySystemError = GetDirectoriesForSystemBySystemErrors[keyof GetDirectoriesForSystemBySystemErrors];

export type GetDirectoriesForSystemBySystemResponses = {
    /**
     * OK
     */
    200: Directory;
};

export type GetDirectoriesForSystemBySystemResponse = GetDirectoriesForSystemBySystemResponses[keyof GetDirectoriesForSystemBySystemResponses];

export type GetDirectoriesByNameExistsInSystemBySystemData = {
    body?: never;
    path: {
        name: string;
        system: SystemTypes;
    };
    query?: never;
    url: '/directories/{name}/exists/in/system/{system}';
};

export type GetDirectoriesByNameExistsInSystemBySystemErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDirectoriesByNameExistsInSystemBySystemError = GetDirectoriesByNameExistsInSystemBySystemErrors[keyof GetDirectoriesByNameExistsInSystemBySystemErrors];

export type GetDirectoriesByNameExistsInSystemBySystemResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetDirectoriesByNameExistsInSystemBySystemResponse = GetDirectoriesByNameExistsInSystemBySystemResponses[keyof GetDirectoriesByNameExistsInSystemBySystemResponses];

export type PostDirectoriesData = {
    body: CreateADirectory;
    path?: never;
    query?: never;
    url: '/directories';
};

export type PostDirectoriesErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PostDirectoriesError = PostDirectoriesErrors[keyof PostDirectoriesErrors];

export type PostDirectoriesResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostDirectoriesResponse = PostDirectoriesResponses[keyof PostDirectoriesResponses];

export type DeleteDirectoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/directories/{id}';
};

export type DeleteDirectoriesByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type DeleteDirectoriesByIdError = DeleteDirectoriesByIdErrors[keyof DeleteDirectoriesByIdErrors];

export type DeleteDirectoriesByIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type DeleteDirectoriesByIdResponse = DeleteDirectoriesByIdResponses[keyof DeleteDirectoriesByIdResponses];

export type PutDirectoriesByIdData = {
    body: RenameADirectory;
    path: {
        id: string;
    };
    query?: never;
    url: '/directories/{id}';
};

export type PutDirectoriesByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PutDirectoriesByIdError = PutDirectoriesByIdErrors[keyof PutDirectoriesByIdErrors];

export type PutDirectoriesByIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type PutDirectoriesByIdResponse = PutDirectoriesByIdResponses[keyof PutDirectoriesByIdResponses];

export type PatchDirectoriesByIdMoveData = {
    body: MoveADirectory;
    path: {
        id: string;
    };
    query?: never;
    url: '/directories/{id}/move';
};

export type PatchDirectoriesByIdMoveErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PatchDirectoriesByIdMoveError = PatchDirectoriesByIdMoveErrors[keyof PatchDirectoriesByIdMoveErrors];

export type PatchDirectoriesByIdMoveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PatchDirectoriesByIdMoveResponse = PatchDirectoriesByIdMoveResponses[keyof PatchDirectoriesByIdMoveResponses];

export type GetFilesByNameExistsInDirectoryByDirectoryIdData = {
    body?: never;
    path: {
        name: string;
        directoryId: string;
    };
    query?: never;
    url: '/files/{name}/exists/in/directory/{directoryId}';
};

export type GetFilesByNameExistsInDirectoryByDirectoryIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetFilesByNameExistsInDirectoryByDirectoryIdError = GetFilesByNameExistsInDirectoryByDirectoryIdErrors[keyof GetFilesByNameExistsInDirectoryByDirectoryIdErrors];

export type GetFilesByNameExistsInDirectoryByDirectoryIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetFilesByNameExistsInDirectoryByDirectoryIdResponse = GetFilesByNameExistsInDirectoryByDirectoryIdResponses[keyof GetFilesByNameExistsInDirectoryByDirectoryIdResponses];

export type PostFilesUploadToDirectoryByDirectoryIdData = {
    body: {
        file: IFormFile;
    };
    path: {
        directoryId: string;
    };
    query?: never;
    url: '/files/upload/to/directory/{directoryId}';
};

export type PostFilesUploadToDirectoryByDirectoryIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PostFilesUploadToDirectoryByDirectoryIdError = PostFilesUploadToDirectoryByDirectoryIdErrors[keyof PostFilesUploadToDirectoryByDirectoryIdErrors];

export type PostFilesUploadToDirectoryByDirectoryIdResponses = {
    /**
     * OK
     */
    200: FileAndVersion;
};

export type PostFilesUploadToDirectoryByDirectoryIdResponse = PostFilesUploadToDirectoryByDirectoryIdResponses[keyof PostFilesUploadToDirectoryByDirectoryIdResponses];

export type DeleteFilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type DeleteFilesByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
    /**
     * Not Found
     */
    404: WaveError;
};

export type DeleteFilesByIdError = DeleteFilesByIdErrors[keyof DeleteFilesByIdErrors];

export type DeleteFilesByIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type DeleteFilesByIdResponse = DeleteFilesByIdResponses[keyof DeleteFilesByIdResponses];

export type PutFilesByIdData = {
    body: RenameAFile;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}';
};

export type PutFilesByIdErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PutFilesByIdError = PutFilesByIdErrors[keyof PutFilesByIdErrors];

export type PutFilesByIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type PutFilesByIdResponse = PutFilesByIdResponses[keyof PutFilesByIdResponses];

export type PatchFilesByIdMoveData = {
    body: MoveAFile;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}/move';
};

export type PatchFilesByIdMoveErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PatchFilesByIdMoveError = PatchFilesByIdMoveErrors[keyof PatchFilesByIdMoveErrors];

export type PatchFilesByIdMoveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PatchFilesByIdMoveResponse = PatchFilesByIdMoveResponses[keyof PatchFilesByIdMoveResponses];

export type PostFilesSearchData = {
    body: SearchFiles;
    path?: never;
    query?: never;
    url: '/files/search';
};

export type PostFilesSearchErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type PostFilesSearchError = PostFilesSearchErrors[keyof PostFilesSearchErrors];

export type PostFilesSearchResponses = {
    /**
     * OK
     */
    200: SearchResultOfFile;
};

export type PostFilesSearchResponse = PostFilesSearchResponses[keyof PostFilesSearchResponses];

export type GetLatestFilesData = {
    body?: never;
    path: {
        system: SystemTypes;
    };
    query?: never;
    url: '/files/{system}/latest';
};

export type GetLatestFilesErrors = {
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetLatestFilesError = GetLatestFilesErrors[keyof GetLatestFilesErrors];

export type GetLatestFilesResponses = {
    /**
     * OK
     */
    200: Array<File>;
};

export type GetLatestFilesResponse = GetLatestFilesResponses[keyof GetLatestFilesResponses];

export type GetMetaDataForFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}/metadata';
};

export type GetMetaDataForFileErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetMetaDataForFileError = GetMetaDataForFileErrors[keyof GetMetaDataForFileErrors];

export type GetMetaDataForFileResponses = {
    /**
     * OK
     */
    200: MetaData;
};

export type GetMetaDataForFileResponse = GetMetaDataForFileResponses[keyof GetMetaDataForFileResponses];

export type GetMetaDataForFileVersionData = {
    body?: never;
    path: {
        id: string;
        versionId: string;
    };
    query?: never;
    url: '/files/{id}/versions/{versionId}/metadata';
};

export type GetMetaDataForFileVersionErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetMetaDataForFileVersionError = GetMetaDataForFileVersionErrors[keyof GetMetaDataForFileVersionErrors];

export type GetMetaDataForFileVersionResponses = {
    /**
     * OK
     */
    200: MetaData;
};

export type GetMetaDataForFileVersionResponse = GetMetaDataForFileVersionResponses[keyof GetMetaDataForFileVersionResponses];

export type GetDownloadUrlForFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}/url';
};

export type GetDownloadUrlForFileErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDownloadUrlForFileError = GetDownloadUrlForFileErrors[keyof GetDownloadUrlForFileErrors];

export type GetDownloadUrlForFileResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDownloadUrlForFileResponse = GetDownloadUrlForFileResponses[keyof GetDownloadUrlForFileResponses];

export type GetDownloadUrlForPreviewOfFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/files/{id}/preview/url';
};

export type GetDownloadUrlForPreviewOfFileErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDownloadUrlForPreviewOfFileError = GetDownloadUrlForPreviewOfFileErrors[keyof GetDownloadUrlForPreviewOfFileErrors];

export type GetDownloadUrlForPreviewOfFileResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDownloadUrlForPreviewOfFileResponse = GetDownloadUrlForPreviewOfFileResponses[keyof GetDownloadUrlForPreviewOfFileResponses];

export type GetDownloadUrlForFileVersionData = {
    body?: never;
    path: {
        id: string;
        versionId: string;
    };
    query?: never;
    url: '/files/{id}/versions/{versionId}/url';
};

export type GetDownloadUrlForFileVersionErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDownloadUrlForFileVersionError = GetDownloadUrlForFileVersionErrors[keyof GetDownloadUrlForFileVersionErrors];

export type GetDownloadUrlForFileVersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDownloadUrlForFileVersionResponse = GetDownloadUrlForFileVersionResponses[keyof GetDownloadUrlForFileVersionResponses];

export type GetDownloadUrlForPreviewOfFileVersionData = {
    body?: never;
    path: {
        id: string;
        versionId: string;
    };
    query?: never;
    url: '/files/{id}/versions/{versionId}/preview/url';
};

export type GetDownloadUrlForPreviewOfFileVersionErrors = {
    /**
     * Bad Request
     */
    400: WaveError;
    /**
     * Unauthorized
     */
    401: WaveError;
    /**
     * Forbidden
     */
    403: WaveError;
};

export type GetDownloadUrlForPreviewOfFileVersionError = GetDownloadUrlForPreviewOfFileVersionErrors[keyof GetDownloadUrlForPreviewOfFileVersionErrors];

export type GetDownloadUrlForPreviewOfFileVersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetDownloadUrlForPreviewOfFileVersionResponse = GetDownloadUrlForPreviewOfFileVersionResponses[keyof GetDownloadUrlForPreviewOfFileVersionResponses];
