// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zDirectoryInfo = z.object({
    id: z.uuid(),
    name: z.string(),
    hasDirectories: z.boolean()
});

export const zErrorType = z.enum([
    'failure',
    'unexpected',
    'validation',
    'conflict',
    'notFound',
    'unauthorized',
    'forbidden'
]);

export const zError = z.object({
    code: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    description: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    type: z.optional(zErrorType),
    numericType: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    metadata: z.optional(z.union([
        z.null(),
        z.record(z.string(), z.unknown())
    ]))
});

export const zErrorOrOfboolean = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.boolean()),
    firstError: z.optional(zError)
});

export const zErrorOrOfGuid = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.uuid()),
    firstError: z.optional(zError)
});

export const zErrorOrOfstring = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    firstError: z.optional(zError)
});

export const zFile = z.object({
    id: z.uuid(),
    name: z.string(),
    directoryId: z.uuid(),
    previewAvailable: z.boolean(),
    sizeInBytes: z.optional(z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })),
    created: z.optional(z.iso.datetime())
});

export const zDirectory = z.object({
    id: z.uuid(),
    name: z.string(),
    directories: z.optional(z.union([
        z.null(),
        z.array(zDirectoryInfo)
    ])),
    files: z.optional(z.union([
        z.null(),
        z.array(zFile)
    ]))
});

export const zErrorOrOfDirectory = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zDirectory),
    firstError: z.optional(zError)
});

export const zFileAndVersion = z.object({
    fileId: z.uuid(),
    versionId: z.uuid()
});

export const zErrorOrOfFileAndVersion = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zFileAndVersion),
    firstError: z.optional(zError)
});

export const zIFormFile = z.string();

export const zMetaData = z.object({
    id: z.uuid(),
    revision: z.optional(z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })),
    name: z.string(),
    sizeInBytes: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    previewAvailable: z.boolean(),
    previewName: z.union([
        z.null(),
        z.string()
    ]),
    previewSizeInBytes: z.union([
        z.null(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ]),
    created: z.iso.datetime(),
    createdBy: z.string()
});

export const zErrorOrOfMetaData = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zMetaData),
    firstError: z.optional(zError)
});

export const zMoveADirectory = z.object({
    to: z.optional(z.union([
        z.null(),
        z.uuid()
    ]))
});

export const zMoveAFile = z.object({
    to: z.uuid()
});

export const zRangeOfDateTime = z.object({
    min: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ])),
    max: z.optional(z.union([
        z.null(),
        z.iso.datetime()
    ]))
});

export const zRenameADirectory = z.object({
    name: z.string()
});

export const zRenameAFile = z.object({
    name: z.string()
});

export const zSearchResultOfFile = z.object({
    count: z.optional(z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })),
    items: z.array(zFile)
});

export const zErrorOrOfSearchResultOfFile = z.object({
    isError: z.optional(z.boolean()),
    errors: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    errorsOrEmptyList: z.optional(z.union([
        z.null(),
        z.array(zError)
    ])),
    value: z.optional(zSearchResultOfFile),
    firstError: z.optional(zError)
});

export const zSortingDirections = z.enum([
    'none',
    'ascending',
    'descending'
]);

export const zSystemTypes = z.enum([
    'none',
    'wave',
    'customerPortal'
]);

export const zCreateADirectory = z.object({
    name: z.string(),
    parentId: z.optional(z.union([
        z.null(),
        z.uuid()
    ])),
    system: z.optional(zSystemTypes)
});

export const zSearchFiles = z.object({
    system: zSystemTypes,
    created: z.optional(z.union([
        z.null(),
        zRangeOfDateTime
    ])),
    skip: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    take: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    search: z.optional(z.string()),
    searchBy: z.optional(z.string()),
    sortBy: z.optional(z.string()),
    sortingDirection: z.optional(z.union([
        z.null(),
        zSortingDirections
    ]))
});

export const zWaveError = z.object({
    type: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    title: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    status: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    detail: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    instance: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zGetDirectoriesForSystemBySystemData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        system: zSystemTypes
    }),
    query: z.optional(z.object({
        id: z.optional(z.uuid())
    }))
});

/**
 * OK
 */
export const zGetDirectoriesForSystemBySystemResponse = zDirectory;

export const zGetDirectoriesByNameExistsInSystemBySystemData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        name: z.string(),
        system: zSystemTypes
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDirectoriesByNameExistsInSystemBySystemResponse = z.boolean();

export const zPostDirectoriesData = z.object({
    body: zCreateADirectory,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostDirectoriesResponse = z.uuid();

export const zDeleteDirectoriesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeleteDirectoriesByIdResponse = z.uuid();

export const zPutDirectoriesByIdData = z.object({
    body: zRenameADirectory,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutDirectoriesByIdResponse = z.uuid();

export const zPatchDirectoriesByIdMoveData = z.object({
    body: zMoveADirectory,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPatchDirectoriesByIdMoveResponse = z.uuid();

export const zGetFilesByNameExistsInDirectoryByDirectoryIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        name: z.string(),
        directoryId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetFilesByNameExistsInDirectoryByDirectoryIdResponse = z.boolean();

export const zPostFilesUploadToDirectoryByDirectoryIdData = z.object({
    body: z.object({
        file: zIFormFile
    }),
    path: z.object({
        directoryId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostFilesUploadToDirectoryByDirectoryIdResponse = zFileAndVersion;

export const zDeleteFilesByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zDeleteFilesByIdResponse = z.uuid();

export const zPutFilesByIdData = z.object({
    body: zRenameAFile,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutFilesByIdResponse = z.uuid();

export const zPatchFilesByIdMoveData = z.object({
    body: zMoveAFile,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPatchFilesByIdMoveResponse = z.uuid();

export const zPostFilesSearchData = z.object({
    body: zSearchFiles,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostFilesSearchResponse = zSearchResultOfFile;

export const zGetLatestFilesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        system: zSystemTypes
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetLatestFilesResponse = z.array(zFile);

export const zGetMetaDataForFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetMetaDataForFileResponse = zMetaData;

export const zGetMetaDataForFileVersionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid(),
        versionId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetMetaDataForFileVersionResponse = zMetaData;

export const zGetDownloadUrlForFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDownloadUrlForFileResponse = z.string();

export const zGetDownloadUrlForPreviewOfFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDownloadUrlForPreviewOfFileResponse = z.string();

export const zGetDownloadUrlForFileVersionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid(),
        versionId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDownloadUrlForFileVersionResponse = z.string();

export const zGetDownloadUrlForPreviewOfFileVersionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid(),
        versionId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetDownloadUrlForPreviewOfFileVersionResponse = z.string();
