// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { fetchElectricityParameters, fetchElectricityTariffs, fetchGasParameters, fetchGasTariffs, fetchNetworkChargeElectricity, fetchNetworkChargeGas, fetchSupplierCardElectricity, fetchSupplierCardGas, fetchSuppliersElectricity, fetchSuppliersGas, fetchSupplierVariantsElectricity, fetchSupplierVariantsGas, fetchTariffResults, fetchUniversalInformationElectricity, fetchUniversalInformationGas, getNetworkChargeResults, getParametersElectricity, getParametersGas, type Options } from '../sdk.gen';
import type { FetchElectricityParametersData, FetchElectricityTariffsData, FetchElectricityTariffsResponse, FetchGasParametersData, FetchGasTariffsData, FetchGasTariffsResponse, FetchNetworkChargeElectricityData, FetchNetworkChargeElectricityResponse, FetchNetworkChargeGasData, FetchNetworkChargeGasResponse, FetchSupplierCardElectricityData, FetchSupplierCardGasData, FetchSuppliersElectricityData, FetchSuppliersGasData, FetchSupplierVariantsElectricityData, FetchSupplierVariantsGasData, FetchTariffResultsData, FetchUniversalInformationElectricityData, FetchUniversalInformationElectricityResponse, FetchUniversalInformationGasData, FetchUniversalInformationGasResponse, GetNetworkChargeResultsData, GetParametersElectricityData, GetParametersGasData } from '../types.gen';

export const fetchNetworkChargeElectricityMutation = (options?: Partial<Options<FetchNetworkChargeElectricityData>>): UseMutationOptions<FetchNetworkChargeElectricityResponse, Options<FetchNetworkChargeElectricityData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchNetworkChargeElectricity({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getParametersElectricityQueryKey = (options?: Options<GetParametersElectricityData>) => createQueryKey('getParametersElectricity', options, ['Endpoints']);

export const getParametersElectricityQuery = defineQueryOptions((options?: Options<GetParametersElectricityData>) => ({
    key: getParametersElectricityQueryKey(options),
    query: async (context) => {
        const { data } = await getParametersElectricity({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchNetworkChargeGasMutation = (options?: Partial<Options<FetchNetworkChargeGasData>>): UseMutationOptions<FetchNetworkChargeGasResponse, Options<FetchNetworkChargeGasData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchNetworkChargeGas({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getParametersGasQueryKey = (options?: Options<GetParametersGasData>) => createQueryKey('getParametersGas', options, ['Endpoints']);

export const getParametersGasQuery = defineQueryOptions((options?: Options<GetParametersGasData>) => ({
    key: getParametersGasQueryKey(options),
    query: async (context) => {
        const { data } = await getParametersGas({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getNetworkChargeResultsQueryKey = (options: Options<GetNetworkChargeResultsData>) => createQueryKey('getNetworkChargeResults', options, ['Endpoints']);

export const getNetworkChargeResultsQuery = defineQueryOptions((options: Options<GetNetworkChargeResultsData>) => ({
    key: getNetworkChargeResultsQueryKey(options),
    query: async (context) => {
        const { data } = await getNetworkChargeResults({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchElectricityTariffsMutation = (options?: Partial<Options<FetchElectricityTariffsData>>): UseMutationOptions<FetchElectricityTariffsResponse, Options<FetchElectricityTariffsData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchElectricityTariffs({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const fetchElectricityParametersQueryKey = (options?: Options<FetchElectricityParametersData>) => createQueryKey('fetchElectricityParameters', options, ['Endpoints']);

export const fetchElectricityParametersQuery = defineQueryOptions((options?: Options<FetchElectricityParametersData>) => ({
    key: fetchElectricityParametersQueryKey(options),
    query: async (context) => {
        const { data } = await fetchElectricityParameters({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchGasTariffsMutation = (options?: Partial<Options<FetchGasTariffsData>>): UseMutationOptions<FetchGasTariffsResponse, Options<FetchGasTariffsData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchGasTariffs({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const fetchGasParametersQueryKey = (options?: Options<FetchGasParametersData>) => createQueryKey('fetchGasParameters', options, ['Endpoints']);

export const fetchGasParametersQuery = defineQueryOptions((options?: Options<FetchGasParametersData>) => ({
    key: fetchGasParametersQueryKey(options),
    query: async (context) => {
        const { data } = await fetchGasParameters({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchTariffResultsQueryKey = (options: Options<FetchTariffResultsData>) => createQueryKey('fetchTariffResults', options, ['Endpoints']);

export const fetchTariffResultsQuery = defineQueryOptions((options: Options<FetchTariffResultsData>) => ({
    key: fetchTariffResultsQueryKey(options),
    query: async (context) => {
        const { data } = await fetchTariffResults({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchSuppliersElectricityQueryKey = (options?: Options<FetchSuppliersElectricityData>) => createQueryKey('fetchSuppliersElectricity', options, ['Endpoints']);

export const fetchSuppliersElectricityQuery = defineQueryOptions((options?: Options<FetchSuppliersElectricityData>) => ({
    key: fetchSuppliersElectricityQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSuppliersElectricity({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchSupplierCardElectricityQueryKey = (options: Options<FetchSupplierCardElectricityData>) => createQueryKey('fetchSupplierCardElectricity', options, ['Endpoints']);

export const fetchSupplierCardElectricityQuery = defineQueryOptions((options: Options<FetchSupplierCardElectricityData>) => ({
    key: fetchSupplierCardElectricityQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSupplierCardElectricity({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchSupplierVariantsElectricityQueryKey = (options: Options<FetchSupplierVariantsElectricityData>) => createQueryKey('fetchSupplierVariantsElectricity', options, ['Endpoints']);

export const fetchSupplierVariantsElectricityQuery = defineQueryOptions((options: Options<FetchSupplierVariantsElectricityData>) => ({
    key: fetchSupplierVariantsElectricityQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSupplierVariantsElectricity({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchUniversalInformationElectricityMutation = (options?: Partial<Options<FetchUniversalInformationElectricityData>>): UseMutationOptions<FetchUniversalInformationElectricityResponse, Options<FetchUniversalInformationElectricityData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchUniversalInformationElectricity({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const fetchSuppliersGasQueryKey = (options?: Options<FetchSuppliersGasData>) => createQueryKey('fetchSuppliersGas', options, ['Endpoints']);

export const fetchSuppliersGasQuery = defineQueryOptions((options?: Options<FetchSuppliersGasData>) => ({
    key: fetchSuppliersGasQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSuppliersGas({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchSupplierCardGasQueryKey = (options: Options<FetchSupplierCardGasData>) => createQueryKey('fetchSupplierCardGas', options, ['Endpoints']);

export const fetchSupplierCardGasQuery = defineQueryOptions((options: Options<FetchSupplierCardGasData>) => ({
    key: fetchSupplierCardGasQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSupplierCardGas({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchSupplierVariantsGasQueryKey = (options: Options<FetchSupplierVariantsGasData>) => createQueryKey('fetchSupplierVariantsGas', options, ['Endpoints']);

export const fetchSupplierVariantsGasQuery = defineQueryOptions((options: Options<FetchSupplierVariantsGasData>) => ({
    key: fetchSupplierVariantsGasQueryKey(options),
    query: async (context) => {
        const { data } = await fetchSupplierVariantsGas({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const fetchUniversalInformationGasMutation = (options?: Partial<Options<FetchUniversalInformationGasData>>): UseMutationOptions<FetchUniversalInformationGasResponse, Options<FetchUniversalInformationGasData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await fetchUniversalInformationGas({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
