// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { deleteDirectoriesById, deleteFilesById, getDirectoriesByNameExistsInSystemBySystem, getDirectoriesForSystemBySystem, getDownloadUrlForFile, getDownloadUrlForFileVersion, getDownloadUrlForPreviewOfFile, getDownloadUrlForPreviewOfFileVersion, getFilesByNameExistsInDirectoryByDirectoryId, getLatestFiles, getMetaDataForFile, getMetaDataForFileVersion, type Options, patchDirectoriesByIdMove, patchFilesByIdMove, postDirectories, postFilesSearch, postFilesUploadToDirectoryByDirectoryId, putDirectoriesById, putFilesById } from '../sdk.gen';
import type { DeleteDirectoriesByIdData, DeleteDirectoriesByIdError, DeleteDirectoriesByIdResponse, DeleteFilesByIdData, DeleteFilesByIdError, DeleteFilesByIdResponse, GetDirectoriesByNameExistsInSystemBySystemData, GetDirectoriesForSystemBySystemData, GetDownloadUrlForFileData, GetDownloadUrlForFileVersionData, GetDownloadUrlForPreviewOfFileData, GetDownloadUrlForPreviewOfFileVersionData, GetFilesByNameExistsInDirectoryByDirectoryIdData, GetLatestFilesData, GetMetaDataForFileData, GetMetaDataForFileVersionData, PatchDirectoriesByIdMoveData, PatchDirectoriesByIdMoveError, PatchDirectoriesByIdMoveResponse, PatchFilesByIdMoveData, PatchFilesByIdMoveError, PatchFilesByIdMoveResponse, PostDirectoriesData, PostDirectoriesError, PostDirectoriesResponse, PostFilesSearchData, PostFilesSearchError, PostFilesSearchResponse, PostFilesUploadToDirectoryByDirectoryIdData, PostFilesUploadToDirectoryByDirectoryIdError, PostFilesUploadToDirectoryByDirectoryIdResponse, PutDirectoriesByIdData, PutDirectoriesByIdError, PutDirectoriesByIdResponse, PutFilesByIdData, PutFilesByIdError, PutFilesByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getDirectoriesForSystemBySystemQueryKey = (options: Options<GetDirectoriesForSystemBySystemData>) => createQueryKey('getDirectoriesForSystemBySystem', options, ['Directories']);

export const getDirectoriesForSystemBySystemQuery = defineQueryOptions((options: Options<GetDirectoriesForSystemBySystemData>) => ({
    key: getDirectoriesForSystemBySystemQueryKey(options),
    query: async (context) => {
        const { data } = await getDirectoriesForSystemBySystem({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDirectoriesByNameExistsInSystemBySystemQueryKey = (options: Options<GetDirectoriesByNameExistsInSystemBySystemData>) => createQueryKey('getDirectoriesByNameExistsInSystemBySystem', options, ['Directories']);

export const getDirectoriesByNameExistsInSystemBySystemQuery = defineQueryOptions((options: Options<GetDirectoriesByNameExistsInSystemBySystemData>) => ({
    key: getDirectoriesByNameExistsInSystemBySystemQueryKey(options),
    query: async (context) => {
        const { data } = await getDirectoriesByNameExistsInSystemBySystem({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postDirectoriesMutation = (options?: Partial<Options<PostDirectoriesData>>): UseMutationOptions<PostDirectoriesResponse, Options<PostDirectoriesData>, PostDirectoriesError> => ({
    mutation: async (vars) => {
        const { data } = await postDirectories({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const deleteDirectoriesByIdMutation = (options?: Partial<Options<DeleteDirectoriesByIdData>>): UseMutationOptions<DeleteDirectoriesByIdResponse, Options<DeleteDirectoriesByIdData>, DeleteDirectoriesByIdError> => ({
    mutation: async (vars) => {
        const { data } = await deleteDirectoriesById({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const putDirectoriesByIdMutation = (options?: Partial<Options<PutDirectoriesByIdData>>): UseMutationOptions<PutDirectoriesByIdResponse, Options<PutDirectoriesByIdData>, PutDirectoriesByIdError> => ({
    mutation: async (vars) => {
        const { data } = await putDirectoriesById({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const patchDirectoriesByIdMoveMutation = (options?: Partial<Options<PatchDirectoriesByIdMoveData>>): UseMutationOptions<PatchDirectoriesByIdMoveResponse, Options<PatchDirectoriesByIdMoveData>, PatchDirectoriesByIdMoveError> => ({
    mutation: async (vars) => {
        const { data } = await patchDirectoriesByIdMove({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getFilesByNameExistsInDirectoryByDirectoryIdQueryKey = (options: Options<GetFilesByNameExistsInDirectoryByDirectoryIdData>) => createQueryKey('getFilesByNameExistsInDirectoryByDirectoryId', options, ['Files']);

export const getFilesByNameExistsInDirectoryByDirectoryIdQuery = defineQueryOptions((options: Options<GetFilesByNameExistsInDirectoryByDirectoryIdData>) => ({
    key: getFilesByNameExistsInDirectoryByDirectoryIdQueryKey(options),
    query: async (context) => {
        const { data } = await getFilesByNameExistsInDirectoryByDirectoryId({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postFilesUploadToDirectoryByDirectoryIdMutation = (options?: Partial<Options<PostFilesUploadToDirectoryByDirectoryIdData>>): UseMutationOptions<PostFilesUploadToDirectoryByDirectoryIdResponse, Options<PostFilesUploadToDirectoryByDirectoryIdData>, PostFilesUploadToDirectoryByDirectoryIdError> => ({
    mutation: async (vars) => {
        const { data } = await postFilesUploadToDirectoryByDirectoryId({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const deleteFilesByIdMutation = (options?: Partial<Options<DeleteFilesByIdData>>): UseMutationOptions<DeleteFilesByIdResponse, Options<DeleteFilesByIdData>, DeleteFilesByIdError> => ({
    mutation: async (vars) => {
        const { data } = await deleteFilesById({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const putFilesByIdMutation = (options?: Partial<Options<PutFilesByIdData>>): UseMutationOptions<PutFilesByIdResponse, Options<PutFilesByIdData>, PutFilesByIdError> => ({
    mutation: async (vars) => {
        const { data } = await putFilesById({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const patchFilesByIdMoveMutation = (options?: Partial<Options<PatchFilesByIdMoveData>>): UseMutationOptions<PatchFilesByIdMoveResponse, Options<PatchFilesByIdMoveData>, PatchFilesByIdMoveError> => ({
    mutation: async (vars) => {
        const { data } = await patchFilesByIdMove({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const postFilesSearchMutation = (options?: Partial<Options<PostFilesSearchData>>): UseMutationOptions<PostFilesSearchResponse, Options<PostFilesSearchData>, PostFilesSearchError> => ({
    mutation: async (vars) => {
        const { data } = await postFilesSearch({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getLatestFilesQueryKey = (options: Options<GetLatestFilesData>) => createQueryKey('getLatestFiles', options, ['Files']);

export const getLatestFilesQuery = defineQueryOptions((options: Options<GetLatestFilesData>) => ({
    key: getLatestFilesQueryKey(options),
    query: async (context) => {
        const { data } = await getLatestFiles({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getMetaDataForFileQueryKey = (options: Options<GetMetaDataForFileData>) => createQueryKey('getMetaDataForFile', options, ['Files']);

export const getMetaDataForFileQuery = defineQueryOptions((options: Options<GetMetaDataForFileData>) => ({
    key: getMetaDataForFileQueryKey(options),
    query: async (context) => {
        const { data } = await getMetaDataForFile({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getMetaDataForFileVersionQueryKey = (options: Options<GetMetaDataForFileVersionData>) => createQueryKey('getMetaDataForFileVersion', options, ['Files']);

export const getMetaDataForFileVersionQuery = defineQueryOptions((options: Options<GetMetaDataForFileVersionData>) => ({
    key: getMetaDataForFileVersionQueryKey(options),
    query: async (context) => {
        const { data } = await getMetaDataForFileVersion({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDownloadUrlForFileQueryKey = (options: Options<GetDownloadUrlForFileData>) => createQueryKey('getDownloadUrlForFile', options, ['Files']);

export const getDownloadUrlForFileQuery = defineQueryOptions((options: Options<GetDownloadUrlForFileData>) => ({
    key: getDownloadUrlForFileQueryKey(options),
    query: async (context) => {
        const { data } = await getDownloadUrlForFile({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDownloadUrlForPreviewOfFileQueryKey = (options: Options<GetDownloadUrlForPreviewOfFileData>) => createQueryKey('getDownloadUrlForPreviewOfFile', options, ['Files']);

export const getDownloadUrlForPreviewOfFileQuery = defineQueryOptions((options: Options<GetDownloadUrlForPreviewOfFileData>) => ({
    key: getDownloadUrlForPreviewOfFileQueryKey(options),
    query: async (context) => {
        const { data } = await getDownloadUrlForPreviewOfFile({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDownloadUrlForFileVersionQueryKey = (options: Options<GetDownloadUrlForFileVersionData>) => createQueryKey('getDownloadUrlForFileVersion', options, ['Files']);

export const getDownloadUrlForFileVersionQuery = defineQueryOptions((options: Options<GetDownloadUrlForFileVersionData>) => ({
    key: getDownloadUrlForFileVersionQueryKey(options),
    query: async (context) => {
        const { data } = await getDownloadUrlForFileVersion({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getDownloadUrlForPreviewOfFileVersionQueryKey = (options: Options<GetDownloadUrlForPreviewOfFileVersionData>) => createQueryKey('getDownloadUrlForPreviewOfFileVersion', options, ['Files']);

export const getDownloadUrlForPreviewOfFileVersionQuery = defineQueryOptions((options: Options<GetDownloadUrlForPreviewOfFileVersionData>) => ({
    key: getDownloadUrlForPreviewOfFileVersionQueryKey(options),
    query: async (context) => {
        const { data } = await getDownloadUrlForPreviewOfFileVersion({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
