// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import {
  ajaxAphiaRecordsByNamePart,
  aphiaAttributeKeysById,
  aphiaAttributesByAphiaId,
  aphiaAttributeValuesByCategoryId,
  aphiaChildrenByAphiaId,
  aphiaClassificationByAphiaId,
  aphiaDistributionsByAphiaId,
  aphiaExternalIdByAphiaId,
  aphiaFullRecordByAphiaId,
  aphiaIdByName,
  aphiaIdsByAttributeKeyId,
  aphiaNameByAphiaId,
  aphiaRecordByAphiaId,
  aphiaRecordByExternalId,
  aphiaRecordsByAphiaIds,
  aphiaRecordsByDate,
  aphiaRecordsByMatchNames,
  aphiaRecordsByName,
  aphiaRecordsByNames,
  aphiaRecordsByTaxonRankId,
  aphiaRecordsByVernacular,
  aphiaSourcesByAphiaId,
  aphiaSynonymsByAphiaId,
  aphiaTaxonRanksById,
  aphiaTaxonRanksByName,
  aphiaVernacularsByAphiaId,
  type Options,
} from '../sdk.gen';
import type {
  AjaxAphiaRecordsByNamePartData,
  AphiaAttributeKeysByIdData,
  AphiaAttributesByAphiaIdData,
  AphiaAttributeValuesByCategoryIdData,
  AphiaChildrenByAphiaIdData,
  AphiaClassificationByAphiaIdData,
  AphiaDistributionsByAphiaIdData,
  AphiaExternalIdByAphiaIdData,
  AphiaFullRecordByAphiaIdData,
  AphiaIdByNameData,
  AphiaIdsByAttributeKeyIdData,
  AphiaNameByAphiaIdData,
  AphiaRecordByAphiaIdData,
  AphiaRecordByExternalIdData,
  AphiaRecordsByAphiaIdsData,
  AphiaRecordsByDateData,
  AphiaRecordsByMatchNamesData,
  AphiaRecordsByNameData,
  AphiaRecordsByNamesData,
  AphiaRecordsByTaxonRankIdData,
  AphiaRecordsByVernacularData,
  AphiaSourcesByAphiaIdData,
  AphiaSynonymsByAphiaIdData,
  AphiaTaxonRanksByIdData,
  AphiaTaxonRanksByNameData,
  AphiaVernacularsByAphiaIdData,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const aphiaChildrenByAphiaIdQueryKey = (options: Options<AphiaChildrenByAphiaIdData>) =>
  createQueryKey('aphiaChildrenByAphiaId', options, ['Taxonomic data']);

/**
 * Get the direct children (max. 50) for a given AphiaID
 *
 * Get the direct children (max. 50) for a given AphiaID
 */
export const aphiaChildrenByAphiaIdQuery = defineQueryOptions((options: Options<AphiaChildrenByAphiaIdData>) => ({
  key: aphiaChildrenByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaChildrenByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaClassificationByAphiaIdQueryKey = (options: Options<AphiaClassificationByAphiaIdData>) =>
  createQueryKey('aphiaClassificationByAphiaId', options, ['Taxonomic data']);

/**
 * Get the complete classification for one taxon. This also includes any sub or super ranks.
 *
 * Get the complete classification for one taxon. This also includes any sub or super ranks.
 */
export const aphiaClassificationByAphiaIdQuery = defineQueryOptions(
  (options: Options<AphiaClassificationByAphiaIdData>) => ({
    key: aphiaClassificationByAphiaIdQueryKey(options),
    query: async (context) => {
      const { data } = await aphiaClassificationByAphiaId({
        ...options,
        ...context,
        throwOnError: true,
      });
      return data;
    },
  }),
);

export const aphiaDistributionsByAphiaIdQueryKey = (options: Options<AphiaDistributionsByAphiaIdData>) =>
  createQueryKey('aphiaDistributionsByAphiaId', options, ['Distributions']);

/**
 * Get all distributions for a given AphiaID
 *
 * Get all distributions for a given AphiaID
 */
export const aphiaDistributionsByAphiaIdQuery = defineQueryOptions(
  (options: Options<AphiaDistributionsByAphiaIdData>) => ({
    key: aphiaDistributionsByAphiaIdQueryKey(options),
    query: async (context) => {
      const { data } = await aphiaDistributionsByAphiaId({
        ...options,
        ...context,
        throwOnError: true,
      });
      return data;
    },
  }),
);

export const aphiaExternalIdByAphiaIdQueryKey = (options: Options<AphiaExternalIdByAphiaIdData>) =>
  createQueryKey('aphiaExternalIdByAphiaId', options, ['External Identifiers']);

/**
 * Get any external identifier(s) for a given AphiaID
 *
 * Get any external identifier(s) for a given AphiaID
 */
export const aphiaExternalIdByAphiaIdQuery = defineQueryOptions((options: Options<AphiaExternalIdByAphiaIdData>) => ({
  key: aphiaExternalIdByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaExternalIdByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaIdByNameQueryKey = (options: Options<AphiaIdByNameData>) =>
  createQueryKey('aphiaIdByName', options, ['Taxonomic data']);

/**
 * Get the AphiaID for a given name.
 *
 * Get the AphiaID for a given name. Output: NULL when no match is found; -999 when multiple matches are found; an integer (AphiaID) when one exact match was found
 */
export const aphiaIdByNameQuery = defineQueryOptions((options: Options<AphiaIdByNameData>) => ({
  key: aphiaIdByNameQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaIdByName({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaNameByAphiaIdQueryKey = (options: Options<AphiaNameByAphiaIdData>) =>
  createQueryKey('aphiaNameByAphiaId', options, ['Taxonomic data']);

/**
 * Get the name for a given AphiaID
 *
 * Get the name for a given AphiaID
 */
export const aphiaNameByAphiaIdQuery = defineQueryOptions((options: Options<AphiaNameByAphiaIdData>) => ({
  key: aphiaNameByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaNameByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordByAphiaIdQueryKey = (options: Options<AphiaRecordByAphiaIdData>) =>
  createQueryKey('aphiaRecordByAphiaId', options, ['Taxonomic data']);

/**
 * Get the complete AphiaRecord for a given AphiaID
 *
 * Get the complete AphiaRecord for a given AphiaID
 */
export const aphiaRecordByAphiaIdQuery = defineQueryOptions((options: Options<AphiaRecordByAphiaIdData>) => ({
  key: aphiaRecordByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
  enabled: !!options?.path.ID,
}));

export const aphiaRecordsByAphiaIdsQueryKey = (options: Options<AphiaRecordsByAphiaIdsData>) =>
  createQueryKey('aphiaRecordsByAphiaIds', options, ['Taxonomic data']);

/**
 * Get an AphiaRecord for multiple AphiaIDs in one go (max: 50)
 *
 * Get an AphiaRecord for multiple AphiaIDs in one go (max: 50)
 */
export const aphiaRecordsByAphiaIdsQuery = defineQueryOptions((options: Options<AphiaRecordsByAphiaIdsData>) => ({
  key: aphiaRecordsByAphiaIdsQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByAphiaIds({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordByExternalIdQueryKey = (options: Options<AphiaRecordByExternalIdData>) =>
  createQueryKey('aphiaRecordByExternalId', options, ['External Identifiers']);

/**
 * Get the Aphia Record for a given external identifier
 *
 * Get the Aphia Record for a given external identifier
 */
export const aphiaRecordByExternalIdQuery = defineQueryOptions((options: Options<AphiaRecordByExternalIdData>) => ({
  key: aphiaRecordByExternalIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordByExternalId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByDateQueryKey = (options: Options<AphiaRecordsByDateData>) =>
  createQueryKey('aphiaRecordsByDate', options, ['Taxonomic data']);

/**
 * Lists all AphiaRecords (taxa) that have their last edit action (modified or added) during the specified period
 *
 * Lists all AphiaRecords (taxa) that have their last edit action (modified or added) during the specified period
 */
export const aphiaRecordsByDateQuery = defineQueryOptions((options: Options<AphiaRecordsByDateData>) => ({
  key: aphiaRecordsByDateQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByDate({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByMatchNamesQueryKey = (options: Options<AphiaRecordsByMatchNamesData>) =>
  createQueryKey('aphiaRecordsByMatchNames', options, ['Taxonomic data']);

/**
 * Try to find AphiaRecords using the TAXAMATCH fuzzy matching algorithm by Tony Rees
 *
 * For each given scientific name (may include authority), try to find one or more AphiaRecords, using the TAXAMATCH fuzzy matching algorithm by Tony Rees.<br/>This allows you to (fuzzy) match multiple names in one call. Limited to 50 names at once for performance reasons
 */
export const aphiaRecordsByMatchNamesQuery = defineQueryOptions((options: Options<AphiaRecordsByMatchNamesData>) => ({
  key: aphiaRecordsByMatchNamesQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByMatchNames({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByNameQueryKey = (options: Options<AphiaRecordsByNameData>) =>
  createQueryKey('aphiaRecordsByName', options, ['Taxonomic data']);

/**
 * Get one or more matching (max. 50) AphiaRecords for a given name
 *
 * Get one or more matching (max. 50) AphiaRecords for a given name
 */
export const aphiaRecordsByNameQuery = defineQueryOptions((options: Options<AphiaRecordsByNameData>) => ({
  key: aphiaRecordsByNameQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByName({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByNamesQueryKey = (options: Options<AphiaRecordsByNamesData>) =>
  createQueryKey('aphiaRecordsByNames', options, ['Taxonomic data']);

/**
 * For each given scientific name, try to find one or more AphiaRecords
 *
 * For each given scientific name, try to find one or more AphiaRecords. This allows you to match multiple names in one call. Limited to 500 names at once for performance reasons.
 */
export const aphiaRecordsByNamesQuery = defineQueryOptions((options: Options<AphiaRecordsByNamesData>) => ({
  key: aphiaRecordsByNamesQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByNames({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByVernacularQueryKey = (options: Options<AphiaRecordsByVernacularData>) =>
  createQueryKey('aphiaRecordsByVernacular', options, ['Vernaculars']);

/**
 * Get one or more Aphia Records (max. 50) for a given vernacular
 *
 * Get one or more Aphia Records (max. 50) for a given vernacular
 */
export const aphiaRecordsByVernacularQuery = defineQueryOptions((options: Options<AphiaRecordsByVernacularData>) => ({
  key: aphiaRecordsByVernacularQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByVernacular({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaSynonymsByAphiaIdQueryKey = (options: Options<AphiaSynonymsByAphiaIdData>) =>
  createQueryKey('aphiaSynonymsByAphiaId', options, ['Taxonomic data']);

/**
 * Get all synonyms for a given AphiaID
 *
 * Get all synonyms for a given AphiaID
 */
export const aphiaSynonymsByAphiaIdQuery = defineQueryOptions((options: Options<AphiaSynonymsByAphiaIdData>) => ({
  key: aphiaSynonymsByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaSynonymsByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaVernacularsByAphiaIdQueryKey = (options: Options<AphiaVernacularsByAphiaIdData>) =>
  createQueryKey('aphiaVernacularsByAphiaId', options, ['Vernaculars']);

/**
 * Get all vernaculars for a given AphiaID
 *
 * Get all vernaculars for a given AphiaID
 */
export const aphiaVernacularsByAphiaIdQuery = defineQueryOptions((options: Options<AphiaVernacularsByAphiaIdData>) => ({
  key: aphiaVernacularsByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaVernacularsByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaSourcesByAphiaIdQueryKey = (options: Options<AphiaSourcesByAphiaIdData>) =>
  createQueryKey('aphiaSourcesByAphiaId', options, ['Sources']);

/**
 * Get one or more sources/references including links, for one AphiaID
 *
 * Get one or more sources/references including links, for one AphiaID
 */
export const aphiaSourcesByAphiaIdQuery = defineQueryOptions((options: Options<AphiaSourcesByAphiaIdData>) => ({
  key: aphiaSourcesByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaSourcesByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaTaxonRanksByIdQueryKey = (options: Options<AphiaTaxonRanksByIdData>) =>
  createQueryKey('aphiaTaxonRanksById', options, ['Taxonomic data']);

/**
 * Get taxonomic ranks by their identifier
 *
 * Get taxonomic ranks by their identifier
 */
export const aphiaTaxonRanksByIdQuery = defineQueryOptions((options: Options<AphiaTaxonRanksByIdData>) => ({
  key: aphiaTaxonRanksByIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaTaxonRanksById({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaTaxonRanksByNameQueryKey = (options: Options<AphiaTaxonRanksByNameData>) =>
  createQueryKey('aphiaTaxonRanksByName', options, ['Taxonomic data']);

/**
 * Get taxonomic ranks by their name
 *
 * Get taxonomic ranks by their name
 */
export const aphiaTaxonRanksByNameQuery = defineQueryOptions((options: Options<AphiaTaxonRanksByNameData>) => ({
  key: aphiaTaxonRanksByNameQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaTaxonRanksByName({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaRecordsByTaxonRankIdQueryKey = (options: Options<AphiaRecordsByTaxonRankIdData>) =>
  createQueryKey('aphiaRecordsByTaxonRankId', options, ['Taxonomic data']);

/**
 * Get the AphiaRecords for a given taxonRankID (max 50)
 *
 * Get the AphiaRecords for a given taxonRankID (max 50)
 */
export const aphiaRecordsByTaxonRankIdQuery = defineQueryOptions((options: Options<AphiaRecordsByTaxonRankIdData>) => ({
  key: aphiaRecordsByTaxonRankIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaRecordsByTaxonRankId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaFullRecordByAphiaIdQueryKey = (options: Options<AphiaFullRecordByAphiaIdData>) =>
  createQueryKey('aphiaFullRecordByAphiaId', options, ['Taxonomic data']);

/**
 * Get the complete AphiaFullRecord for a given AphiaID
 *
 * Returns the linked open data implementation of an AphiaRecord for a given AphiaID. There are multiple formats available that can be chosen with the Accept header. The default format is JSON-LD but RDF, Turtle and N-triples are also supported.
 */
export const aphiaFullRecordByAphiaIdQuery = defineQueryOptions((options: Options<AphiaFullRecordByAphiaIdData>) => ({
  key: aphiaFullRecordByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaFullRecordByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaAttributeKeysByIdQueryKey = (options: Options<AphiaAttributeKeysByIdData>) =>
  createQueryKey('aphiaAttributeKeysById', options, ['Attributes']);

/**
 * Get attribute definitions
 *
 * Get attribute definitions. To refer to root items specify ID = &#039;0&#039;
 */
export const aphiaAttributeKeysByIdQuery = defineQueryOptions((options: Options<AphiaAttributeKeysByIdData>) => ({
  key: aphiaAttributeKeysByIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaAttributeKeysById({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaAttributeValuesByCategoryIdQueryKey = (options: Options<AphiaAttributeValuesByCategoryIdData>) =>
  createQueryKey('aphiaAttributeValuesByCategoryId', options, ['Attributes']);

/**
 * Get list values that are grouped by an CateogryID
 *
 * Get list values that are grouped by an CateogryID
 */
export const aphiaAttributeValuesByCategoryIdQuery = defineQueryOptions(
  (options: Options<AphiaAttributeValuesByCategoryIdData>) => ({
    key: aphiaAttributeValuesByCategoryIdQueryKey(options),
    query: async (context) => {
      const { data } = await aphiaAttributeValuesByCategoryId({
        ...options,
        ...context,
        throwOnError: true,
      });
      return data;
    },
  }),
);

export const aphiaIdsByAttributeKeyIdQueryKey = (options: Options<AphiaIdsByAttributeKeyIdData>) =>
  createQueryKey('aphiaIdsByAttributeKeyId', options, ['Attributes']);

/**
 * Get a list of AphiaID's (max 50) with attribute tree for a given attribute definition ID
 *
 * Get a list of AphiaID&#039;s (max 50) with attribute tree for a given attribute definition ID
 */
export const aphiaIdsByAttributeKeyIdQuery = defineQueryOptions((options: Options<AphiaIdsByAttributeKeyIdData>) => ({
  key: aphiaIdsByAttributeKeyIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaIdsByAttributeKeyId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const aphiaAttributesByAphiaIdQueryKey = (options: Options<AphiaAttributesByAphiaIdData>) =>
  createQueryKey('aphiaAttributesByAphiaId', options, ['Attributes']);

/**
 * Get a list of attributes for a given AphiaID
 *
 * Get a list of attributes for a given AphiaID
 */
export const aphiaAttributesByAphiaIdQuery = defineQueryOptions((options: Options<AphiaAttributesByAphiaIdData>) => ({
  key: aphiaAttributesByAphiaIdQueryKey(options),
  query: async (context) => {
    const { data } = await aphiaAttributesByAphiaId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const ajaxAphiaRecordsByNamePartQueryKey = (options: Options<AjaxAphiaRecordsByNamePartData>) =>
  createQueryKey('ajaxAphiaRecordsByNamePart', options, ['Ajax calls']);

/**
 * Get taxa suggestion for a given prefix of a taxon name.
 *
 * Get taxa suggestion for a given prefix of a taxon name.
 */
export const ajaxAphiaRecordsByNamePartQuery = defineQueryOptions(
  (options: Options<AjaxAphiaRecordsByNamePartData>) => ({
    key: ajaxAphiaRecordsByNamePartQueryKey(options),
    query: async (context) => {
      const { data } = await ajaxAphiaRecordsByNamePart({
        ...options,
        ...context,
        throwOnError: true,
      });
      return data;
    },
  }),
);
